<?php 
//$word_data = isset($this->params["word_data"]) ? json_decode($this->params["word_data"]) : json_decode($this->detailKeyword["word_data"]);
//p($word_data);die;
?>
<section class="wrapper site-min-height">
    <div class="get-alert"></div>
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-edit-keyword')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>

    <div class="row" id="frmAddCity">
        <div class="col-lg-12">
            <section class="panel">
                <header id="frmTitle" class="panel-heading">Chỉnh sửa Keyword</header>
                <div class="panel-body">
                    <form id="frm" role="form" class="form-horizontal tasi-form" method="POST">
                        <div class="form-group">
                            <label class="col-lg-2  col-md-2 col-sm-2 control-label"> Tên keyword</label>
                            <div class="col-lg-10 col-md-10 col-sm-10">
                                <input readonly class="form-control" type="text" name="wordName" value = "<?php echo $this->detailKeyword['word_key'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="word_slug" class="col-lg-2  col-md-2 col-sm-2 control-label">URL</label>
                            <div class="col-lg-10 col-md-10 col-sm-10">
                                <input readonly class="form-control" type="text" name="wordSlug" placeholder="Nhập URL" value="<?php echo $this->detailKeyword['word_slug'] ?>">
                            </div>
                        </div>
<!--                        <div class="form-group">
                            <label for="word_parent" class="col-lg-2 col-md-2 col-sm-2 control-label">Thuộc từ khóa</label>
                            <div class="col-lg-10 col-md-10 col-sm-10 width-fix">
                                <select name="word_parent" class="selectbox selectpicker"  data-live-search="true" title="Chọn một từ khóa">
                                    <?php
                                    $key= $this->detailKeyword['word_parent'];                                                  
                                    foreach ($this->arrKeywordList as $keyword) {                             
                                        ?>
                                        <option <?php echo ($keyword['word_id'] ==  $key) ? 'selected="selected"' : '' ?> value="<?php echo $keyword['word_id'] ?>"><?php echo $keyword['word_key'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>-->
                        <div class="form-group">
                            <label for="word_status" class="col-lg-2  col-md-2 col-sm-2 col-sm-2 control-label" value="">Trạng thái</label>
                            <div class="col-lg-10">
                                <select name="word_status" class="multi-select form-control sumo-select-box">
                                    <option value="1" <?php if ($this->detailKeyword['word_status'] == 1): ?>selected="selected"<?php endif; ?>>Hiển thị</option>
                                    <option value="0" <?php if ($this->detailKeyword['word_status'] == 0): ?>selected="selected"<?php endif; ?>>Ẩn</option>
                                </select>
                            </div>
                        </div>                        
                        <div class="form-group">
                            <label for="word_data" class="col-lg-2  col-md-2 col-sm-2 control-label">Từ khóa liên quan</label>
                            <div class="col-lg-10">
                                <?php $word_data = isset($this->params["word_data"]) ? json_decode($this->params["word_data"],true) : json_decode($this->detailKeyword["word_data"],true);
                                   unset($word_data[array_search($this->detailKeyword["word_key"], $word_data)]); 
                                $StringWord = '';
                                    foreach ($word_data as $word){
$StringWord .= trim($word) . '
'; // don't move,please
                                    }
                                    ?>
                                <textarea rows="10" name="word_data" id="Sumary" class="form-control editor"><?php echo trim($StringWord); ?></textarea>
                               
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-lg-offset-3 col-lg-10">
                                <button type="submit" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                                <button type="submit" id="done" class="btn btn-success bt-save" name="save_close"><i class="icon-save"></i> Lưu & Thoát</button> 
                                <input value="0" name="is_close" class="is_close" type="hidden" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>    
</section>
<script type="text/javascript">
    Keyword.index();
</script>