<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-keyword')->getMessages(), $this->flashMessenger()->setNamespace('success-edit-keyword')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>
    <section class="panel">
        <header class="panel-heading">
            Danh sách Keyword
        </header>
        <div class="panel-body">    
            <div class="adv-table editable-table ">  
                <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-3">                  
                        <div id="editable-sample_length" class="dataTables_length no-padding">
                            <a class="btn btn-primary" href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'keyword', 'action' => 'add', 'limit' => $this->params["limit"])); ?>" ><i class="icon-plus-sign-alt"></i> Thêm</a>
                            <a class="btn btn-danger delete-all" href="javascript:;" ><i class="icon-trash "></i> Xóa</a>
                        </div>
                    </div>
                    <div class="col-lg-9 col-md-9 col-sm-9">
                        <form id="frm" class="form-horizontal" role="form" method="GET">
                            <div class="col-xs-9 no-padding">
                                <div class="dataTables_filter no-padding per-100">
                                    <label><input  name="s"  value="<?php echo $this->params["s"]; ?>" type="text" aria-controls="editable-sample" class="per-100 input-seaching form-control medium"></label>
                                </div>
                            </div>
                            <div class="col-xs-3 no-padding-right">
                                <button type="submit" class="btn btn-white per-100" ><i class="icon-search"></i> Tìm kiếm</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col_lg-6" >
                    ID Đang quét: <b><?php echo $this->arrKeywordMaxCrawl; ?></b>, ID cuối cùng:<strong><?php echo $this->arrKeywordMax; ?></strong> / Tổng <b><?php echo $this->arrTotalKeyword; ?></b> dòng hiện tại
                    <div class="col_lg 4">
                            <div class="col-xs-2 no-padding">
                                <div class="dataTables_filter no-padding per-100">
                                    <label><input name="position"  value="" type="text" aria-controls="editable-sample" class="per-100 input-seaching form-control medium" placeholder="vị trí crawler nhảy đến"></label>
                                </div>
                            </div>
                            <div class="col-xs-1 no-padding-right">
                                <button type="button" class="btn btn-white per-100 btn-crawler">OK</button>
                            </div>
                            <div class="edit-info col-xs-5">
                               
                            </div>
                    </div>
                </div>
                <section id="unseen">
                    <table class="table table-bordered table-striped table-condensed cf">
                        <thead class="cf">
                            <tr>
                                <th class="numeric text-center">#</th>
                                <th class="text-center">ID</th>
                                <th class="visible-xs visible-sm visible-md visible-lg"><i class="icon-list-alt"></i> Tên Keyword</th>
                                <th class="text-center">Sort</th>
                                <th class="text-center"><i class="icon-edit"></i> Trạng thái</th>
                                <th class="text-center"><i class="icon-edit"></i> Chức năng</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if ($this->arrKeywordList):
                                foreach ($this->arrKeywordList as $arrKeywordList):
                                    ?>
                                    <tr>
                                        <td class="text-center data-id" width="50"><input type="checkbox" name="data-id[]" clas value="<?php echo $arrKeywordList['word_id'] ?>"/></td>
                                        <td class="text-center"><?php echo $arrKeywordList['word_id']; ?></td>              
                                        <td class="visible-xs visible-sm visible-md visible-lg">
                                            <a class="tooltips" data-placement="top" >
                                                <?php
                                                    echo $arrKeywordList['word_key'];
                                                ?>
                                            </a>
                                        </td>
                                        <td class="text-center">
                                            <?php
                                            if($arrKeywordList['word_level']  == 0){
                                                    echo "<a class='keyword-m0'>keyword mồi</a>";
                                                }else{
                                                    echo "<a class='keyword-api'>keyword api</a>";
                                                }
                                            ?>
                                        </td>
                                        <td class="text-center" width="200">
                                            <?php
                                                if($arrKeywordList['word_status'] == 1){
                                                    echo "Hiển thị";
                                                }else{
                                                    echo "Ẩn";
                                                }
                                            ?>
                                        </td>  
                                        <td class="text-center" width="200">         
                                            <a target="_blank"  href="<?php echo $this->serverUrl() . $this->Url('frontend-search', array('controller' => 'search', 'action' => 'index', 'keySlug' => $arrKeywordList['word_slug'])); ?>"  class="btn btn-primary btn-xs" data-placement="top" data-original-title="Xem keyword"  rel="<?php echo $arrKeywordList['word_id'] ?>"><i class="icon-eye-open"></i> Xem</a>
                                            <a  href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'keyword', 'action' => 'edit', 'id' => $arrKeywordList['word_id'])); ?>"  class="btn btn-primary btn-xs  edit" data-placement="top" data-original-title="Sửa keyword"  rel="<?php echo $arrKeywordList['word_id'] ?>"><i class="icon-pencil"></i> Sửa</a>
                                            <a  class="btn btn-danger btn-xs remove-keyword tooltips" data-placement="top" data-original-title="Xóa danh mục" data-id="<?php echo $arrKeywordList['word_id'] ?>"><i class="icon-trash "></i> Xóa</a>
                                        </td>
                                    </tr>

                                <?php endforeach; ?>
                            <?php else: ?>
                                <tr><td colspan="6" class="text-center">Không có keyword.</td></tr>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </section>
            </div>
            <div>
                <div class="row">
                    <div  class="col-lg-6 col-md-12 col-sm-12 col-xz-12">
                        <div class="form-group">
                            <div  class="col-sm-3 col-md-3 col-xs-3">
                                <select name="limit" class="form-control" onchange="window.location.href = this.value">
                                    <option value="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'keyword', 'action' => 'index', 'limit' => 15, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 15 ? "selected" : "" ?>>15</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'keyword', 'action' => 'index', 'limit' => 30, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 30 ? "selected" : "" ?>>30</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'keyword', 'action' => 'index', 'limit' => 100, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 100 ? "selected" : "" ?>>100</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'keyword', 'action' => 'index', 'limit' => 300, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 300 ? "selected" : "" ?>>300</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'keyword', 'action' => 'index', 'limit' => 500, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 500 ? "selected" : "" ?>>500</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'keyword', 'action' => 'index', 'limit' => 1000, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 1000 ? "selected" : "" ?>>1000</option>
                                </select>
                            </div>
                            <div class = "col-sm-3" style = "padding-top: 10px">Dòng</div>
                        </div>
                    </div>
                    <div class = "col-lg-6 col-md-12 col-sm-12 col-xz-12">
<?php echo $this->paging;
?>
                    </div>
                </div>
            </div>
        </div>
    </section>
</section>
<script type="text/javascript">
    Keyword.index();
</script>