<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-edit-comment')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>

    <div class="row" id="frmEditComment">
        <div class="col-lg-12">
            <section class="panel panel-primary">
                <header id="frmTitle" class="panel-heading">Comment</header>
                <div class="panel-body">
                    <div class="timeline-messages">
                        <?php 
                            foreach ($this->ListComment as $comment):
                                if($comment['comm_parent'] == 0){                            
                        ?>
                        <!-- Comment -->
                        <div class="msg-time-chat">
                            <a class="message-img" href="#"><img alt="" src="<?php echo STATIC_URL . '/b/images/noAvatar.jpg' ?>" class="avatar"></a>
                            <div class="message-body msg-out">
                                <span class="arrow"></span>
                                <div class="text">
                                    <div class="row">
                                        <div class="col-xs-10"
                                            <p class="attribution"><a href="#"><?php echo $comment['user_fullname'] ?> - <?php echo $comment['user_email'] ?></a> at <?php echo date('H:i',$comment['comm_created']) ?> | <?php echo date('d/m/Y',$comment['comm_created']) ?></p>
                                            <p><?php echo $comment['comm_content'] ?></p>
                                        </div>
                                        <div class="col-xs-2">
                                            
                                                <?php if($comment['comm_status'] == 0){ ?>
                                                <i class="icon-unlock-alt" style="font-size: 25px"></i>
                                                <?php }else {?>
                                                <i class="icon-unlock" style="font-size: 25px"></i>
                                                <?php } ?>
                                            
                                            <a href="#" class="comm-edit" data-id ="<?php echo $comment['comm_id'] ?>" style="text-align: center"><i class="icon-wrench" style="font-size: 25px"></i></a>
                                            <a href="#" class="delete" data-id ="<?php echo $comment['comm_id'] ?>" style="text-align: center"><i class="icon-remove" style="font-size: 25px"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                                <?php }else{ ?>
                        <!-- /comment -->

                        <!-- Comment -->
                        <div class="msg-time-chat">
                            <a class="message-img" href="#"><img alt="" src="<?php echo STATIC_URL . '/b/images/noAvatar.jpg' ?>" class="avatar"></a>
                            <div class="message-body msg-out">
                                <span class="arrow"></span>
                                <div class="text" style="margin-left: 40px">
                                    <div class="row">
                                        <div class="col-xs-10"
                                            <p class="attribution"><a href="#"><?php echo $comment['user_fullname'] ?> - <?php echo $comment['user_email'] ?></a> at <?php echo date('H:i',$comment['comm_created']) ?> | <?php echo date('d/m/Y',$comment['comm_created']) ?></p>
                                            <p><?php echo $comment['comm_content'] ?></p>
                                        </div>
                                        <div class="col-xs-2">
                                            
                                                <?php if($comment['comm_status'] == 0){ ?>
                                                <i class="icon-unlock-alt" style="font-size: 25px"></i>
                                                <?php }else {?>
                                                <i class="icon-unlock" style="font-size: 25px"></i>
                                                <?php } ?>
                                           
                                            <a href="#" class="comm-edit" data-id ="<?php echo $comment['comm_id'] ?>" style="text-align: center"><i class="icon-wrench" style="font-size: 25px"></i></a>
                                            <a href="#" class="delete" data-id ="<?php echo $comment['comm_id'] ?>" style="text-align: center"><i class="icon-remove" style="font-size: 25px"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                                <?php } endforeach; ?>
                        <!-- /comment -->                      
                    </div>
                </div>
            </section>
            <section class="panel panel-primary">
                <header id="frmTitle" class="panel-heading">Trả lời comment</header>
                <div class="panel-body">
                    <form method="POST" role="form" class="form-horizontal tasi-form" id="frm" novalidate="novalidate" enctype="multipart/form-data">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label for="user_type" class="col-lg-2 col-sm-2 control-label" value="">Người trả lời</label>
                                <div class="col-lg-10">
                                    <select name="user_type" class="multi-select form-control sumo-select-box">
                                        <option value="1">Admin</option>
                                        <option value="0">User</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="comm_content" class="col-lg-2 col-sm-2 control-label">Nội dung comment:</label>
                                <div class="col-sm-10">
                                    <textarea placeholder="Nhập bình luận" rows="6" value="" name="comm_content" class="form-control"><?php echo $this->params['cont_summary'] ?></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button type="submit" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                                    <input value="0" name="is_close" class="is_close" type="hidden" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
</section>
<script>
    Comment.index();
</script>