<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-times-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = $this->flashMessenger()->setNamespace('success-add-store')->getMessages();
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>

    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <div class="row">
                    <div class="col-lg-12">
                        <section class="panel">
                            <header class="panel-heading">Thêm kho</header>
                            <div class="panel-body">
                                <form method="POST" role="form" class="form-horizontal tasi-form" id="frm" novalidate="novalidate">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="store-code" class="col-lg-2 control-label" value="">Mã SP</label>
                                            <div class="col-lg-3">
                                                <input type="text" value="<?php echo $this->params["prodCode"] ?>" placeholder="Nhập mã sản phẩm" class="form-control" name="prodCode" id="prodID-store">
                                            </div>
                                            <div class="col-lg-3">
                                                <a id="done" class="btn btn-success btn-check"><i class="icon-add"></i> Kiểm tra</a>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="store-name" class="col-lg-2 control-label" value="">Tên SP</label>
                                            <div class="col-lg-10">
                                                <input type="text" value="<?php echo $this->params["prodName"] ?>" placeholder="Nhập tên sản phẩm" class="form-control" name="prodName" id="prodName-store">
                                                <input type="hidden" value="<?php echo $this->params["prodId"] ?>"  class="form-control" name="prodId" id="prodId">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="store-name" class="col-lg-2 control-label" value="">Đơn vị tính</label>
                                            <div class="col-lg-2 col-sm-8 col-md-8 col-xs-12">
                                                <select id="union"  name="union" class="selectbox selectpicker"  data-live-search="true" title="Đơn vị tính">
                                                    <?php for ($i = 1; $i <= 6; ++$i) { ?>
                                                        <option <?php if ($this->params['union'] == $i): ?> selected <?php endif; ?> value="<?php echo $i ?>"><?php echo My\General::getUnitProduct()[$i]; ?></option>
                                                        <?php
                                                    }
                                                    ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="store-phone" class="col-lg-2 control-label" value="">Tổng hàng ký gửi</label>
                                            <div class="col-lg-10">
                                                <input type="text" value="<?php echo $this->params["prodTotal"] ?>" placeholder="Nhập tổng hàng ký gửi" class="form-control" name="prodTotal" id="phone-store">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="store-address" class="col-lg-2 control-label" value="">Ngày</label>
                                            <div class="col-lg-4 col-sm-8 col-md-8 col-xs-12">
                                                <div data-date-format="dd/mm/yyyy" data-date="" class="input-group input-large">
                                                    <input type="text" name="date_from" class="form-control dpd1" placeholder="Từ ngày" value="<?php echo $this->params['date_from'] ?>">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="store-phone" class="col-lg-2 control-label" value="">Giá</label>
                                            <div class="col-lg-10">
                                                <input type="text" value="<?php echo $this->params["prodPrice"] ?>" placeholder="Nhập giá" class="form-control" name="prodPrice" id="phone-store">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="store-phone" class="col-lg-2 control-label" value="">Chiết khấu</label>
                                            <div class="col-lg-10">
                                                <input type="text" value="<?php echo $this->params["storeDiscounts"] ?>" placeholder="Nhập chiết khấu" class="form-control" name="storeDiscounts" id="phone-store">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="store-phone" class="col-lg-2 control-label" value="">Giá bán</label>
                                            <div class="col-lg-10">
                                                <input type="text" value="<?php echo $this->params["storePriceSell"] ?>" placeholder="Nhập giá bán" class="form-control" name="storePriceSell" id="phone-store">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="store-phone" class="col-lg-2 control-label" value="">Chọn NCC</label>
                                            <div class="col-lg-2 col-sm-8 col-md-8 col-xs-12">
                                                <select id="provider"  name="provCode" class="selectbox selectpicker"  data-live-search="true" title="Nhà cung cấp">
                                                    <?php foreach ($this->arrListProvider as $arrListProvider) { ?>
                                                        <option <?php if ($this->params['provCode'] == $arrListProvider['prov_code']): ?> selected <?php endif; ?> value="<?php echo $arrListProvider['prov_code']; ?>"><?php echo $arrListProvider['prov_name']; ?></option>
                                                        <?php
                                                    }
                                                    ?>
                                                </select>
                                            </div>
                                            <a id="done" class="btn btn-success btn-add"><i class="icon-add"></i> Thêm</a>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button type="submit" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                                                <button type="submit" id="done" class="btn btn-success bt-save" name="save_close"><i class="icon-save"></i> Lưu & Thoát</button> 
                                                <input value="0" name="is_close" class="is_close" type="hidden" />
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </section>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    Store.index();
    Store.date();
</script>