<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-payment')->getMessages(), $this->flashMessenger()->setNamespace('success-add-store')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">Danh sách kho</header>
                <div class="panel-body">
                    <form id="frm" class="form-horizontal" role="form" method="GET">
                        <div class="col-xs-3 no-padding">
                        </div>
                        <div class="col-xs-6 no-padding">
                            <div class="dataTables_filter no-padding per-100">
                                <label><input name="s" value="" type="text" aria-controls="editable-sample" class="per-100 input-seaching form-control medium"></label>
                            </div>
                        </div>
                        <div class="col-xs-3 no-padding-right">
                            <button type="submit" class="btn btn-white per-100"><i class="icon-search"></i> Tìm kiếm</button>
                        </div>
                    </form>
                    <section id="unseen">
                        <table class="table table-bordered table-striped table-condensed cf">
                            <thead class="cf">
                                <tr>
                                    <th class="numeric text-center" width="5%">STT</th>
                                    <th class="numeric text-center">Mã SP</th>
                                    <th class="numeric text-center" width="15%">Tên SP</th>
                                    <th class="numeric text-center" width="10%">Tổng hàng ký gửi</th>
                                    <th class="numeric text-center" width="15%">Ngày ký hợp đồng</th>
                                    <th class="numeric text-center" width="10%">Tổng xuất</th>
                                    <th class="numeric text-center" width="10%">Tổng tồn</th>
                                    <th class="numeric text-center" width="10%">Giá NCC</th>
                                    <th class="numeric text-center" width="10%">Giá bán</th>
                                    <th class="numeric text-center" width="10%">Giá chiết khấu</th>
                                    <th class="numeric text-center" width="20%">Doanh thu NCC</th>
                                    <th class="numeric text-center" width="20%">Thanh toán NCC</th>
                                    <th class="numeric text-center" width="20%">Chưa thanh toán</th>
                                    <th class="numeric text-center" width="10%">Trả hàng</th>
                                    <th class="numeric text-center" width="10%">Mã NCC</th>
                                    <th class="numeric text-center" width="20%">Trạng thái</th> 
                                    <th class="numeric text-center">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if ($this->arrStore) {
                                    foreach ($this->arrStore as $key => $value) {
                                        $key ++;
                                        ?>
                                        <tr>
                                            <td style="text-align: center"><?php echo $key ?></td>
                                            <td style="text-align: center"><?php echo $value['prod_code'] ?></td>
                                            <td style="text-align: center"><?php echo $value['store_prod_name'] ?></td>
                                            <td style="text-align: center"><?php echo $value['store_prod_total'] ?></td>
                                            <td style="text-align: center"><?php echo date('d/m/Y', $value['date_contract']) ?></td>
                                            <td style="text-align: center"><?php echo $value['store_export'] ?></td>
                                            <td style="text-align: center"><?php echo number_format($value['store_import']) ?></td>
                                            <td style="text-align: center"><?php echo number_format($value['prov_price']) ?></td>
                                            <td style="text-align: center"><?php echo number_format($value['store_price_sell']) ?></td>
                                            <td style="text-align: center"><?php echo number_format($value['store_discounts']) ?></td>
                                            <td style="text-align: center"><?php echo number_format($value['prov_total']) ?></td>
                                            <td style="text-align: center"><?php echo number_format($value['prov_payment']) ?></td>
                                            <td style="text-align: center"><?php echo number_format($value['prov_not_payment']) ?></td>
                                            <td style="text-align: center"><?php echo $value['prov_return'] ?></td>
                                            <td style="text-align: center"><?php echo $value['prov_code'] ?></td>
                                            <td style="text-align: center">
                                                <?php if ($value['store_status'] == 1) { ?>
                                                    <span class="label label-success tooltips" data-placement="top" data-original-title="Còn hàng"><?php echo My\General::getStatusStore()[$value['store_status']] ?></span>
                                                <?php } else {
                                                    ?>
                                                    <span class="label label-danger tooltips" data-placement="top" data-original-title="Hết hàng"><?php echo My\General::getStatusStore()[$value['store_status']] ?></span>
                                                    <?php
                                                }
                                                ?>
                                            </td>
                                            <td style="text-align: center">
                                                <a href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'store', 'action' => 'edit', 'id' => $value['store_id'])); ?>" data-original-title="Sửa nhà cung cấp" class="btn btn-primary tooltips btn-xs">Sửa</a>
                                                <a href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'store', 'action' => 'paymentProvider', 'id' => $value['store_id'])); ?>" data-original-title="Thanh toán" class="btn btn-success tooltips btn-xs">Thanh toán</a>
                                                <a class="btn btn-danger btn-xs remove tooltips btn-del" data-placement="top" data-original-title="Xóa nhà cung cấp" rel="<?php echo $value['store_id'] ?>">Xóa</a>
                                            </td>
                                        </tr>
                                        <?php
                                    }
                                } else {
                                    echo '<tr><td style="text-align: center" colspan="15">Không tìm thấy dữ liệu</td></tr>';
                                }
                                ?>
                            </tbody>
                        </table>
                    </section>
                    <div>
                        <div class="row">
                            <div  class="col-lg-6">
                                &nbsp;
                            </div>
                            <div class = "col-lg-6">
                                <?php echo $this->paging; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    Store.index();
</script>