<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-times-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = $this->flashMessenger()->setNamespace('success-add-payment')->getMessages();
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>

    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <div class="row">
                    <div class="col-lg-12">
                        <section class="panel">
                            <header class="panel-heading">Thanh toán cho nhà cung cấp</header>
                            <div class="panel-body">
                                <form method="POST" role="form" class="form-horizontal tasi-form" id="frm" novalidate="novalidate">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="prod_name" class="col-lg-2 control-label" value="">Tên sản phẩm</label>
                                            <div class="col-lg-10">
                                                <input type="text" value="<?php echo $this->storeDetail["store_prod_name"] ?>" class="form-control" name="prod_name">
                                                <input type="hidden" value="<?php echo $this->storeDetail["prod_id"] ?>" class="form-control" name="prod_id">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="prov_code" class="col-lg-2 control-label" value="">Mã NCC</label>
                                            <div class="col-lg-10">
                                                <input type="text" value="<?php echo $this->storeDetail["prov_code"] ?>" class="form-control" name="prov_code">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="money" class="col-lg-2 control-label" value="">Số tiền</label>
                                            <div class="col-lg-10">
                                                <input type="text" value="<?php echo $this->params["money"] ?>" placeholder="Nhập số tiền thanh toán" class="form-control" name="money">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button type="submit" id="done" class="btn btn-success bt-save" name="save_close"><i class="icon-save"></i> Lưu & Thoát</button> 
                                                <input value="0" name="is_close" class="is_close" type="hidden" />
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </section>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    Provider.index();
</script>