<!DOCTYPE html>
<html class="html">
    <head>
        <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=0.5">
        <!-- CSS -->
        <?php
        echo $this->headTitle();
        echo $this->headMeta();
        echo $this->headLink();
        echo $this->headScript();
        ?>
        <script>
            var showcartURL = '<?php echo $this->serverUrl() . $this->Url('frontend-order', array('controller' => 'order', 'action' => 'show-cart')); ?>';
            var profile_changecitytUrl = '<?php echo $this->serverUrl() . $this->Url('profile', array('controller' => 'profile', 'action' => 'changecity')); ?>';
            var viewCartURL = '<?php echo $this->serverUrl() . $this->Url('frontend-order', array('controller' => 'order', 'action' => 'view-cart')) ?>';
        </script>
    </head>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-63222712-1', 'auto');
        ga('send', 'pageview');

    </script>
    <script type="application/ld+json">
        {
        "@context": "http://schema.org",
        "@type": "Organization",
        "url": "<?php echo $this->serverUrl(); ?>",
        "logo": "<?php echo STATIC_URL; ?>/f/v1/images/logo-email.png"
        }
    </script>
    <body>
        <?php
        echo $this->render('frontend/topbar');
        echo $this->layout()->content;
        echo $this->render('frontend/footer');
        ?>
    </body>
</html>