<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-edit-menu')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>
    <div class="row" id="frmAddCity">
        <div class="col-lg-12">
            <section class="panel ">
                <header id="frmTitle" class="panel-heading">Chỉnh sửa Menu</header>
                <div class="panel-body">
                    <form id="frm" role="form" class="form-horizontal tasi-form" method="POST">
                        <div class="form-group">
                            <label class="col-lg-3 col-md-3 col-sm-3 control-label"> Tên Menu</label>
                            <div class="col-lg-9 col-md-9 col-sm-9">
                                <input class="form-control" type="text" name="MenuName" value="<?php echo $this->detailMenu['menu_name']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Url" class="col-lg-3 col-md-3 col-sm-3 control-label">Đường dẫn URL</label>
                            <div class="col-lg-9 col-md-9 col-sm-9">
                                <input class="form-control" type="text" name="Url" value="<?php echo $this->detailMenu['menu_url']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="localtion" class="col-lg-3 col-md-3 col-sm-3 control-label">Vị trí menu</label>
                            <div class="col-lg-9 col-md-9 col-sm-9">
                                <select class="form-control" name="localtion" id="localtion">
                                    <option value="">Mời chọn vị trí</option>
                                    <?php foreach (My\General::getMenuLocation() as $key => $location):
                                        ?>
                                        <option <?php echo $this->detailMenu['localtion'] == $key ? 'selected="selected"' : '' ?> value="<?php echo $key ?>"><?php echo $location; ?></option>
                                        <?php
                                    endforeach;
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="class_icon" class="col-lg-3 col-md-3 col-sm-3 control-label">Class Icon</label>
                            <div class="col-lg-9 col-md-9 col-sm-9">
                                <select class="form-control" name="class_icon" id="class_icon">
                                    <option value="">Chọn icon</option>
                                    <?php foreach (My\General::getClassIcon() as $class => $valus):
                                        ?>
                                        <option <?php echo $this->detailMenu['class_icon'] == $class ? 'selected="selected"' : '' ?> value="<?php echo $class ?>"><span class="icon <?php echo $class ?>"></span><?php echo $valus; ?></option>
                                        <?php
                                    endforeach;
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Status" class="col-lg-3 col-md-3 col-sm-3 control-label">Trạng thái</label>
                            <div class="radios col-lg-9 col-md-9 col-sm-9">
                                <label class="label_radio" for="radio" name="Status">
                                    <input type="radio" name="Status" value="1" <?php if ($this->detailMenu['menu_status'] == 1) { ?>checked<?php } ?>>Hiển thị &nbsp;&nbsp;&nbsp;&nbsp;
                                    <input type="radio" name="Status" value="0" <?php if ($this->detailMenu['menu_status'] == 0) { ?>checked<?php } ?>>Không hiển thị
                                </label>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-offset-3 col-md-offset-3 col-sm-offset-3 col-lg-10">
                                <button type="submit" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                                <button type="submit" id="done" class="btn btn-success bt-save" name="save_close"><i class="icon-save"></i> Lưu & Thoát</button> 
                                <input value="0" name="is_close" class="is_close" type="hidden" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    Menu.index();
</script>