<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-tags')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>

    <div class="row" id="frmAddCity">
        <div class="col-lg-12">
            <section class="panel ">
                <header id="frmTitle" class="panel-heading">Thêm Tags mới</header>
                <div class="panel-body">
                    <form id="frm" role="form" class="form-horizontal tasi-form" method="POST">
                        <div class="form-group">
                            <label class="col-lg-2 col-md-2 col-sm-2 control-label"> Tên Tags</label>
                            <div class="col-lg-10 col-md-10 col-sm-10">
                                <input class="form-control" type="text" name="TagsName" placeholder="Nhập tên Tags" value="<?php echo $this->params['TagsName'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tags_slug" class="col-lg-2 col-md-2 col-sm-2 control-label"> URL</label>
                            <div class="col-lg-10 col-md-10 col-sm-10">
                                <input class="form-control" type="text" name="TagsSlug" placeholder="Nhập tên không dấu" value="<?php echo $this->params['TagsSlug'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tags_order" class="col-lg-2 col-md-2 col-sm-2 control-label">Độ ưu tiên</label>
                            <div class="col-lg-10 col-md-10 col-sm-10">
                                <input class="form-control" type="text" name="TagsOrder" placeholder="Nhập Độ ưu tiên" value="<?php echo $this->params['TagsOrder'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tags_status" class="col-lg-2 col-md-2 col-sm-2 col-sm-2 control-label" value="">Tình trạng</label>
                            <div class="col-lg-10 col-md-10 col-sm-10">
                                <select name="tags_status" class="multi-select form-control sumo-select-box">
                                    <option value="1">Hiển thị</option>
                                    <option value="0">Ẩn</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tags_description" class="col-lg-2 col-md-2 col-sm-2 control-label">Mô tả ngắn về Tags</label>
                            <div class="col-lg-10 col-md-10 col-sm-10">
                                <textarea rows="6" name="tags_description" id="Sumary" class="form-control editor" style="">
                                    <?php echo $this->params['tags_description']; ?>
                                </textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tags_meta_title" class="col-lg-2 col-md-2 col-sm-2 control-label">SEO Meta Title</label>
                            <div class="col-lg-10 col-md-10 col-sm-10">
                                <input class="form-control" type="text" name="TagsMetaTitle" placeholder="Nhập SEO Meta Title" value="<?php echo $this->params['TagsMetaTitle'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="Tags_meta_keyword" class="col-lg-2 col-md-2 col-sm-2 control-label">SEO Meta Keyword</label>
                            <div class="col-lg-10 col-md-10 col-sm-10">
                                <input class="form-control" type="text" name="TagsMetaKeyword" placeholder="Nhập SEO Meta Keyword" value="<?php echo $this->params['TagsMetaKeyword'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="Tags_meta_description" class="col-lg-2 col-md-2 col-sm-2 control-label">SEO Meta Description</label>
                            <div class="col-lg-10 col-md-10 col-sm-10">
                                <input class="form-control" type="text" name="TagsMetaDescription" placeholder="Nhập SEO Meta Description" value="<?php echo $this->params['TagsMetaDescription'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="Tags_meta_social" class="col-lg-2 col-md-2 col-sm-2 control-label">SEO Meta Social</label>
                            <div class="col-lg-10 col-md-10 col-sm-10">
                                <input class="form-control" type="text" name="TagsMetaSocial" placeholder="Nhập SEO Meta Social" value="<?php echo $this->params['TagsMetaSocial'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-offset-3 col-lg-10 col-md-10 col-sm-10">
                                <button type="submit" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                                <button type="submit" id="done" class="btn btn-success bt-save" name="save_close"><i class="icon-save"></i> Lưu & Thoát</button> 
                                <input value="0" name="is_close" class="is_close" type="hidden" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
</section>
<script>
    Tags.add();
    Tags.submitClose();
</script>