<section id="unseen">
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="col-lg-2 col-md-3 col-sm-12">
            <a class="btn btn-primary btn-updateProduct" data-placement="top" data-original-title="Cập nhật"><i class="icon-refresh"></i> Làm mới</a>
        </div>
        <label class="col-xs-9 col-lg-6 col-md-9 col-sm-12 col-lg-push-1">
            <input type="text" name="text" aria-controls="editable-sample" class="input-seaching form-control search_product" value="<?php echo $this->params['search_name'] ?>">
        </label>
        <div class="col-lg-3 col-sm-12 col-md-12 col-xs-3 col-lg-push-1">
            <button type="button" class="form-control btn btn-white btn-searchProduct"><i class="icon-search"></i> Tìm kiếm</button>
        </div>
    </div>
</div>
<br>
<div class="row">
    <div class="col-lg-12">
        <div class="searchproduct">
            <table class="table table-striped table-bordered" cellspacing="0">
                <thead>
                    <tr>
                        <th style="text-align:center;width:25%" class="numeric">Chức năng</th>
                        <th style="width:75%">Tên sản phẩm</th>
                    </tr>
                </thead>
                <tbody>

                    <?php
                    if ($this->arrProductList) {
                        foreach ($this->arrProductList as $arrProductList) {
                            ?>
                            <tr id="<?php echo $arrProductList['prod_id']; ?>">
                                <td style="text-align: center">
                                    <a class="btn btn-success btn-xs censor btn-addProduct" data-placement="top" data-original-title="Thêm bài viết" data-id="<?php echo $arrProductList['prod_id']; ?>"><i class="icon-arrow-left"></i> Thêm</a>
                                </td>
                                <td>
                                    <?php echo $arrProductList['prod_name']; ?>
                                </td>
                            </tr>
                            <?php
                        }
                    } else {
                        ?>
                        <tr class="none-product">
                            <td colspan="2" style="text-align:center;">Hiện tại chưa có sản phẩm nào.</td>
                        </tr>
                    <?php } ?>

                </tbody>
            </table>
            <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12" >
                <?php echo $this->paging; ?>
            </div>
        </div>
    </div>
</div>
</section>