<section id="unseenTags">
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="col-lg-2 col-md-3 col-sm-12 ">
            <a class="btn btn-primary btn-updateProductTags" data-placement="top" data-original-title="Cập nhật" ><i class="icon-refresh"></i> Làm mới</a>
        </div>
        <label class="col-xs-9 col-lg-6 col-md-9 col-sm-12 col-lg-push-1">
            <input type="text" name="text" aria-controls="editable-sample" class="input-seaching form-control search_producttags" value="<?php echo $this->params['search_name'] ?>">
        </label>
        <div class="col-lg-3 col-sm-12 col-md-12 col-xs-3 col-lg-push-1">
            <button type="button" class="form-control btn btn-white btn-searchProductTags"><i class="icon-search"></i> Tìm kiếm</button>
        </div>
    </div>
</div>
<br>
<div class="row">
    <div class="col-lg-12">
        <div class="searchproducttags">
            <table class="table table-striped table-bordered" cellspacing="0">
                <thead>
                    <tr>
                        <th style="width:75%">Tên sản phẩm</th>
                        <th class="text-center">Độ ưu tiên</th>
                        <th style="text-align:center;width:25%" class="numeric">Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if ($this->arrProductTagsList) {
                        foreach ($this->arrProductTagsList as $arrProductTagsList) {
                            ?>
                            <tr id="<?php echo $arrProductTagsList['prod_id']; ?>">
                                <td>
                                    <?php echo $arrProductTagsList['prod_name']; ?>
                                </td>
                                <td class="text-center">
                                    <input style="text-align: center" size="2" class="data-ord" type="text" data-id ="<?php echo $arrProductTagsList['prod_id']; ?>" name="ord[<?php echo $arrProductTagsList['prod_id']; ?>]" value="<?php echo (!empty($arrProductTagsList['sort_ordering']) ? $arrProductTagsList['sort_ordering'] : 0 ) ?>">
                                </td>
                                <td style="text-align: center">
                                    <input type="hidden" name="tags_id" value="<?php echo $this->params['tags_id'] ?>">
                                    <a class="btn btn-danger btn-xs btn-deleteProductTags" data-placement="top" data-original-title="Loại bỏ bài viết" data-id="<?php echo $arrProductTagsList['prod_id']; ?>">Loại bỏ <i class="icon-arrow-right"></i></a>
                                </td>
                            </tr>
                            <?php
                        }
                    } else {
                        ?>
                        <tr class="none-producttags">
                            <td colspan="3" style="text-align:center;">Hiện tại chưa có sản phẩm nào.</td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
            <a style="float: right;margin: 0px 100px 15px auto" class="btn btn-success icon-sort-by-order-alt bt-update-ord" href="javascript:;" >Cập nhật</a>
            <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12" >
                <?php echo $this->paging; ?>
            </div>
        </div>
    </div>
</div>
</section>
<script type="text/javascript">
    Tags.ord();
</script>
