<div id="info_order">
    <div class="line-head">
        <label>Thông tin khách hàng</label>           
    </div>
    <div class="error">
        <span class="error-display error-rgServer"></span>
    </div>
    <div class="register-frame">
        <div class="ui-formRow ">
            <label class="label">Họ tên khách hàng <span class="required">*</span></label>                            
            <div class="collection">
                <input id="login-popup-email" class="user_fullname"><br>
                <span class="error-display error-user_fullname"></span>
            </div>
        </div>

        <div class="ui-formRow ">
            <label class="label">E-Mail <span class="required"></span></label>                            
            <div class="collection">
                <input id="login-popup-email" class="user_email"><br>
                <span class="error-display error-user_email"></span>
            </div>
        </div> 
        
        <div class="ui-formRow ">
            <label class="label">Số điện thoại <span class="required">*</span></label>                            
            <div class="collection">
                <input type="text" id="login-popup-email" class="user_phone"><br>
                <span class="error-display error-user_phone"></span>

            </div>
        </div>
        
        <div class="ui-formRow">
            <label class="label">Địa chỉ <span class="required">*</span></label>                            
            <div class="collection">
                <textarea class="user_address" ></textarea>
                <br/>
                <span class="error-display error-user_address"></span>
            </div>
        </div>
        
        <div class="ui-formRow ">
            <label class="label"><b>Số lượng</b><span class="required">*</span></label>                            
            <div class="collection">
                <input type="text" id="login-popup-email" class="quantityPro" />
                <div style=" width: 248px">
                    <span class="error-display error-quantityPro"></span>
                </div>
            </div>
        </div>

        <div class="ui-formRow ui-submmit-field">
            <center><div class="img-register"></div></center>
            <div class="button-login">
                <button type="submit" class="ui-button btnInfoOrder"><span>Xác nhận</span></button>
            </div>
        </div> 
    </div>              
</div>