<?php
    $arrOrder = $this->arrOrder;
    $arrOrderDetail = $this->arrOrderDetail;
    $arrOrderInfo = json_decode($arrOrder['orde_detail'],true);
?>
<html>
    <head>
        <style>
            * html .clearfixslide-vnt {height: 1%; /* IE5-6 */}
            .clearfix {display: inline-block; /* IE7xhtml*/}
            html[xmlns] .clearfix { display: block; /* O */}
            .clearfix:after { clear: both;content: ".";display: block; height: 0;isibility: hidden; visibility: hidden;line-height: 0;font-size: 1px;overflow: hidden;}
            .page-order{overflow: hidden; margin: 0 auto; width: 785px; border: 1px solid #454545; font-size: 14px;}
            .page-order .text-center{text-align: center;}
            .page-order table {border-spacing: 0;border-collapse: collapse; display: table;}
            .page-order .header{margin: 10px 20px; line-height: 20px;}
            .page-order .header table{width: 100%;}
            .page-order .title{text-align: center; font-size: 20px; font-weight: bold;}
            .page-order .info-customer{width: 100%;padding-top: 20px; margin: 0px 25px; line-height: 25px;}
            .page-order .info-customer table tr td{padding-left:  50px;}
            .page-order .info-customer table tr td:first-child{padding-left:  0px;}
            .page-order .info{width: 95%;padding-top: 20px;}
            .page-order .info .table {width: 95%;max-width: 95%; margin: 0 auto; }
            .page-order .info .table-bordered td{border: 1px solid #454545; line-height: 25px;}
            .page-order .info .table-bordered tr:first-child{text-align: center; font-weight: bold;}
            .page-order .info .table-bordered tr{text-align: center;}
            .page-order .price{padding-top: 10px;margin: 0px 25px; line-height: 25px;}

            body{ font-size: 12px; line-height: 15px;}
            .page-order .header{margin: 10px 20px; line-height: 15px;}
            .page-order .header table{width: 100%;}
            .page-order .title{text-align: center; font-size: 15px; font-weight: bold;}
            .page-order .info-customer{width: 100%; margin: 0px 25px; line-height: 15px;padding-top: 10px;}
            .page-order .info-customer table tr td{padding-left:  50px;width:50%;}
            .page-order .info-customer table tr td:first-child{padding-left:  0px;}

            .page-order .logo{height: 60%;}
            .page-order .info .table {width: 95%;max-width: 95%; margin: 0 auto; }
            .page-order .info .table-bordered td{border: 1px solid #454545; line-height: 15px;}
            .page-order table {border-collapse: collapse;}
            .page-order .info .table-bordered tr:first-child{text-align: center; font-weight: bold;}
            .page-order .text-center{text-align: center;}
            .page-order .info{width: 95%;padding-top: 10px;}
            .page-order .price{margin: 0px 25px;padding-top: 10px;line-height: 15px;}

            /* Clearfix */
            * html .clearfixslide-vnt {height: 1%; /* IE5-6 */}
            .clearfix {display: inline-block; /* IE7xhtml*/}
            html[xmlns] .clearfix {display: block; /* O */}
            .clearfix:after {clear: both;content: ".";display: block; height: 0;visibility: hidden;line-height: 0;font-size: 1px;overflow: hidden;}
            .page-info{ margin: 0 auto; overflow: hidden; font-size: 15px; line-height: 20px;}
            .page-info .main{ width:  539px; height: 298px;  border: 1px solid #454545;}
            .page-info .main .block-1{border: 2px solid #454545;margin:5px 5px;}
            .page-info .main .block-1 .block-2{border: 1px solid #454545;margin:5px 5px;}
            .page-info .main .block-1 .block-2 table{margin: 15px 20px;}
            .page-info .main .block-1 .block-2 .text-center{text-align: center;}
            .page-info .main .block-1 .block-2 .title{font-size: 19px; text-align: center;}
            .page-info .main .block-1 .block-2 table tr td .logo {width: 50%; height: 75%; margin-left: 98px; }


            body{font-size: 12px;line-height: 15px;}
            .page-info{  overflow: hidden; font-size: 18px; line-height: 30px;}
            .page-info .main{ width:  550px; height: 380px;  border: 1px solid #454545; margin:0 auto; }
            .page-info .main .block-1{border: 2px solid #454545;margin:5px 5px;}
            .page-info .main .block-1 .block-2{border: 1px solid #454545;margin:5px 5px;}
            .page-info .main .block-1 .block-2 table{margin: 15px 20px;}
            .page-info .main .block-1 .block-2 .text-center{text-align: center;}
            .page-info .main .block-1 .block-2 .title{font-size: 15px; text-align: center;}
            .page-info .main .block-1 .block-2 table tr td .logo {width: 50%; height: 75%; margin-left: 98px; }
        </style>
    <head>
    <body>
        <div class="page-order" style="min-height: 600px">
            <div class="header">
                <table>
                    <tbody>
                        <tr>
                            <td style="width: 70%" ><img src="http://static.megavita.vn/f/v1/images/logo-email.png" title="Megavita"></td>
                            <td style="width: 30%" >
                                <span><strong>Mã số thuế:</strong></span>
                                <span> 0312654255-001</span>
                            </td>
                        </tr>
                        <tr>
                            <td><strong>Địa chỉ:</strong> 61C Tú Xương, Phường 7, Quận 3, TP.HCM </td>
                            <td><strong>Người làm đơn:</strong> ........................</td>
                        </tr>
                        <tr>
                            <td><strong>Điện thoại:</strong> <?php echo HOTLINE_NUMBER;?></td>
                            <td><strong>Ngày lập:</strong> <?php echo date('d/m/Y',$arrOrder['orde_created'])?></td>
                        </tr>
                        <tr>
                            <td><strong>Website:</strong> megavita.vn</td>
                            <td>&nbsp;</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="title">ĐƠN ĐẶT HÀNG</div>
            <div class="info-customer">
                <table>
                    <tr>
                        <td>Tên khách hàng: <span style="text-transform: capitalize;"><?php echo ($arrOrderInfo['fullname']);?></span></td>
                        <td>Ghi chú: ............................................................... </td>
                    </tr>
                    <tr>
                        <td>Địa chỉ:  <?php echo $arrOrderInfo['address']?> </td>
                        <td>Nhân viên bán hàng: ............................................</td>
                    </tr>
                    <tr>
                        <td>Số điện thoại: <?php echo $arrOrderInfo['phone']?> </td>
                    </tr>
                    <tr>
                        <td></td>
                    </tr>
                </table>
            </div>
            <div class="info">
                <table class="table table-bordered">
                    <tr>
                        <td style="width: 5%">STT</td>
                        <td style="width: 10%">MSP</td>
                        <td style="width: 40%">Tên sản phẩm</td>
                        <td style="width: 5%">Số lượng</td>
                        <td style="width: 10%">Đơn giá</td>
                        <td style="width: 10%">Chiết khấu</td>
                        <td style="width: 10%">Thành tiền</td>
                    </tr>
                    <?php foreach($arrOrderDetail as $key => $value):?>
                    <tr>
                        <td> <?php echo $key+1;?></td>
                        <td> 
                            <?php 
                                echo My\General::PREFIX_IN .sprintf("%03d", $this->arrListProducts[$value['prod_id']]['prod_code']);
                            ?>
                        </td>
                        <td> <?php echo $value['prod_name'];?></td>
                        <td> <?php echo $value['prod_quantity'];?></td>
                        <td> <?php echo number_format($value['prod_price']);?></td>
                        <td> <?php echo $value['discount'];?>%</td>
                        <td> <?php echo number_format($value['total_price']);?></td>
                    </tr>
                    <?php endforeach;?>
                </table>
            </div>
            <div class="price">
                <table>
                    <tr>
                        <td>
                            <span>Tổng tiền: <?php echo number_format($arrOrder['orde_total_price']);?> VNĐ. </span>
                            <span>Bằng chữ: ...................................................................................</span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span>Đã thu : .......................... VNĐ. </span>
                            <span>Bằng chữ: .............................................................................</span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span>Còn lại : .......................... VNĐ. </span>
                            <span>Bằng chữ: .............................................................................</span>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </body>
</html>