<section class="panel">
                  <header class="panel-heading">
                      Image Galley
                  </header>
                  <div class="panel-body">
                      <div>Version PC</div>
                      <ul class="grid cs-style-5">
                         
                          <li >
                              <figure>
                                  <img src="<?php echo STATIC_URL ?>/b/images/template/2.png" alt="Template 2">
                                  <figcaption>
                                      <h3>Template 2</h3>
                                      <span>tawseef tasi</span>
                                      <form action="" method="POST">
                                          <input type="hidden" value="2" name="template">
                                          <button class="fancybox btn btn-success" rel="group" type="submit">Chọn</button>
                                      </form>
                                  </figcaption>
                              </figure>
                          </li>
                          <li>
                              <figure>
                                  <img src="<?php echo STATIC_URL ?>/b/images/template/3.png" alt="Template 3">
                                  <figcaption>
                                      <h3>Modern</h3>
                                      <span>dkmosa inc</span>
                                     <form action="" method="POST">
                                          <input type="hidden" value="3" name="template">
                                          <button class="fancybox btn btn-success" rel="group" type="submit">Chọn</button>
                                      </form>
                                  </figcaption>
                              </figure>
                          </li>
                          <li>
                              <figure>
                                  <img src="<?php echo STATIC_URL ?>/b/images/template/4.png" alt="Template 4">
                                  <figcaption>
                                      <h3>Clean Code</h3>
                                      <span>nice concept</span>
                                      <form action="" method="POST">
                                          <input type="hidden" value="4" name="template">
                                          <button class="fancybox btn btn-success" rel="group" type="submit">Chọn</button>
                                      </form>
                                  </figcaption>
                              </figure>
                          </li>
                          
                      </ul>
                      <div>Version mobile</div>
                      <ul class="grid cs-style-5">
                      <li>
                              <figure>
                                  <img src="<?php echo STATIC_URL;?>/f/mobile/images/banner.png" alt="Template 5">
                                  <figcaption>
                                      <h3>Banner</h3>
                                      <span>sumon ahmed</span>
                                     <form action="" method="POST">
                                          <input type="hidden" value="5" name="template">
                                          <button class="fancybox btn btn-success" rel="group" type="submit">Chọn</button>
                                      </form>
                                  </figcaption>
                              </figure>
                          </li>
                           <li>
                              <figure>
                                  <img src="<?php echo STATIC_URL ?>/b/images/template/5.png" alt="Template 5">
                                  <figcaption>
                                      <h3>Top sản phẩm người dùng lựa chọn</h3>
                                      <span>sumon ahmed</span>
                                     <form action="" method="POST">
                                          <input type="hidden" value="6" name="template">
                                          <button class="fancybox btn btn-success" rel="group" type="submit">Chọn</button>
                                      </form>
                                  </figcaption>
                              </figure>
                          </li>
                      </ul>
                  </div>
              </section>