<?php
$template = $this->template;
echo $this->render('backend/template_' . $template['template']);
?>
<div id="form_calorin" style="display: none">
   <img src="<?php echo STATIC_URL ?>/b/images/template/box-canngu.jpg" alt="Template 4">
</div>
<div id="health" style="display: none">
    <img  src="<?php echo STATIC_URL ?>/b/images/template/box-canngu.jpg" alt="Template 5">
</div>
<div id="image_banner" style="display: none">
    <img  src="<?php echo STATIC_URL ?>/b/images/template/images-5.png" alt="Template 6">
</div>