<?php
$arrProdList = $this->arrProdList;
$param = $this->params;
?>
<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-content')->getMessages(), $this->flashMessenger()->setNamespace('success-edit-content')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">Danh sách sản phẩm cần mua</header>
                <div class="panel-body">
<!--                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-4">                  
                            <div id="editable-sample_length" class="dataTables_length no-padding">
                                <a class="btn btn-primary" href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'content', 'action' => 'add')); ?>" ><i class="icon-plus-sign-alt"></i> Thêm</a>
                                <a class="btn btn-danger delete-all" href="javascript:;" ><i class="icon-trash "></i> Xóa</a>
                            </div>
                        </div>
                    </div>-->
                    <div class="row">
                        <div class="col-lg-8">
                            <form id="frm" class="form-horizontal" role="form" method="GET">
                                <div class="col-xs-6 col-lg-6 col-md-4 col-sm-7 no-padding">
                                    <div class="dataTables_filter no-padding per-100">
                                        <label><input  name="s"  value="<?php echo $this->params["s"]; ?>" type="text" aria-controls="editable-sample" class="per-100 input-seaching form-control medium"></label>
                                    </div>
                                </div>
                                <div class="col-xs-4 col-lg-3 col-md-2 col-sm-3 no-padding-right">
                                    <button type="submit"  class="btn btn-white per-100" ><i class="icon-search"></i> Tìm kiếm</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <section id="unseen">
                        <table class="table table-bordered table-striped table-condensed cf">
                            <thead class="cf">
                                <tr>
                                    <th class="numeric text-center">Mã sản phẩm</th>
                                    <th class="numeric text-center hidden-md hidden-sm hidden-xs">Tên sản phẩm</th>
                                    <th class="numeric text-center hidden-md hidden-sm hidden-xs">Số lượng</th>
                                    <th class="numeric text-center visible-xs visible-sm visible-md visible-lg">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if ($this->arrProdList):
                                    foreach ($this->arrProdList as $Prod):
                                        ?>
                                        <tr id="<?php echo $Prod['prod_id']; ?>">
                                            <td class="text-center"> <?php echo $Prod['prod_id'];  ?></td>
                                            <td class="text-left"><a href="<?php ?>"><?php echo $Prod['prod_name']; ?></a></td>
                                            <td class="text-center"> <?php echo $Prod['prod_quantity'];  ?></td>
                                            <td class="numeric text-center visible-xs visible-sm visible-md visible-lg" width="200">  
                                                <a href="#linkBuy" class="btn btn-primary btn-xs link-buy" rel="<?php echo $Prod['prod_id']; ?>"><i class="icon-eye-open"></i> Xem link</a>
                                                <a href="#bought" class="btn btn-warning btn-xs edit bought" rel="<?php echo $Prod['prod_id']; ?>"><i class="icon-pencil"></i> Đã mua</a>
                                                <!--<a class="btn btn-danger btn-xs remove-conten" data-id="<?php echo $arrContentList['cont_id'] ?>"><i class="icon-trash "></i> Xóa</a>-->
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr><td colspan="8"><center>Hiện tại chưa có dữ liệu.</center></td></tr>
                            <?php endif ?>
                            </tbody>
                        </table>
                    </section>
                    <div>
                        <div class="row">
                            <div class = "col-lg-6">
                                <?php echo $this->paging;
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    BuyProduct.index();
</script>