<?php
$arrProdList = $this->arrProdList;
$param = $this->params;
$arrDetalBuyProd = $this->arrDetalBuyProd;
?>
<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-content')->getMessages(), $this->flashMessenger()->setNamespace('success-edit-content')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">Danh sách sản phẩm</header>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">                  
                        </div>
                        <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
                            <form id="frm" class="form-horizontal" role="form" method="GET">
                                <div class="col-xs-9 no-padding">
                                    <div class="dataTables_filter no-padding per-100">
                                        <label><input  name="s"  value="<?php echo $this->params["s"]; ?>" type="text" aria-controls="editable-sample" class="per-100 input-seaching form-control medium"></label>
                                    </div>
                                </div>
                                <div class="col-xs-3 no-padding-right">
                                    <button type="submit" class="btn btn-white per-100" ><i class="icon-search"></i> Tìm kiếm</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <section id="unseen">
                        <table class="table table-bordered table-striped table-condensed cf">
                            <thead class="cf">
                                <tr>
                                    <th class="numeric text-center">Mã sản phẩm</th>
                                    <th class="numeric text-center">Tên sản phẩm</th>
                                    <th class="numeric text-center">Ngày mua cuối cùng</th>
                                    <th class="numeric text-center">Số lượng mua cuối cùng</th>
<!--                                    <th class="numeric text-center">Lịch sử mua</th>-->
                                    <th class="numeric text-center">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if ($this->arrProdList):
                                    foreach ($this->arrProdList as $Prod):
                                        ?>
                                        <tr id="<?php echo $Prod['prod_id']; ?>">
                                            <td class="text-center"><?php echo $Prod['prod_code']; ?></td>
                                            <td class="text-left"><a target="_bank" href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $Prod['prod_slug'], 'productId' => $Prod['prod_id'])); ?>"><?php echo $Prod['prod_name']; ?></a></td>
                                            <td class="text-center">
                                                <?php
                                                $prod_id = $Prod['prod_id'];
                                                if(!empty($arrDetalBuyProd[$prod_id]['buy_last_time'])){
                                                    echo date('d/m/Y',$arrDetalBuyProd[$prod_id]['buy_last_time']);
                                                }
                                                ?>
                                            </td>
                                            <td class="text-center">
                                                <?php
                                                $prod_id = $Prod['prod_id'];
                                                if(isset($arrDetalBuyProd[$prod_id])){
                                                    echo $arrDetalBuyProd[$prod_id]['buy_last_quantity'];
                                                }
                                                ?>
                                            </td>
<!--                                            <td class="text-center">
                                                <a href="#logs" class="btn btn-primary btn-xs view-logs" rel="<?php echo $Prod['prod_id']; ?>"></i> Xem lịch sử</a>
                                            </td>-->
                                            <td class="numeric text-center visible-xs visible-sm visible-md visible-lg" width="200">  
                                                <a href="#linkProduct" class="btn btn-primary btn-xs view-link" rel="<?php echo $Prod['prod_id']; ?>"><i class="icon-pencil"></i> Sửa link</a>
                                                <a href="#send" data-id="<?php echo $Prod['prod_id']; ?>" class="btn btn-warning btn-xs edit send-prod" rel="<?php echo $Prod['prod_id']; ?>"><i class=" icon-envelope-alt"></i> Gửi mail</a>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr><td colspan="8"><center>Hiện tại chưa có sản phẩm nào.</center></td></tr>
                            <?php endif ?>
                            </tbody>
                        </table>
                    </section>
                    <div>
                        <div class="row">
                            <div  class="col-lg-6">
                                <div class="form-group">
                                    <div  class="col-sm-3 col-xs-3">
                                        <select name="limit" class="form-control" onchange="window.location.href = this.value">
                                            <option value="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'buyProduct', 'action' => 'index', 'limit' => 15, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 15 ? "selected" : "" ?>>15</option>
                                            <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'buyProduct', 'action' => 'index', 'limit' => 30, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 30 ? "selected" : "" ?>>30</option>
                                            <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'buyProduct', 'action' => 'index', 'limit' => 100, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 100 ? "selected" : "" ?>>100</option>
                                            <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'buyProduct', 'action' => 'index', 'limit' => 300, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 300 ? "selected" : "" ?>>300</option>
                                            <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'buyProduct', 'action' => 'index', 'limit' => 500, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 500 ? "selected" : "" ?>>500</option>
                                            <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'buyProduct', 'action' => 'index', 'limit' => 1000, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 1000 ? "selected" : "" ?>>1000</option>
                                        </select>
                                    </div>
                                    <div class = "col-sm-3" style = "padding-top: 10px">Dòng</div>
                                </div>
                            </div>
                            <div class = "col-lg-6">
                                <?php echo $this->paging;
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    BuyProduct.index();
</script>