<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-content')->getMessages(), $this->flashMessenger()->setNamespace('success-edit-content')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">Lịch sử mua hàng</header>
                <div class="panel-body">
                    <div class="row">
                        <form id="frm" class="form-horizontal" role="form" method="GET">
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">   
                                <div data-date-format="dd/mm/yyyy" data-date="" class="input-group input-large">
                                    <input type="text" name="date_from" class="form-control dpd1" placeholder="Từ ngày" value="<?php echo empty($this->params['date_from']) ? date('d/m/Y', (time() - (60 * 60 * 24 * 30))) : $this->params['date_from']; ?>">
                                    <span class="input-group-addon">Đến</span>
                                    <input type="text" name="date_to" class="form-control dpd2" placeholder="Đến ngày" value="<?php echo empty($this->params['date_to']) ? date('d/m/Y', time()) : $this->params['date_to']; ?>">
                                </div>
                            </div>
                            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
                                    <div class="col-xs-3 no-padding-right">
                                    </div>
                                    <div class="col-xs-6 no-padding">
                                        <div class="dataTables_filter no-padding per-100">
                                            <label><input  name="s"  value="<?php echo $this->params["s"]; ?>" type="text" aria-controls="editable-sample" class="per-100 input-seaching form-control medium"></label>
                                        </div>
                                    </div>
                                    <div class="col-xs-3 no-padding-right">
                                        <button type="submit" class="btn btn-white per-100" ><i class="icon-search"></i> Tìm kiếm</button>
                                    </div>
                            </div>
                        </form>
                    </div>
                    <section id="unseen">
                        <table class="table table-bordered table-striped table-condensed cf">
                            <thead class="cf">
                                <tr>
                                    <th class="numeric text-center">Mã SP</th>
                                    <th class="numeric text-center">Tên sản phẩm</th>
                                    <th class="numeric text-center">Số lượng</th>
                                    <th class="numeric text-center">Ngày</th>
                                    <th class="numeric text-center">Link</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                    //p($this->arrListBuyLog);die();
                                if($this->arrListBuyLog){
                                    foreach($this->arrListBuyLog as $value){ ?>
                                        <tr>
                                            <td class="numeric text-center"><?php echo $value['prod_code'] ?></td>
                                            <td class="numeric text-left"><?php echo $value['prod_name'] ?></td>
                                            <td class="numeric text-center"><?php echo $value['buy_quantity'] ?></td>
                                            <td class="numeric text-center"><?php echo date('d/m/Y',$value['buy_time']) ?></td>
                                            <td class="numeric text-center"><a href="<?php echo $value['buy_link'] ?>">Link mua</a></td
                                        </tr>
                                <?php        
                                    }
                                }
                                ?>
                            </tbody>
                        </table>
                    </section>
                     <div>
                        <div class="row">
                            <div  class="col-lg-6">
                            </div>
                            <div class = "col-lg-6">
                                <?php echo $this->paging;
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    BuyProduct.index();
</script>