<header class="header white-bg">
    <div class="sidebar-toggle-box" style="font-size:20px;margin-top:16px;cursor:pointer;">
        <div id="leftMenuToggle" data-original-title="Ẩn / hiện danh mục" data-placement="right" class="icon-reorder tooltips"></div>
    </div>
    <a href="<?php echo $this->serverUrl() . $this->Url('backend', array()); ?>" class="logo" >megavita.<span>vn</span></a>
    <div class="top-nav ">
        <ul class="nav pull-right top-menu">
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <i class="icon-user" style="font-size:18px;color: #5cb85c;"></i>
                    <span class="username">Xin chào <?php
                        $arrName = explode(' ', FULLNAME);
                        echo end($arrName);
                        ?></span>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu extended logout">
                    <div class="log-arrow-up"></div>
                    <li><a href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'profile','action' => 'index')); ?>"><i class="icon-suitcase"></i>Cá nhân</a></li>
                    <li><a href="#"><i class="icon-cog"></i> Cài đặt</a></li>
                    <li><a href="#"><i class="icon-bell-alt"></i> Tin nhắn</a></li>
                    <li><a href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'auth', 'action' => 'logout')); ?>"><i class="icon-key"></i> Đăng xuất</a></li>
                </ul>
            </li>
        </ul>
    </div>
</header>