<?php
$strTemplate = current($this->layout()->getChildren())->getTemplate();
//p($para)
?>
<!DOCTYPE html>
<html>
    <head>
        <?php echo $this->headTitle(); ?>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="content-language" content="vi" />
        <!--<meta name="robots" content="INDEX, FOLLOW" />-->
        <meta http-equiv="Expires" content="0" />
        <meta name='revisit-after' content='1 days' />
        <meta http-equiv="REFRESH" content="1200" />
        <meta property="article:author" content="https://www.facebook.com/megavita.vn" />
        <script type="text/javascript">
            var baseurl = '<?php echo $this->serverUrl(); ?>';
            var registerURL = '<?php echo $this->serverUrl() . $this->Url('auth', array('controller' => 'auth', 'action' => 'signup')); ?>';
            var loginURL = '<?php echo $this->serverUrl() . $this->Url('auth', array('controller' => 'auth', 'action' => 'login')); ?>';
            var resetPassURL = '<?php echo $this->serverUrl() . $this->Url('auth', array('controller' => 'auth', 'action' => 'reset-password')); ?>';
            var module = '<?php echo MODULE; ?>';
            var staticurl = '<?php echo STATIC_URL; ?>';
            var fullname = '<?php echo FULLNAME; ?>';
            var role = '<?php echo USER_ROLE; ?>';
            var url_rate_product = '<?php echo $this->serverUrl() . $this->Url('product_rate', array('controller' => 'product', 'rate' => 'rate')); ?>';
            var addcartURL = '<?php echo $this->serverUrl() . $this->Url('frontend-order', array('controller' => 'order', 'action' => 'add-product-cart')); ?>';
            var showcartURL = '<?php echo $this->serverUrl() . $this->Url('frontend-order', array('controller' => 'order', 'action' => 'show-cart')); ?>';
            var updatecartURL = '<?php echo $this->serverUrl() . $this->Url('frontend-order', array('controller' => 'order', 'action' => 'update-cart')); ?>';
            var removeproductcartURL = '<?php echo $this->serverUrl() . $this->Url('frontend-order', array('controller' => 'order', 'action' => 'remove-product-cart')); ?>';
            var captchaURL = '<?php echo $this->serverUrl() . $this->Url('captcha', array('controller' => 'captcha', 'action' => 'index')); ?>';
            var profileUrl = '<?php echo $this->serverUrl() . $this->Url('profile', array('controller' => 'profile', 'action' => 'index')); ?>';
            var profile_changecitytUrl = '<?php echo $this->serverUrl() . $this->Url('profile', array('controller' => 'profile', 'action' => 'changecity')); ?>';
            var autocompleteUrl = '<?php echo $this->serverUrl() . $this->Url('frontend', array('controller' => 'index', 'action' => 'autocomplete')); ?>'
            var searchUrl = '<?php echo $this->serverUrl() . $this->Url('frontend-search', array('controller' => 'search', 'action' => 'index')); ?>';
            var categoryUrl = '<?php echo $this->serverUrl() . $this->Url('category', array('controller' => 'product', 'action' => 'index')); ?>';
            var changeAvatarUrl = '<?php echo $this->serverUrl() . $this->Url('profile', array('controller' => 'profile', 'action' => 'changeavatar')); ?>';
//            var searchajaxUrl = '<?php // echo $this->serverUrl() . $this->Url('search', array('controller' => 'search', 'action' => 'get-ajax'));  ?>';
            var cateajaxUrl = '<?php echo $this->serverUrl() . $this->Url('cate', array('controller' => 'category', 'action' => 'menuajax')); ?>';
            var mainmenuURL = '<?php echo $this->serverUrl() . $this->Url('menu', array('controller' => 'menu', 'action' => 'load-menu')); ?>';
        </script>        
        <?php
        echo $this->headMeta();
        echo $this->headLink();
        echo $this->headScript();
        ?>
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-63222712-1', 'auto');
            ga('send', 'pageview');

        </script>
        <script type="application/ld+json">
            {
            "@context": "http://schema.org",
            "@type": "Organization",
            "url": "<?php echo $this->serverUrl(); ?>",
            "logo": "<?php echo STATIC_URL; ?>/f/v1/images/logo-email.png"
            }
        </script>
    </head>

    <body id="home" class="spring-option <?php echo (CONTROLLER == "index") ? "" : "insider"; ?>">
        <div id="wrap">
            <?php
            echo $this->render('frontend/topbar');
            echo $this->layout()->content;
            echo $this->render('frontend/footer');
            echo $this->render('frontend/form');
            ?>
        </div>
    </body>
    <script>
        Cart.index();
        Account.index();
        Topbar.index();
        AutoComplete.index();
    </script>
</html>