<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-times-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = $this->flashMessenger()->setNamespace('success-add-provider')->getMessages();
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>

    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <div class="row">
                    <div class="col-lg-12">
                        <section class="panel">
                            <header class="panel-heading">Sửa nhà cung cấp</header>
                            <div class="panel-body">
                                <form method="POST" role="form" class="form-horizontal tasi-form" id="frm" novalidate="novalidate">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="provider-code" class="col-lg-2 control-label" value="">Mã NCC</label>
                                            <div class="col-lg-10">
                                                <input type="text" value="<?php echo!empty($this->params["code"]) ? $this->params["code"] : $this->arrDetailProvider["prov_code"] ?>" placeholder="Nhập mã nhà cung cấp" class="form-control" name="code" id="code-provider">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="provider-name" class="col-lg-2 control-label" value="">Tên</label>
                                            <div class="col-lg-10">
                                                <input type="text" value="<?php echo!empty($this->params["name"]) ? $this->params["name"] : $this->arrDetailProvider["prov_name"] ?>" placeholder="Nhập tên nhà cung cấp" class="form-control" name="name" id="name-provider">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="provider-phone" class="col-lg-2 control-label" value="">Phone</label>
                                            <div class="col-lg-10">
                                                <input type="text" value="<?php echo!empty($this->params["phone"]) ? $this->params["phone"] : $this->arrDetailProvider["prov_phone"] ?>" placeholder="Nhập số điện thoại nhà cung cấp" class="form-control" name="phone" id="phone-provider">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="provider-address" class="col-lg-2 control-label" value="">Đia chỉ</label>
                                            <div class="col-lg-10">
                                                <input type="text" value="<?php echo!empty($this->params["address"]) ? $this->params["address"] : $this->arrDetailProvider["prov_address"] ?>" placeholder="Nhập địa chỉ nhà cung cấp" class="form-control" name="address" id="address-provider">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="provider-email" class="col-lg-2 control-label" value="">Email</label>
                                            <div class="col-lg-10">
                                                <input type="text" value="<?php echo!empty($this->params["email"]) ? $this->params["email"] : $this->arrDetailProvider["prov_email"] ?>" placeholder="Nhập email nhà cung cấp" class="form-control" name="email" id="email-provider">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="provider-fax" class="col-lg-2 control-label" value="">Fax</label>
                                            <div class="col-lg-10">
                                                <input type="text" value="<?php echo!empty($this->params["fax"]) ? $this->params["fax"] : $this->arrDetailProvider["prov_fax"] ?>" placeholder="Nhập số fax nhà cung cấp" class="form-control" name="fax" id="fax-provider">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="provider-userbane" class="col-lg-2 control-label" value="">Username</label>
                                            <div class="col-lg-10">
                                                <input readonly="" type="text" value="<?php echo $this->arrDetailProvider["login_name"] ?>" placeholder="Nhập tên đăng nhập cho nhà cung cấp" class="form-control" id="user-provider">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="provider-password" class="col-lg-2 control-label" value="">Password</label>
                                            <div class="col-lg-10">
                                                <input type="password"  placeholder="Nhập mật khẩu nhà cung cấp" class="form-control" name="pass" id="pass-provider">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label  class="col-lg-2 control-label">Tình trạng<span style="color:red">*</span></label>
                                            <div class="col-lg-10">
                                                <select name="status" id="userRole" class="form-control">
                                                    <option value="1" <?php echo (!empty($this->params["status"]) ? $this->params["status"] : $this->arrDetailProvider['prov_status'] == 1) ? 'selected' : ''; ?>>Hoạt động</option>
                                                    <option value="0" <?php echo (!empty($this->params["status"]) ? $this->params["status"] : $this->arrDetailProvider['prov_status'] == 0) ? 'selected' : ''; ?>>Khóa tài khoản</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button type="submit" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                                                <button type="submit" id="done" class="btn btn-success bt-save" name="save_close"><i class="icon-save"></i> Lưu & Thoát</button> 
                                                <input value="0" name="is_close" class="is_close" type="hidden" />
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </section>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    Provider.index();
</script>