<section class="wrapper site-min-height">
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">Danh sách nhà cung cấp</header>
                <div class="panel-body">
                    <div class="row" style="margin-bottom: 10px;">
                        <div class="col-lg-3 col-md-3 col-sm-4">                  
                            <div id="editable-sample_length" class="dataTables_length no-padding">
                                <a class="btn btn-primary" href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'provider', 'action' => 'add')); ?>"><i class="icon-plus-sign-alt"></i> Thêm</a>
                            </div>
                        </div>
                        <form id="frm" class="form-horizontal" role="form" method="GET">
                            <div class="col-lg-6">
                                <div class="dataTables_filter no-padding per-100 ">
                                    <label><input name="s" value="<?php echo $this->params['s'] ?>" type="text" aria-controls="editable-sample" class="per-100 input-seaching form-control medium col-lg-5 floatRight"></label>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="dataTables_filter no-padding per-100 ">
                                    <button type="submit" class="btn btn-white per-100"><i class="icon-search"></i> Tìm kiếm</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <section id="unseen">
                        <table class="table table-bordered table-striped table-condensed cf">
                            <thead class="cf">
                                <tr>
                                    <th class="numeric text-center" width="7%">STT</th>
                                    <th class="numeric text-center">Mã NCC</th>
                                    <th class="numeric text-center" width="10%">Tên NCC</th>
                                    <th class="numeric text-center" width="10%">Điện thoại</th>
                                    <th class="numeric text-center" width="20%">Địa chỉ</th>
                                    <th class="numeric text-center" width="20%">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if($this->arrProvider){
                                    foreach($this->arrProvider as $key => $value){ 
                                        $key ++;
                                ?>
                                        <tr>
                                            <td style="text-align: center"><?php echo $key ?></td>
                                            <td style="text-align: center"><?php echo $value['prov_code'] ?></td>
                                            <td style="text-align: center"><?php echo $value['prov_name'] ?></td>
                                            <td style="text-align: center"><?php echo $value['prov_phone'] ?></td>
                                            <td style="text-align: center"><?php echo $value['prov_address'] ?></td>
                                            <td style="text-align: center">
                                                <a href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'provider', 'action' => 'edit', 'id' => $value['prov_id'])); ?>" data-original-title="Sửa nhà cung cấp" class="btn btn-primary tooltips btn-xs"><i class="icon-edit"></i> Sửa</a>
                                                <a class="btn btn-danger btn-xs remove tooltips" data-placement="top" data-original-title="Xóa nhà cung cấp" rel="<?php echo $value['prov_id'] ?>"><i class="icon-trash "></i> Xóa</a>
                                            </td>
                                        </tr>
                                <?php
                                    }
                                }else{
                                    echo '<tr><td style="text-align: center" colspan="5">Không tìm thấy dữ liệu</td></tr>';
                                }
                                ?>
                            </tbody>
                        </table>
                    </section>
                    <div>
                        <div class="row">
                            <div  class="col-lg-6">
                                &nbsp;
                            </div>
                            <div class = "col-lg-6">
                                <?php echo $this->paging;?>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    Provider.index();
</script>