<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-tagscontent')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>

    <div class="row" id="frmAddCity">
        <div class="col-lg-12">
            <section class="panel">
                <header id="frmTitle" class="panel-heading">Thêm Tags bài viết mới</header>
                <div class="panel-body">
                    <form id="frm" role="form" class="form-horizontal tasi-form" method="POST">
                        <div class="form-group">
                            <label class="col-lg-2 col-sm-2 col-md-2 control-label"> Tên Tags</label>
                            <div class="col-lg-10 col-sm-10 col col-md-10">
                                <input class="form-control" type="text" name="TagsName" placeholder="Nhập tên Tags" value="<?php echo $this->params['TagsName'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tags_cont_slug" class="col-lg-2 col-sm-2 col-md-2   control-label"> URL</label>
                            <div class="col-lg-10 col-sm-10 col col-md-10">
                                <input class="form-control" type="text" name="TagsSlug" placeholder="Nhập tên không dấu" value="<?php echo $this->params['TagsSlug'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 col-sm-2 col-md-2  control-label"> Thuộc Nhóm   </label>
                            <div class="col-lg-10 col-sm-10 col col-md-10">
                                <select name="parentID" class="selectbox selectpicker" data-live-search="true" title="Chọn tag">
                                    <option value="0">Chọn Nhóm</option>
                                    <?php foreach ($this->arrTagsContentList as $key => $arrTagsContentList) { ?>
                                        <option value="<?php echo $arrTagsContentList['tags_cont_id'] ?>" <?php if ($arrTagsContentList['tags_cont_id'] == $this->params['parentID']) { ?> selected <?php } ?>>
                                            <?php
                                            $temp = substr_count($arrTagsContentList['tags_cont_grade'], ':');
                                            if ($temp > 0) {
                                                if ($arrTagsContentList['tags_cont_parent'] != 0) {
                                                    echo str_repeat('&nbsp;&nbsp;&nbsp;', $temp);
                                                    echo '&#x21b3;&nbsp;&nbsp;';
                                                }
                                            }
                                            echo $arrTagsContentList['tags_cont_name'];
                                            ?>
                                        </option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tags_cont_order" class="col-lg-2 col-sm-2 col-md-2  control-label">Độ ưu tiên</label>
                            <div class="col-lg-10 col-sm-10 col col-md-10">
                                <input class="form-control" type="text" name="TagsOrder" placeholder="Nhập Độ ưu tiên" value="<?php echo $this->params['TagsOrder'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tags_cont_status" class="col-lg-2 col-sm-2 col-md-2control-label" value="">Tình trạng</label>
                            <div class="col-lg-10 col-sm-10 col col-md-10">
                                <select name="tags_cont_status" class="multi-select form-control sumo-select-box">
                                    <option value="1">Hiển thị</option>
                                    <option value="0">Ẩn</option>
                                </select>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="tags_cont_position" class="col-lg-2 col-sm-2 col-md-2control-label" value="">Tình trạng</label>
                            <div class="col-lg-10 col-sm-10 col col-md-10">
                                <select name="tags_cont_position" class="multi-select form-control sumo-select-box">
                                    <option value="1">Dưới</option>
                                    <option value="0">Trên</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tags_cont_description" class="col-lg-2 col-sm-2 col-md-2  control-label">Mô tả ngắn về Tags</label>
                            <div class="col-lg-10 col-sm-10 col col-md-10">
                                <textarea rows="6" name="tags_cont_description" id="Sumary" class="form-control editor" style="">
                                    <?php echo $this->params['tags_cont_description']; ?>
                                </textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tags_cont_meta_title" class="col-lg-2 col-sm-2 col-md-2  control-label">SEO Meta Title</label>
                            <div class="col-lg-10 col-sm-10 col col-md-10">
                                <input class="form-control" type="text" name="TagsMetaTitle" placeholder="Nhập SEO Meta Title" value="<?php echo $this->params['TagsMetaTitle'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="Tags_meta_keyword" class="col-lg-2 col-sm-2 col-md-2  control-label">SEO Meta Keyword</label>
                            <div class="col-lg-10 col-sm-10 col col-md-10">
                                <input class="form-control" type="text" name="TagsMetaKeyword" placeholder="Nhập SEO Meta Keyword" value="<?php echo $this->params['TagsMetaKeyword'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="Tags_meta_description" class="col-lg-2 col-sm-2 col-md-2  control-label">SEO Meta Description</label>
                            <div class="col-lg-10 col-sm-10 col col-md-10">
                                <input class="form-control" type="text" name="TagsMetaDescription" placeholder="Nhập SEO Meta Description" value="<?php echo $this->params['TagsMetaDescription'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="Tags_meta_social" class="col-lg-2 col-sm-2 col-md-2  control-label">SEO Meta Social</label>
                            <div class="col-lg-10 col-sm-10 col col-md-10">
                                <input class="form-control" type="text" name="TagsMetaSocial" placeholder="Nhập SEO Meta Social" value="<?php echo $this->params['TagsMetaSocial'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-offset-3 col-lg-10 col-sm-10 col col-md-10">
                                <button type="submit" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                                <button type="submit" id="done" class="btn btn-success bt-save" name="save_close"><i class="icon-save"></i> Lưu & Thoát</button> 
                                <input value="0" name="is_close" class="is_close" type="hidden" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
</section>
<script>
    TagsCont.add();
    TagsCont.submitClose();
</script>