<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <label class="col-xs-9 col-lg-9 col-md-12 col-sm-12">
            <input type="text" value="<?php echo $this->params['s'] ?>" name="text" aria-controls="editable-sample" class="input-seaching form-control search_content">
        </label>
        <div class="col-lg-3 col-sm-12 col-md-12 col-xs-3">
            <button type="button" onclick="loadPage(1,'get-content')" class="form-control btn btn-white btn-searchProduct"><i class="icon-search"></i> Tìm kiếm</button>
        </div>
    </div>
</div>
<br>
<div class="row">
    <div class="col-lg-12">
        <div class="searchcontent">
            <table class="table table-striped table-bordered" cellspacing="0">
                <thead>
                    <tr>
                        <th style="text-align:center;width:25%" class="numeric">Chức năng</th>
                        <th style="width:75%">Tên bài viết</th>
                    </tr>
                </thead>
                <tbody>

                    <?php
                    if ($this->arrContentList) {
                        foreach ($this->arrContentList as $content) {
                            ?>
                            <tr id="<?php echo $content['cont_id']; ?>">
                                <td style="text-align: center">
                                    <a class="btn btn-success btn-xs censor btn-addContent" data-placement="top" data-original-title="Thêm bài viết" data-id="<?php echo $content['cont_id']; ?>"><i class="icon-arrow-left"></i> Thêm</a>
                                </td>
                                <td>
                                    <?php echo $content['cont_title']; ?>
                                </td>
                            </tr>
                            <?php
                        }
                    } else {
                        ?>
                        <tr class="none-content">
                            <td colspan="2" style="text-align:center;">Hiện tại chưa có sản phẩm nào.</td>
                        </tr>
                    <?php } ?>

                </tbody>
            </table>
            <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12" >
                <?php echo $this->paging; ?>
            </div>
        </div>
    </div>
</div>
