<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Upload Images</title>
        <script type="text/javascript" src="<?php echo STATIC_URL; ?>/b/js/library/tinymce/plugins/jbimages/js/dialog-v4.js"></script>
        <link href="<?php echo STATIC_URL; ?>/b/js/library/tinymce/plugins/jbimages/css/dialog-v4.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <form class="form-inline" id="upl" name="upl" action="/backend/uploader/images" method="post" enctype="multipart/form-data" target="upload_target" onsubmit="jbImagesDialog.inProgress();">

            <div id="upload_in_progress" class="upload_infobar"><img src="<?php echo STATIC_URL; ?>/b/js/library/tinymce/plugins/jbimages/img/spinner.gif" width="16" height="16" class="spinner">Upload in progress&hellip; <div id="upload_additional_info"></div></div>
            <div id="upload_infobar" class="upload_infobar"></div>	
            <p id="upload_form_container">
                <input id="uploader" name="upload_file" type="file" class="jbFileBox" onChange="document.upl.submit();
                        jbImagesDialog.inProgress();">
            </p>
            <p id="the_plugin_name"></p>
        </form>
        <iframe id="upload_target" name="upload_target" src="/backend/uploader/images?blank"></iframe>
    </body>
</html>