<section class="wrapper site-min-height">   
    <section class="panel">
        <header class="panel-heading">
            Danh sách Đăng ký
        </header>
        <div class="panel-body">    
            <div class="adv-table editable-table ">  
                <div class="row">
                    <div class="col-lg-4 col-sm-4 col-md-12" col-xs-12>                  
                        <div id="editable-sample_length" class="dataTables_length no-padding">
                            <a class="btn btn-primary" href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'subscribe', 'action' => 'exportExcel')); ?>"><i class="icon-file-text-alt"> </i> Xuất danh sách ra file EXCEL</a>
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                        <form id="frm" class="form-horizontal" role="form" method="GET">
                            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-8 no-padding">
                                <div class="dataTables_filter no-padding per-100">
                                    <label><input  name="s"  value="<?php echo $this->params["s"]; ?>" type="text" aria-controls="editable-sample" class="per-100 input-seaching form-control medium"></label>
                                </div>
                            </div>
                            <div class="col-lg-3 col-sm-3 col-md-3 col-xs-4 no-padding-right">
                                <button type="submit"  class="btn btn-white per-100" ><i class="icon-search"></i> Tìm kiếm</button>
                            </div>
                        </form>
                    </div>
                </div>
                <section id="unseen">
                    <table class="table table-bordered table-striped table-condensed cf">
                        <thead class="cf">
                            <tr>
                                <th ><i class="icon-list"></i> ID</th>
                                <th class="visible-lg visible-md visible-sm visible-xs text-center"><i class="icon-envelope-alt"></i> Email</th>
                                <th class="text-center"><i class="icon-ok"></i> Ngày đăng ký</th>
                                <th class="visible-lg visible-md visible-sm visible-xs text-center"><i class="icon-edit"></i> Chức năng</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if ($this->arrSubscribe):
                                foreach ($this->arrSubscribe as $arrSubscribe):
                                    ?>
                                    <tr>
                                        <td  class="text-center" width="50">
                                            <?php echo $arrSubscribe['subs_id']; ?>
                                        </td>
                                        <td class=" visible-lg visible-md visible-sm visible-xs"><?php echo $arrSubscribe['subs_email']; ?> </td>
                                        <td><?php echo date('d/m/Y',$arrSubscribe['subs_created']); ?> </td>
                                        <td class="text-center visible-lg visible-md visible-sm visible-xs" width="200">
                                            <a  class="btn btn-danger btn-xs remove tooltips" data-placement="top" data-original-title="Xóa người đăng ký này" rel="<?php echo $arrSubscribe['subs_id']; ?>"><i class="icon-trash "></i> Xóa</a>
                                        </td>
                                    </tr>

                                <?php endforeach; ?>
                            <?php else: ?>
                                <tr><td colspan="6" class="text-center">Hiện tại chưa có người đăng ký.</td></tr>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </section>
            </div>
            <div>
                <?php echo $this->paging; ?>
            </div>
        </div>
    </section>
</section>
<script type="text/javascript">
    Subscribe.del();
</script>