<?php

use My\General;

$arrCategoryDetailList = $this->arrCategoryDetailList;
$arrBrandDetailList = $this->arrBrandDetailList;
$param = $this->params;
//p($param);die;
?>
<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-times-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-product')->getMessages(), $this->flashMessenger()->setNamespace('success-edit-product')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">Danh sách Sản phẩm</header>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-2">                  
                            <div id="editable-sample_length" class="dataTables_length no-padding">
                                <a class="btn btn-primary" href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'product', 'action' => 'add')); ?>" ><i class="icon-plus-sign-alt"></i> Thêm</a>
                                <a class="btn btn-danger remove-all" href="javascript:;" ><i class="icon-trash "></i> Xóa</a>
                            </div>
                        </div>
                        <div class="col-lg-10">
                            <form id="frm" class="form-horizontal" role="form" method="GET">
                                <div class="row">
                                    <div class="col-lg-4">
                                        <select id="cate" class="selectbox selectpicker"  multiple="multiple"  data-live-search="true" title="Chọn danh mục">
                                            <?php
                                            if (is_array($param['cate_id'])) {
                                                $listCate = $param['cate_id'];
                                            } else {
                                                $listCate = explode(',', $param['cate_id']);
                                            }
                                            foreach ($arrCategoryDetailList as $category) {
                                                $depth = substr_count($category['cate_grade'], ':') - 1;
                                                $str = $depth > 0 ? str_repeat('&nbsp;&nbsp;&nbsp;', $depth - 1) . '&rdsh;&nbsp;' : '';
                                                ?>
                                                <option <?php echo in_array($category['cate_id'], $listCate) ? 'selected="selected"' : '' ?> value="<?php echo $category['cate_id'] ?>"><?php echo $str . $category['cate_name'] ?></option>
                                            <?php } ?>
                                        </select>
                                        <input type="hidden" name="cate_id" id ="cate_id" value="<?php echo $this->params['cate_id'] ?>">
                                    </div>
                                    <div class="col-lg-4">
                                        <select id="brand" class="selectbox selectpicker"  multiple="multiple"  data-live-search="true" title="Chọn thương hiệu">
                                            <?php
                                            if (is_array($param['brand_id'])) {
                                                $listBrand = $param['brand_id'];
                                            } else {
                                                $listBrand = explode(',', $param['brand_id']);
                                            }
                                            foreach ($arrBrandDetailList as $brand) {
                                                ?>
                                                <option <?php echo in_array($brand['cate_id'], $listBrand) ? 'selected="selected"' : '' ?> value="<?php echo $brand['cate_id'] ?>"><?php echo $brand['cate_name'] ?></option>
                                            <?php } ?>
                                        </select>
                                        <input type="hidden" name="brand_id" id ="brand_id" value="<?php echo $this->params['brand_id'] ?>">
                                    </div>
                                    <div class="col-lg-4">
                                        <select  name="order_sort" class="sumo-select-box">
                                            <option value="">Sắp xếp</option>
                                            <option value="prod_price ASC" <?php if ($param['order_sort'] == 'prod_price ASC'): ?> selected<?php endif; ?>>Giá tăng dần</option>
                                            <option value="prod_price DESC" <?php if ($param['order_sort'] == 'prod_price DESC'): ?> selected<?php endif; ?>>Giá giảm dần</option>
                                            <option value="prod_id DESC" <?php if ($param['order_sort'] == 'prod_id DESC'): ?> selected<?php endif; ?>>Sản phẩm Mới đến cũ</option>
                                            <option value="prod_id ASC" <?php if ($param['order_sort'] == 'prod_id ASC'): ?> selected<?php endif; ?>>Sản phẩm Cũ đến mới</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-9">
                                        <div class="dataTables_filter no-padding per-100 ">
                                            <label><input  name="s"  value="<?php echo $this->params["s"]; ?>" type="text" aria-controls="editable-sample" class="per-100 input-seaching form-control medium col-lg-5 floatRight"></label>
                                        </div>
                                    </div>
                                    <div class="col-lg-3">
                                        <button type="submit"  class="btn btn-white per-100" ><i class="icon-search"></i> Tìm kiếm</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <section id="unseen">
                        <table class="table table-bordered table-striped table-condensed cf">
                            <thead class="cf">
                                <tr>
                                    <th class="numeric text-center">#</th>
                                    <th class="numeric text-center">Tên sản phẩm</th>
                                    <th class="numeric text-center">Danh mục</th>
                                    <th class="numeric text-center">Thương hiệu</th>
                                    <th class="numeric text-center">Mã sản phẩm</th>
                                    <th class="numeric text-center">Giá bán (VNĐ)</th>
                                    <th class="numeric text-center">Ngày tạo</th>
                                    <th class="numeric text-center">Loại hàng</th>
                                    <th class="numeric text-center">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if ($this->arrProductList):
                                    foreach ($this->arrProductList as $arrProductList):
//                                    p($arrProductList);die();
                                        ?>
                                        <tr>
                                            <td class="text-center data-id"><input type="checkbox" name="data-id[]" clas value="<?php echo $arrProductList['prod_id'] ?>"/></td>
                                            <td class="numeric producName"><?php echo $arrProductList['prod_name']; ?></td>
                                            <td class="numeric productCategory" style="  text-transform: lowercase;">
                                                <div class="btn-group">
                                                    <button data-toggle="dropdown" class="btn btn-white dropdown-toggle btn-xs" type="button"><?php echo $arrCategoryDetailList[$arrProductList['main_cate_id']]['cate_name'] ?> <span class="caret"></span></button>
                                                    <ul role="menu" class="dropdown-menu">
                                                        <?php
                                                        $result = explode(',', $arrProductList['cate_id']);
                                                        foreach ($result as $key => $value):
                                                            if (isset($arrCategoryDetailList[$value]['cate_name']) && $arrProductList['main_cate_id'] != $value) :
                                                                echo '<li><a>' . $arrCategoryDetailList[$value]['cate_name'] . '</a></li>';
                                                            endif;
                                                        endforeach;
                                                        ?>
                                                    </ul>
                                                </div>

                                            </td>
                                            <td class="numeric producStatus text-center"><?php echo $arrBrandDetailList[$arrProductList['bran_id']]['cate_name'] ?> </td>
                                            <td class="numeric producStatus text-center"><?php echo General::PREFIX_IN . $arrProductList['prod_code'] ?></td>


                                            <td class="numeric productPrice text-center">
                                                <?php if ($arrProductList['prod_call_price'] == 1) { ?>Giá liên hệ<?php
                                                } else {
                                                    if ($arrProductList['prod_is_promotion'] == 1) {
                                                        echo number_format($arrProductList['prod_promotion_price'], 2, ",", ".");
                                                        ?><br/><small class="text-muted " style="color:#F00;text-decoration: line-through"><?php echo number_format($arrProductList['prod_price'], 2, ",", "."); ?></small> <?php
                                                    } else {
                                                        echo number_format($arrProductList['prod_price'], 2, ",", ".");
                                                    }
                                                }
                                                ?></td>
                                            <td class="numeric productCreated text-center"><?php echo date('d/m/Y', $arrProductList['prod_created']); ?></td>
                                            <td class="numeric productCreated text-center"><?php echo $arrProductList['prod_type']; ?></td>
                                            <td class="numeric text-center" width="190">
                                                <a  href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $arrProductList["prod_slug"], 'productId' => $arrProductList['prod_id'])) ?>" target="_bank"  class="btn btn-primary btn-xs"><i class="icon-eye-open"></i> Xem</a>
                                                <a href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'product', 'action' => 'edit', 'id' => $arrProductList['prod_id'])); ?>" class="btn btn-primary btn-xs edit"><i class="icon-pencil"></i> Sửa</a>
                                                <!--<a class="btn btn-danger btn-xs remove" data-id="<?php echo $arrProductList['prod_id'] ?>"><i class="icon-trash "></i> Xóa</a>--><div style="height:3px;"></div>
                                                <a class="btn btn-primary btn-xs btn-edit" data-id="<?php echo $arrProductList['prod_id']; ?>"><i class="icon-pencil"></i> Sửa nhanh</a>
                                                <a class="btn btn-success btn-xs  check" data-placement="top" style = "display:none"><i class="icon-ok"></i> Cập nhật </a>
                                                <a class="btn btn-danger btn-xs  denied" data-placement="top" style = "display:none"><i class="icon-remove"></i> Bỏ qua</a>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr><td colspan="7" class="text-center">Hiện tại chưa có dữ liệu.</td></tr>
                                <?php endif ?>
                            </tbody>
                        </table>
                    </section>
                    <div>
                        <div class="row">
                            <div  class="col-lg-6">
                                <div class="form-group">
                                    <div  class="col-sm-3">
                                        <select name="limit" class="form-control" onchange="window.location.href = this.value">
                                            <option value="<?php echo $this->serverUrl() . $this->Url('backend-product-search', array('controller' => 'product', 'action' => 'index', 'limit' => 15, 's' => $this->params["s"], 'cate_id' => $this->params["cate_id"], 'brand_id' => $this->params["brand_id"], 'order_sort' => $this->params["order_sort"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 15 ? "selected" : "" ?>>15</option>
                                            <option value ="<?php echo $this->serverUrl() . $this->Url('backend-product-search', array('controller' => 'product', 'action' => 'index', 'limit' => 30, 's' => $this->params["s"], 'cate_id' => $this->params["cate_id"], 'brand_id' => $this->params["brand_id"], 'order_sort' => $this->params["order_sort"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 30 ? "selected" : "" ?>>30</option>
                                            <option value ="<?php echo $this->serverUrl() . $this->Url('backend-product-search', array('controller' => 'product', 'action' => 'index', 'limit' => 100, 's' => $this->params["s"], 'cate_id' => $this->params["cate_id"], 'brand_id' => $this->params["brand_id"], 'order_sort' => $this->params["order_sort"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 100 ? "selected" : "" ?>>100</option>
                                            <option value ="<?php echo $this->serverUrl() . $this->Url('backend-product-search', array('controller' => 'product', 'action' => 'index', 'limit' => 300, 's' => $this->params["s"], 'cate_id' => $this->params["cate_id"], 'brand_id' => $this->params["brand_id"], 'order_sort' => $this->params["order_sort"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 300 ? "selected" : "" ?>>300</option>
                                            <option value ="<?php echo $this->serverUrl() . $this->Url('backend-product-search', array('controller' => 'product', 'action' => 'index', 'limit' => 500, 's' => $this->params["s"], 'cate_id' => $this->params["cate_id"], 'brand_id' => $this->params["brand_id"], 'order_sort' => $this->params["order_sort"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 500 ? "selected" : "" ?>>500</option>
                                            <option value ="<?php echo $this->serverUrl() . $this->Url('backend-product-search', array('controller' => 'product', 'action' => 'index', 'limit' => 1000, 's' => $this->params["s"], 'cate_id' => $this->params["cate_id"], 'brand_id' => $this->params["brand_id"], 'order_sort' => $this->params["order_sort"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 1000 ? "selected" : "" ?>>1000</option>
                                        </select>
                                    </div>
                                    <div class = "col-sm-3" style = "padding-top: 10px">Dòng</div>
                                </div>
                            </div>
                            <div class = "col-lg-6">
                                <?php echo $this->paging;
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    $('.sumo-multiple-select-box').SumoSelect();
    $('.sumo-select-box').SumoSelect();
    Product.del_all();
//    Product.del();
    Product.edit();
    Product.getSelect();
</script>