<?php
$optionProperties = "";
foreach ($this->arrPropertiesList as $cate) {
    $optionProperties.= '<option ' . ((in_array($cate['prop_id'], $this->params["Properties"])) ? "selected" : "") . ' value="' . $cate['prop_id'] . '">' . $strSpace . $cate['prop_name'] . '</option>';
}
?>
<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-brand')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>

    <div class="row" id="frmAddCity">
        <div class="col-lg-12">
            <section class="panel panel-primary">
                <header id="frmTitle" class="panel-heading">Thêm Danh mục</header>
                <div class="panel-body">
                    <form id="frm" role="form" class="form-horizontal tasi-form" method="POST">
                        <div class="form-group">
                            <label class="col-lg-2 control-label"> Tên Danh mục</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="CategoryName" placeholder="Nhập tên danh mục" value="<?php echo $this->params['CategoryName'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_slug" class="col-lg-2 control-label">URL</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="CateSlug" placeholder="Nhập URL" value="<?php echo $this->params['CateSlug'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"> Thuộc Nhóm   </label>
                            <div class="col-lg-10 tabselect" tabindex= "1" da-select="true">
                                <select name="parentID" class="selectbox selectpicker" data-live-search="true" title="Chọn danh mục">
                                    <?php foreach ($this->arrCategoryList as $key => $arrCategoryList) { ?>
                                        <option value="<?php echo $arrCategoryList['cate_id'] ?>" <?php if ($arrCategoryList['cate_id'] == $this->params['parentID']) { ?> selected <?php } ?>>
                                            <?php
                                            $temp = substr_count($arrCategoryList['cate_grade'], ':');
                                            if ($temp > 0) {
                                                if ($arrCategoryList['cate_parent'] != 0) {
                                                    echo str_repeat('&nbsp;&nbsp;&nbsp;', $temp);
                                                    echo '&#x21b3;&nbsp;&nbsp;';
                                                }
                                            }
                                            echo $arrCategoryList['cate_name'];
                                            ?>
                                        </option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_id" class="col-lg-2 control-label">Chọn nhóm thuộc tính</label>
                            <div class="col-lg-10 tabselect" tabindex= "2">
                                <select name="Properties[]" class="sumo-multiple-select-box sumo-select-box"  multiple="multiple"  id="select-box"data-placeholder="Chọn một nhóm thuộc tính" >
                                    <?php echo $optionProperties ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_order" class="col-lg-2 control-label">Độ ưu tiên</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="CateOrder" placeholder="Nhập Độ ưu tiên" value="<?php echo $this->params['CateOrder'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_status" class="col-lg-2 col-md-2 col-sm-2 col-sm-2 control-label" value="">Tình trạng</label>
                            <div class="col-lg-10 col-md-10 col-sm-10 tabselect" tabindex= "3">
                                <select name="cate_status" class="multi-select form-control sumo-select-box">
                                    <option value="1">Hiển thị</option>
                                    <option value="0">Ẩn</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_description" class="col-lg-2 control-label">Mô tả ngắn về Danh mục</label>
                            <div class="col-lg-10 textedit" tabindex="4" >
                                <textarea rows="6" name="cate_description" id="Sumary" class="form-control editor" style="">
                                    <?php echo $this->params['cate_description']; ?>
                                </textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_meta_title" class="col-lg-2 control-label">SEO Meta Title</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="CateMetaTitle" placeholder="Nhập SEO Meta Title" value="<?php echo $this->params['CateMetaTitle'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_meta_keyword" class="col-lg-2 control-label">SEO Meta Keyword</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="CateMetaKeyword" placeholder="Nhập SEO Meta Keyword" value="<?php echo $this->params['CateMetaKeyword'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_meta_description" class="col-lg-2 control-label">SEO Meta Description</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="CateMetaDescription" placeholder="Nhập SEO Meta Description" value="<?php echo $this->params['CateMetaDescription'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_meta_social" class="col-lg-2 control-label">SEO Meta Social</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="CateMetaSocial" placeholder="Nhập SEO Meta Social" value="<?php echo $this->params['CateMetaSocial'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-offset-3 col-lg-10">
                                <button type="button" onclick="document.getElementById('frm').submit();" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                                <button type="button" onclick="document.getElementById('frm').submit();" id="done" class="btn btn-success bt-save" name="save_close"><i class="icon-save"></i> Lưu & Thoát</button> 
                                <input value="0" name="is_close" class="is_close" type="hidden" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
</section>
<script>
    Category.index();
</script>