<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-category')->getMessages(), $this->flashMessenger()->setNamespace('success-edit-category')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>
    <section class="panel">
        <header class="panel-heading">
            Danh sách Danh mục
        </header>
        <div class="panel-body">    
            <div class="adv-table editable-table ">  
                <div class="row">
                    <div class="col-lg-6">                  
                        <div id="editable-sample_length" class="dataTables_length no-padding">
                            <a class="btn btn-primary" href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'category', 'action' => 'add', 'limit' => $this->params["limit"])); ?>" ><i class="icon-plus-sign-alt"></i> Thêm</a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <form id="frm" class="form-horizontal" role="form" method="GET">
                            <div class="col-xs-9 no-padding">
                                <div class="dataTables_filter no-padding per-100">
                                    <label><input  name="s"  value="<?php echo $this->params["s"]; ?>" type="text" aria-controls="editable-sample" class="per-100 input-seaching form-control medium"></label>
                                </div>
                            </div>
                            <div class="col-xs-3 no-padding-right">
                                <button type="submit" class="btn btn-white per-100" ><i class="icon-search"></i> Tìm kiếm</button>
                            </div>
                        </form>
                    </div>
                </div>
                <section id="unseen">
                    <table class="table table-bordered table-striped table-condensed cf">
                        <thead class="cf">
                            <tr>
                                <th class="text-center"><i class="icon-list"></i> ID</th>
                                <th><i class="icon-list-alt"></i> Tên Danh mục</th>
                                <th class="text-center"><i class="icon-ok"></i> Ngày tạo</th>
                                <th class="text-center"><i class="icon-check"></i> Trạng thái </th>
                                <th class="text-center"><i class="icon-edit"></i> Chức năng</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if ($this->arrCategoryList):
                                foreach ($this->arrCategoryList as $arrCategoryList):
                                    ?>
                                    <tr>
                                        <td  class="text-center" width="80">
                                            <?php echo $arrCategoryList['cate_id']; ?>
                                        </td>
                                        <td>
                                            <a>
                                                <?php
                                                if ($arrCategoryList['cate_parent'] == 0) {
                                                    echo $arrCategoryList['cate_name'];
                                                } else {
                                                    $temp = substr_count($arrCategoryList['cate_grade'], ':');
                                                    echo str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;', $temp);
                                                    echo '&#x21b3;&nbsp;&nbsp;';
                                                    echo $arrCategoryList['cate_name'];
                                                }
                                                ?>
                                            </a>
                                        </td>
                                        <td  class="text-center"><?php echo date('d/m/Y', $arrCategoryList['cate_created']); ?></td>
                                        <td  class="text-center"><?php if ($arrCategoryList['cate_status'] == 1): ?><a href="javascript:;" class="tooltips" data-placement="top" data-original-title="Đang hiện"><i class="icon-ok color-success"></a><?php
                                            endif;
                                            if ($arrCategoryList['cate_status'] == 0):
                                                ?><a href="javascript:;" class="tooltips" data-placement="top" data-original-title="Đang ẩn"><i class="icon-minus-sign color-danger"></i></a><?php endif; ?></td>
                                        <td class="text-center" width="200">
                                            <a  href="<?php echo $this->serverUrl() . $this->Url('category', array('controller' => 'category', 'action' => 'index', 'categorySlug' => $arrCategoryList["cate_slug"], 'categoryID' => $arrCategoryList["cate_id"])); ?>" target="_bank"  class="btn btn-primary btn-xs"><i class="icon-eye-open"></i> Xem</a>
                                            <a  href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'category', 'action' => 'edit', 'id' => $arrCategoryList['cate_id'])); ?>"  class="btn btn-primary btn-xs  edit" data-placement="top" data-original-title="Sửa danh mục"  rel="<?php echo $arrCategoryList['cate_id'] ?>"><i class="icon-pencil"></i> Sửa</a>
                                            <a  class="btn btn-danger btn-xs remove tooltips" data-placement="top" data-original-title="Xóa danh mục" rel="<?php echo $arrCategoryList['cate_id'] ?>"><i class="icon-trash "></i> Xóa</a>
                                        </td>
                                    </tr>

                                <?php endforeach; ?>
                            <?php else: ?>
                                <tr><td colspan="6" class="text-center">Hiện tại chưa có danh mục nào.</td></tr>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </section>
            </div>
            <div>
                <div class="row">
                    <div  class="col-lg-6">
                        <div class="form-group">
                            <div  class="col-sm-3 col-xs-3">
                                <select name="limit" class="form-control" onchange="window.location.href = this.value">
                                    <option value="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'category', 'action' => 'index', 'limit' => 15, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 15 ? "selected" : "" ?>>15</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'category', 'action' => 'index', 'limit' => 30, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 30 ? "selected" : "" ?>>30</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'category', 'action' => 'index', 'limit' => 100, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 100 ? "selected" : "" ?>>100</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'category', 'action' => 'index', 'limit' => 300, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 300 ? "selected" : "" ?>>300</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'category', 'action' => 'index', 'limit' => 500, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 500 ? "selected" : "" ?>>500</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'category', 'action' => 'index', 'limit' => 1000, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 1000 ? "selected" : "" ?>>1000</option>
                                </select>
                            </div>
                            <div class = "col-sm-3" style = "padding-top: 10px">Dòng</div>
                        </div>
                    </div>
                    <div class = "col-lg-6">
                        <?php echo $this->paging;
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
</section>
<script type="text/javascript">
    Category.del();
</script>