<?php

$arrRole = $this->arrRole;
?>
<section class="wrapper site-min-height">   
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-times-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-user')->getMessages(), $this->flashMessenger()->setNamespace('success-edit-user')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>
    <section class="panel">
        <header class="panel-heading">
            Danh sách đơn hàng của khách hàng <strong><?php echo $this->arrInfoUser['user_fullname'] ?></strong>
        </header>
        <div class="panel-body">    
            <div class="adv-table editable-table ">  
                <div class="row">
                    <div class="col-lg-4 col-sm-4 col-md-4 col-xs-12">                  
<!--                        <div id="editable-sample_length" class="dataTables_length no-padding">
                            <a class="btn btn-primary" href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'user', 'action' => 'add')); ?>" ><i class="icon-plus-sign-alt"></i> Thêm</a>
                        </div>-->
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
<!--                        <form id="frm" class="form-horizontal" role="form" method="GET">
                            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-8 no-padding">
                                <div class="dataTables_filter no-padding per-100">
                                    <label><input  name="s"  value="<?php echo $this->params["s"]; ?>" type="text" aria-controls="editable-sample" class="per-100 input-seaching form-control medium"></label>
                                </div>
                            </div>
                            <div class="col-lg-3 col-sm-3 col-md-3 col-xs-4 no-padding-right">
                                <button type="submit"  class="btn btn-white per-100" ><i class="icon-search"></i> Tìm kiếm</button>
                            </div>
                        </form>-->
                    </div>
                </div>
                <section id="unseen">
                    <table class="table table-bordered table-striped table-condensed cf">
                            <thead class="cf">
                                <tr>
                                    <th class="text-center"><i class="icon-list"></i> Mã đơn hàng</th>
                                    <th class="text-center"><i class="icon-list"></i> Mã sản phẩm</th>
                                    <th class="text-center visible-xs visible-md visible-sm visible-lg"><i class="icon-list-alt"></i> Họ tên khách hàng</th>
                                    <th class="text-center hidden-sm hidden-xs"><i class="icon-dollar"></i> Tổng tiền 
                            <div class="co-red text-right" style="color:#F00"><?php echo number_format($this->intTotalOrder['sum_total_order'], 0, ',', '.'); ?> VNĐ</div>
                            </th>
                            <th class="text-center visible-xs visible-md visible-sm visible-lg"> Trạng thái </th>
                            <th class="text-center"><i class="icon-ok"></i> Ngày đặt hàng</th>
                            <th class="text-center hidden-xs hidden-sm"><i class="icon-user"></i> Người duyệt </th>
                            <th class="text-center visible-xs visible-md visible-sm visible-lg"><i class="icon-edit"></i> Chức năng</th>
                            </tr>
                            </thead>
                            <tbody>
                                <?php
                                if ($this->arrListOrder):
                                    foreach ($this->arrListOrder as $arrOrderList):
                                        ?>
                                        <tr>
                                            <td class="text-center" width="150"><?php echo $arrOrderList['orde_code'] . $arrOrderList['orde_id']; ?></td>
                                            <td class="text-center" width="150">
                                                <?php
                                                    if ($this->arrListProductOrder) {
                                                        $arrListProductOrder = $this->arrListProductOrder[$arrOrderList['orde_id']];
                                                        if (count($arrListProductOrder) > 0) {
                                                            $strListProduct = '';
                                                            foreach ($arrListProductOrder as $arrListOrder) {
                                                                $strListProduct .= '<a target="_blank" href="' . $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $arrListOrder["prod_slug"], 'productId' => $arrListOrder['prod_id'])) . '">' . $this->arrListProduct[$arrListOrder['prod_id']] . '</a>, ';
                                                            }
                                                            echo rtrim($strListProduct, ', ');
                                                        }
                                                    }   
                                                ?>
                                            </td>

                                            <td class="text-left"><span style="text-transform: capitalize;"><?php echo $arrOrderList['user_fullname']; ?></span></td>
                                            <td class="text-right"><?php echo number_format($arrOrderList['orde_total_price'], 0, ",", "."); ?> VNĐ</td>
                                            <td class="text-center"><strong>
                                                    <?php
                                                    switch ($arrOrderList['is_payment']) {
                                                        case -1:
                                                            echo '<span class="label label-danger tooltips" data-placement="top" data-original-title="' . My\General::getStatusOrder()[$arrOrderList['is_payment']] . '">' . My\General::getStatusOrder()[$arrOrderList['is_payment']] . '</span>';
                                                            break;
                                                        case 0:
                                                            echo '<span class="label label-warning tooltips" data-placement="top" data-original-title="' . My\General::getStatusOrder()[$arrOrderList['is_payment']] . '">' . My\General::getStatusOrder()[$arrOrderList['is_payment']] . '</span>';
                                                            break;
                                                        case 1:
                                                            echo '<span class="label label-info tooltips" data-placement="top" data-original-title="' . My\General::getStatusOrder()[$arrOrderList['is_payment']] . '">' . My\General::getStatusOrder()[$arrOrderList['is_payment']] . '</span>';
                                                            break;
                                                        case 2:
                                                            echo '<span class="label label-primary tooltips" data-placement="top" data-original-title="' . My\General::getStatusOrder()[$arrOrderList['is_payment']] . '">' . My\General::getStatusOrder()[$arrOrderList['is_payment']] . '</span>';
                                                            break;
                                                        case 3:
                                                            echo '<span class="label label-warning tooltips" data-placement="top" data-original-title="' . My\General::getStatusOrder()[$arrOrderList['is_payment']] . '">' . My\General::getStatusOrder()[$arrOrderList['is_payment']] . '</span>';
                                                            break;
                                                        case 4:
                                                            echo '<span class="label label-success tooltips" data-placement="top" data-original-title="' . My\General::getStatusOrder()[$arrOrderList['is_payment']] . '">' . My\General::getStatusOrder()[$arrOrderList['is_payment']] . '</span>';
                                                            break;
                                                        case 5:
                                                            echo '<span class="label label-default tooltips" data-placement="top" data-original-title="' . My\General::getStatusOrder()[$arrOrderList['is_payment']] . '">' . My\General::getStatusOrder()[$arrOrderList['is_payment']] . '</span>';
                                                            break;
                                                        case 6:
                                                            echo '<span class="label label-inverse tooltips" data-placement="top" data-original-title="' . My\General::getStatusOrder()[$arrOrderList['is_payment']] . '">' . My\General::getStatusOrder()[$arrOrderList['is_payment']] . '</span>';
                                                            break;
                                                    }
                                                    ?>
                                                </strong>
                                            </td>
                                            <td class="text-center"><?php echo date('d/m/Y H:i:s', $arrOrderList['orde_created']); ?></td>
                                            <td class="text-center hidden-xs hidden-sm"><?php echo $arrOrderList['user_change_status']; ?></td>
                                            <td class="text-center visible-xs visible-md visible-sm visible-lg" width="150">
                                                <a  href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'order', 'action' => 'view', 'id' => $arrOrderList['orde_id'])); ?>"  class="btn btn-primary btn-xs  edit" data-placement="top" data-original-title="Xem thông tin đơn hàng"><i class="icon-eye-open"></i> Xem</a>
                                                <!--<a  href="javascript:;"  class="btn btn-danger btn-xs  trash" data-placement="top" data-original-title="Xóa đơn hàng này" rel="<?php echo $arrOrderList['orde_id']; ?>"><i class="icon-trash"></i> Xóa</a>-->
                                            </td>
                                        </tr>

                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr><td colspan="8" class="text-center">Hiện tại chưa có đơn hàng nào.</td></tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                </section>
            </div>
            <div>
                <?php echo $this->paging; ?>
            </div>
        </div>
    </section>
</section>
<script type="text/javascript">

</script>