<div id=":p1" class="ii gt m14ce51e6703b6edc adP adO"><div id=":p0" class="a3s" style="overflow: hidden;"><div class="adM"> </div><table width="700px" cellspacing="0" cellpadding="0" align="center" style="background:#ffffff;border:1px solid #37c3ff;padding:10px 10px" valign="middle">
            <tbody>
                <tr>
                    <td align="center" colspan="2"><img src="<?php echo STATIC_URL.'/f/v1/images/logo-email.png'?>" class="CToWUd"></td>
                </tr>
                <tr style="overflow:hidden">
                    <td style="color:#3bace1;padding-top:10px"><strong>Cảm ơn Quý khách</strong></td>
                </tr>
                <tr>
                    <td style="width:60%">
                        <table cellspacing="0" cellpadding="0" align="center" style="line-height:20px;font-size:13px;padding-right:30px;text-align:justify" valign="middle">
                            <tbody><tr><td style="padding-top:5px"></td></tr>
                                <tr><td style="padding-top:5px">Mã đơn hàng <font color="red"><?php echo My\General::PREFIX_IN . sprintf("%03d", $this->orde_id); ?></font> của Quý khác đã bị hủy. Vì <?php echo $this->content_cancel; ?>. <br></td></tr>
                            </tbody></table>
                    </td>
                </tr>

                <tr>
                    <td colspan="2"> &nbsp; </td>
                </tr>
                <tr>
                    <td colspan="2"> &nbsp; </td>
                </tr>
                <tr style="background:#e3f5ff">
                    <td style="font-size:13px;padding:10px 10px;border-radius:5px;line-height:20px" colspan="2">Cảm ơn Quý khách đã sử dụng dịch vụ của <strong><a href="<?php echo $this->serverUrl(); ?>">Megavita.vn</a></strong>:
                        <br><strong>Địa chỉ văn phòng Megavita.vn : 61C Tú Xương, Phường 7, Quận 3, TP.HCM - <?php echo HOTLINE_NUMBER; ?></strong><br>
                    </td>
                </tr>
                <tr>
                    <td style="font-size:13px;padding:0px 10px;border-radius:5px;line-height:20px" colspan="2">Nếu quý khách cần hỗ trợ, vui lòng gọi  <span style="color:#f00;font-weight:bold;font-size:15px"><?php echo HOTLINE_NUMBER; ?></span> hoặc gửi email đến: <span style="color:#0f72e2"><a href="mailto:<?php echo \My\General::EMAIL_SUPPORT ?>" target="_blank"><?php echo \My\General::EMAIL_SUPPORT ?></a></span>.</td>
                </tr>
                <tr>
                    <td style="font-size:13px;padding:10px 10px;border-radius:5px;line-height:20px;color:#888888" colspan="2">(*) Đây là email hệ thống gửi tự động, vui lòng không trả lời (reply) lại email này.</td>
                </tr>
                <tr>
                <td colspan="2"  style="padding: 30px 10px;"><img src="<?php echo STATIC_URL.'/f/v1/images/line.png'?>" alt=""/></td>
                </tr>
                <tr>
                    <td style="font-size:20px;padding:20px 10px;border-radius:5px;line-height:20px;color:#3bace1;font-weight:bold;text-align:center" colspan="2">Megavita.vn - Siêu thị khỏe và đẹp online !</td>
                </tr>
            </tbody>
        </table><div class="yj6qo"></div><div class="adL">
        </div></div></div>