<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-category')->getMessages(), $this->flashMessenger()->setNamespace('success-edit-category')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>
    <section class="panel">
        <header class="panel-heading">
            Danh sách sản phẩm trong order
        </header>
        <div class="panel-body">    
            <div class="adv-table editable-table ">  
                <div class="row">
                    <div class="col-lg-3">

                    </div>
                    <div class="col-lg-9">
                        <form id="frm" class="form-horizontal" role="form" method="GET">
                            <div class="row">
                                <div class="col-md-3">     
                                    <div data-date-format="dd/mm/yyyy" data-date="" class="input-group input-large">
                                        <input type="text" name="date_from" class="form-control dpd1" placeholder="Từ ngày" value="<?php echo empty($this->params['date_from']) ? date('d/m/Y', (time())) : $this->params['date_from']; ?>">
                                        <span class="input-group-addon">Đến</span>
                                        <input type="text" name="date_to" class="form-control dpd2" placeholder="Đến ngày" value="<?php echo empty($this->params['date_to']) ? date('d/m/Y', time()) : $this->params['date_to']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <select class="form-control" name="status">
                                        <option <?php echo (!isset($this->params['status'])) ? 'selected' : '' ?> value="" >Tất cả</option>
                                        <option <?php echo ($this->params['status'] == -1) ? 'selected' : '' ?> value="-1">Chưa duyệt </option>
                                        <option <?php echo ($this->params['status'] == 0 && $this->params['status'] != '') ? 'selected' : '' ?> value="0">Hết hàng</option>
                                        <option <?php echo ($this->params['status'] == 1) ? 'selected' : '' ?> value="1">Còn hàng</option>
                                    </select>
                                </div>
                                <div class="col-md-3">
                                    <div class="dataTables_filter no-padding per-100">
                                        <label><input  name="s"  value="<?php echo $this->params["s"]; ?>" type="text" aria-controls="editable-sample" class="per-100 input-seaching form-control medium"></label>
                                    </div>
                                </div>
                                <div class="col-xs-3">
                                    <button type="submit" class="btn btn-white per-100" ><i class="icon-search"></i> Tìm kiếm</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <section id="unseen">
                    <table class="table table-bordered table-striped table-condensed cf">
                        <thead class="cf">
                            <tr>
                                <th class="text-center"><i class="icon-list"></i> ID</th>
                                <th><i class="icon-list-alt"></i> Tên sản phẩm</th>
                                <th class="text-center"><i class="icon-list"></i>Order</th>
                                <th class="text-center"></i>Số lượng</th>
                                <th class="text-center"><i class="icon-check"></i> Trạng thái </th>
                                <th class="text-center"><i class="icon-check"></i> Chức năng </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if ($this->arrProd):
                                foreach ($this->arrProd as $arrProd):
                                    ?>
                                    <tr>
                                        <td  class="text-center" width="80">
                                            <?php echo $arrProd['prod_id']; ?>
                                        </td>
                                        <td width="50%">
                                            <a target="_bank" href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $arrProd["prod_slug"], 'productId' => $arrProd["prod_id"])); ?>">
                                                <?php echo $arrProd['prod_name']; ?>
                                            </a>
                                        </td>
                                        <td class="text-center" width="80"><?php echo \My\General::ORDER_CODE . $arrProd['orde_id']; ?></td>
                                        <td class="text-center" width="80"><?php echo $arrProd['prod_quantity']; ?></td>
                                        <td  class="text-center" width="80">
                                            <strong>
                                                <?php
                                                switch ($arrProd['prod_status']) {
                                                    case -1:
                                                        echo '<span class="label label-default tooltips" data-placement="top" data-original-title="' . My\General::getStatusProdOrder()[$arrProd['prod_status']] . '">' . My\General::getStatusProdOrder()[$arrProd['prod_status']] . '</span>';
                                                        break;
                                                    case 0:
                                                        echo '<span class="label label-danger tooltips" data-placement="top" data-original-title="' . My\General::getStatusProdOrder()[$arrProd['prod_status']] . '">' . My\General::getStatusProdOrder()[$arrProd['prod_status']] . '</span>';
                                                        break;
                                                    case 1:
                                                        echo '<span class="label label-success tooltips" data-placement="top" data-original-title="' . My\General::getStatusProdOrder()[$arrProd['prod_status']] . '">' . My\General::getStatusProdOrder()[$arrProd['prod_status']] . '</span>';
                                                        break;
                                                }
                                                ?>
                                            </strong>
                                        </td>
                                        </td>
                                        <td>
                                            <select class="form-control changeStatusProdOrder" data-id="<?php echo $arrProd['product_order_id']; ?>">
                                                <?php for ($i = -1; $i <= 1; $i++) { ?>  
                                                    <option <?php echo ($arrProd['prod_status'] == $i) ? 'selected' : '' ?> value="<?php echo $i ?>"><?php echo My\General::getStatusProdOrder()[$i] ?></option>
                                                    <?php
                                                }
                                                ?>
                                            </select>
                                        </td>
                                    </tr>

                                <?php endforeach; ?>
                            <?php else: ?>
                                <tr><td colspan="6" class="text-center">Hiện tại chưa có sản phẩm nào nào.</td></tr>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </section>
            </div>
            <div>
                <div class="row">
                    <div  class="col-lg-6">
                        <div class="form-group">
                            <div  class="col-sm-3 col-xs-3">
                                <select name="limit" class="form-control" onchange="window.location.href = this.value">
                                    <option value="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'order', 'action' => 'product', 'limit' => 15, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 15 ? "selected" : "" ?>>15</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'order', 'action' => 'product', 'limit' => 30, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 30 ? "selected" : "" ?>>30</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'order', 'action' => 'product', 'limit' => 100, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 100 ? "selected" : "" ?>>100</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'order', 'action' => 'product', 'limit' => 300, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 300 ? "selected" : "" ?>>300</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'order', 'action' => 'product', 'limit' => 500, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 500 ? "selected" : "" ?>>500</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'order', 'action' => 'product', 'limit' => 1000, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 1000 ? "selected" : "" ?>>1000</option>
                                </select>
                            </div>
                            <div class = "col-sm-3" style = "padding-top: 10px">Dòng</div>
                        </div>
                    </div>
                    <div class = "col-lg-6">
                        <?php echo $this->paging;
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
</section>
<script type="text/javascript">
    Order.product();
</script>