<?php //p($this->arrProductList);die; ?>
<section class="wrapper site-min-height">
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <?php if ($this->errors): ?>
                    <div class="alert alert-block alert-danger fade in">
                        <button class="close close-sm" type="button" data-dismiss="alert">
                            <i class="icon-remove"></i>
                        </button>
                        <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
                        <?php foreach ($this->errors as $error): ?>
                            <p> - <?php echo $error; ?></p>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>

                <?php
                $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-order')->getMessages());
                if ($successMessage):
                    ?>
                    <div class="alert alert-success alert-block fade in">
                        <button class="close close-sm" type="button" data-dismiss="alert">
                            <i class="icon-remove"></i>
                        </button>
                        <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
                        <p>- <?php echo current($successMessage); ?></p>
                    </div>
                <?php endif; ?>
                <header class="panel-heading">Chi tiết đơn hàng</header>
                <div class="panel-body">
                    <div class="row invoice-list">
                        <div class="col-lg-4 col-sm-4">
                            <h4>THÔNG TIN KHÁCH HÀNG</h4>
                            <p>
                                <b>Họ tên :</b> <?php echo $this->userInfo['fullname']; ?> <br>
                                <b>Địa chỉ :</b> <?php echo $this->userInfo['address']; ?> <br>
                                <b>Số điện thoại :</b> <?php echo $this->userInfo['phone']; ?><br>
                                <b>Email :</b> <?php echo $this->userInfo['email']; ?>
                            </p>
                        </div>
                        <div class="col-lg-4 col-sm-4">
                            <h4>TRẠNG THÁI ĐƠN HÀNG</h4>
                            <p>
                                <b>Trạng thái :</b> <?php echo My\General::getStatusOrder()[$this->detailOrder['is_payment']]?><br>
                                <b>Mã đơn hàng :</b> <?php echo My\General::PREFIX_IN . sprintf("%03d",$this->detailOrder['orde_id']);?><br/>
                                <b>Ngày đặt hàng :</b> <?php echo date('d/m/Y', $this->detailOrder['orde_created']); ?><br>
                                <b>Tổng tiền :</b> <?php echo number_format($this->detailOrder['orde_total_price'], 2, ",", ".") . ' VNĐ'; ?><br>
                            </p>
                        </div>
                        <?php if($this->detailOrder['is_payment']!=0):?>
                        <div class="col-lg-4 col-sm-4">
                            <h4>NGƯỜI XỬ LÝ ĐƠN HÀNG</h4>
                            <p>
                                <b>Người duyệt : </b> <?php echo $this->detailOrder['user_change_status'];?><br/>
                                <b>Ngày duyệt  : </b> <?php echo date('d/m/Y',$this->detailOrder['orde_updated']);?><br/>
                                <?php if($this->detailOrder['is_payment']==-1):?><b>Lý do hủy   : </b> <?php echo $this->detailOrder['content_cancel'];?><br/><?php endif;?>
                            </p>
                        </div>
                        <?php endif;?>
                    </div>
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th class="text-center">Tên sản phẩm</th>
                                <th class="text-center">Số lượng</th>
                                <th class="text-center">Giá bán</th>
                                <th class="text-center">Chiết khấu</th>
                                <th class="text-center">Tổng tiền</th>
                                <th class="text-center">Ghi chú</th>
                                <th class="text-center">Chức năng</th>
                            </tr>
                        </thead>
                        <tbody>
                            <input type="hidden" id="OrderID" value="<?php echo $this->detailOrder['orde_id'];?>" />
                           <?php
                            if ($this->arrProductList):
                                
                                foreach ($this->arrProductList as $key => $value):
                                    ?>
                                    <tr>
                                        <td class="text-center ProductOrderID"><?php echo $key +1 ?></td>
                                        <td class="text-left" width="250">
                                            <a href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => 'productslug', 'productId' => $value['prod_id'])) ?>" target="_bank">                                    
                                                <?php echo $value['prod_name']; ?>
                                            </a>
                                        </td>
                                        <td class="text-center prodQuantity" width="80"><?php echo $value['prod_quantity']; ?></td>
                                        <td class="text-center prodPrice"><?php
                                    if ($value['prod_call_price'] != 1) {
                                        echo number_format($value['prod_price'], 2, ",", ".") . ' VNĐ';
                                    } else {
                                        ?>Giá liên hệ ...<br/>(Giá thực : <small class="text-muted " style="color:#F00"><?php echo number_format($arrProductList['prod_price'], 2, ",", ".") . ' VNĐ'; ?></small>)<?php } ?></td>
                                        <td class="text-center disCount"><?php echo $value['discount']; ?>%</td>
                                        <td class="text-center TotalPrice"><?php
                                            if ($value['prod_call_price'] != 1) {
                                                echo number_format($value['total_price'], 2, ",", ".") . ' VNĐ';
                                            } else {
                                                ?>Đang cập nhật ... <br/><small class="text-muted ">(Tổng tiền : <small class="text-muted " style="color:#F00"><?php echo number_format($arrProductList['total_price'], 2, ",", ".") . ' VNĐ'; ?></small>)</small><?php } ?></td> 
                                        <td class="text-center note"><?php echo $value['orde_note']; ?></td>
                                        <td class="text-center" width="200">
                                    <?php if ($value['prod_call_price'] == 1) { ?>
                                                <a class="btn btn-primary btn-xs  edit" data-placement="top" data-original-title="Sửa giá liên hệ" rel="<?php echo $value['product_order_id'] ?>"><i class="icon-pencil"></i> Sửa giá bán</a>
                                                <a class="btn btn-primary btn-xs  check" data-placement="top" style = "display:none"><i class="icon-ok"></i> Cập nhật </a>
                                                <a class="btn btn-primary btn-xs  denied" data-placement="top" style = "display:none"><i class="icon-remove"></i> Bỏ qua</a>
                                            </td>
                                             <?php } ?>
                                    </tr>
                                        <?php endforeach; ?>
                                    <?php else: ?>
                                <tr><td colspan="8" class="text-center">Hiện tại không có sản phẩm.</td></tr>
                            <?php endif; ?>
                        </tbody>
                    </table>
                    <?php if ($this->detailOrder['is_payment'] >= 0) { ?>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group text-center">
                                    <form method="POST" action="">
                                        <?php if ($this->detailOrder['is_payment'] == 0) { ?>
                                        <button type="submit" class="btn btn-danger btn-lg" data-placement="top" ><i class="icon-ok"></i> Duyệt </button>
                                        <?php } ?>
                                        <button type="button" class="btn btn-info btn-lg remove" data-placement="top" rel="<?php echo $this->detailOrder['orde_id'] ?>"><i class="icon-remove"></i> Hủy </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </section>
        </div>
    </div>
</section>
<script>
    Order.index();
</script>
