<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-times-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = $this->flashMessenger()->setNamespace('success-add-meeting')->getMessages();
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>

    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <div class="row">
                    <div class="col-lg-12">
                        <section class="panel">
                            <header class="panel-heading">Sửa cuộc họp</header>
                            <div class="panel-body">
                                <form method="POST" role="form" class="form-horizontal tasi-form" id="frm" novalidate="novalidate">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="meeting-name" class="col-lg-2 control-label" value="">Title</label>
                                            <div class="col-lg-10">
                                                <input type="text" value="<?php echo $this->arrDetailMeeting["meet_title"] ?>" placeholder="Nhập title" class="form-control" name="title" id="title-meeting">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="meeting-content" class="col-lg-2 control-label" value="">Content</label>
                                            <div class="col-lg-10">
                                                <textarea rows="20" class="form-control editor" name="content" id=content-meeting"><?php echo $this->arrDetailMeeting["meet_content"] ?></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button type="submit" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                                                <button type="submit" id="done" class="btn btn-success bt-save" name="save_close"><i class="icon-save"></i> Lưu & Thoát</button> 
                                                <input value="0" name="is_close" class="is_close" type="hidden" />
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </section>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    Meeting.index();
</script>