<section class="wrapper site-min-height">
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">Danh sách cuộc họp</header>
                <div class="panel-body">
                    <section id="unseen">
                        <table class="table table-bordered table-striped table-condensed cf">
                            <thead class="cf">
                                <tr>
                                    <th class="numeric text-center" width="7%">STT</th>
                                    <th class="numeric text-center">Tiêu đề</th>
                                    <th class="numeric text-center" width="10%">Ngày tạo</th>
                                    <th class="numeric text-center" width="10%">Người tạo</th>
                                    <th class="numeric text-center" width="20%">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if($this->arrMeeting){
                                    foreach($this->arrMeeting as $key => $value){ 
                                        $key ++;
                                ?>
                                        <tr>
                                            <td style="text-align: center"><?php echo $key ?></td>
                                            <td style="text-align: center"><?php echo $value['meet_title'] ?></td>
                                            <td style="text-align: center"><?php echo date('d/m/Y',$value['meet_date']) ?></td>
                                            <td style="text-align: center">
                                                <?php 
                                                    echo $this->arrUserDetail[$value['user_created']]['user_fullname'];
                                                ?>
                                            </td>
                                            <td style="text-align: center">
                                                <a href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'meeting', 'action' => 'edit', 'id' => $value['meet_id'])); ?>" target="_bank" class="btn btn-primary btn-xs"><i class="icon-eye-open"></i> Xem</a>
                                            </td>
                                        </tr>
                                <?php
                                    }
                                }else{
                                    echo '<tr><td style="text-align: center" colspan="5">Không tìm thấy dữ liệu</td></tr>';
                                }
                                ?>
                            </tbody>
                        </table>
                    </section>
                    <div>
                        <div class="row">
                            <div  class="col-lg-6">
                                &nbsp;
                            </div>
                            <div class = "col-lg-6">
                                <?php echo $this->paging;?>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
</script>