<section id="unseen">
    <header class="panel-heading">Danh sách sản phẩm <?php echo $this->name ?></header>
    <div class="row">
        <div class="col-lg-4">
            <div class="dataTables_filter no-padding per-100">
                <select name="sort" class="sumo-multiple-select-box" id="sort">
                    <option value="1" <?php echo ((int) $this->params['sort'] === 1) ? "selected" : "" ?>>Giảm dần</option>
                    <option value="0" <?php echo ((int) $this->params['sort'] === 0) ? "selected" : "" ?>>Tăng dần</option>                    
                </select>
            </div>
        </div>
        <div class="col-lg-5">
            <label class="col-xs-12">
                <input type="text" name="text" aria-controls="editable-sample" class="input-seaching form-control search_product" value="<?php echo $this->params['search_name'] ?>">
            </label>
        </div>
        <div class="col-lg-3">
            <button type="button" class="form-control btn btn-white btn-searchProduct"><i class="icon-search"></i> Tìm kiếm</button>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-lg-12">
            <div class="searchproduct">
                <table class="table table-striped table-bordered" cellspacing="0">
                    <thead>
                        <tr>
                            <th style="text-align:center;width:10%" class="numeric">Id</th>
                            <th style="text-align:center;width:40%">Tên sản phẩm</th>
                            <th style="text-align:center;width:10%">Số đơn hàng</th>
                            <th style="text-align:center;width:10%">Tổng số lượng</th>
                            <th style="text-align:center;width:20%">Tổng tiền</th>
                            <th style="text-align:center;width:10%">Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                    <input type="hidden" value="<?php echo $this->params['condition'] ?>" id="condition">
                    <input type="hidden" value="<?php echo $this->params['name'] ?>" id="name">
                    <?php
                    if ($this->arrProduct) {
                        foreach ($this->arrProduct as $arrProductList) {
                            ?>
                            <tr id="<?php echo $arrProductList['prod_id']; ?>">
                                <td style="text-align: center">
                                    <?php $prod_id = $arrProductList['prod_id'];
                                    echo $this->arrProdCode[$prod_id]['prod_code'] ?>
                                </td>
                                <td>
                                    <?php echo $arrProductList['prod_name']; ?>
                                </td>
                                <td style="text-align: center">
                                    <?php echo $arrProductList['num']; ?>
                                </td>
                                <td style="text-align: center">
                                    <?php echo $arrProductList['quantity']; ?>
                                </td>
                                <td style="text-align: center">
                                    <?php echo number_format($arrProductList['total']); ?>
                                </td>
                                <td style="text-align: center">
                                    <a  href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $arrProductList["prod_slug"], 'productId' => $arrProductList['prod_id'])) ?>" target="_bank"  class="btn btn-primary btn-xs"><i class="icon-eye-open"></i> Xem</a>
                                </td>
                            </tr>
                            <?php
                        }
                    } else {
                        ?>
                        <tr class="none-product">
                            <td colspan="6" style="text-align:center;">Hiện tại chưa có sản phẩm nào.</td>
                        </tr>
                    <?php } ?>

                    </tbody>
                </table>
                <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12" >
                    <?php echo $this->paging; ?>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    var search_product = $('.search_product').val();
    function loadPage(page, action) {
        var from = $('#main-from').val();
        var to = $('#main-to').val();
        var condition = $('#condition').val();
        var name = $('#name').val();
        var sort = $('#sort').find(":selected").val();
        $('.show-prod').load(baseurl + '/backend/statistic/' + action + '/page/' + page, {condition: condition, from: from, to: to, name: name, search_name: search_product, sort: sort});
    }
    ;
    Statistic.searchProd();
    $('.sumo-multiple-select-box').SumoSelect({okCancelInMulti: false});
</script>