<?php
$intToltalOrder = $this->intToltalOrder;
$intMethodBaoKim = $this->intMethodBaoKim;
$intMethodTransfer = $this->intMethodTransfer;
$intMethodReceived = $this->intMethodReceived;
?>
<div class="col-lg-12">
    <div class="col-lg-4">
        <section class="panel">
            <header class="panel-heading">
                Thống kê
            </header>
            <div class="panel-body">
                <table class="table table-striped table-bordered" cellspacing="0">
                    <thead>
                        <tr>
                            <th style="text-align:center">Hình thức thanh toán</th>
                            <th style="text-align:center;">Tổng</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td style="text-align: left">
                                <b>Bảo Kim</b>
                            </td>
                            <td style="text-align:center"><?php echo $intMethodBaoKim; ?></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">
                                <b>Chuyển Khoản</b>
                            </td>
                            <td style="text-align:center"><?php echo $intMethodTransfer; ?></td>
                        </tr>
                        <tr>
                            <td style="text-align: left">
                                <b>Trả tiền khi nhận hàng </b>
                            </td>
                            <td style="text-align:center"><?php echo $intMethodReceived; ?></td>
                        </tr>
                        <tr style="color: red; font-size: 15px; font-weight: 700">
                            <td style="text-align: left">
                                <b>Tổng cộng </b>
                            </td>
                            <td style="text-align:center"><?php echo $intToltalOrder; ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </section>
    </div>
    <div class="col-lg-8">
        <section class="panel">
            <header class="panel-heading">
                Biểu đồ
            </header>
            <div class="panel-body">
                <div class="chart-ship-pie">

                </div>
            </div>
        </section>
    </div>
</div>