<?php
$sellBest = $this->prodSellBest;
$sellSlow = $this->prodSellSlow;
$sellNo = $this->prodSellNo;
?>
<section class="panel">
    <header class="panel-heading">Phân tích sản phẩm</header>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-5">
                <div class="row">
                    <div class="col-sm-8">
                        <div class="input-group input-large" data-date-format="dd/mm/yyyy">
                            <input type="text" class="form-control dpd1" id="from" value="<?php echo $this->date['from'] ?>">
                            <span class="input-group-addon">To</span>
                            <input type="text" class="form-control dpd2" id="to" value="<?php echo $this->date['to'] ?>">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <button type="button" class="btn btn-white per-100 btn-prod" ><i class="icon-search"></i>OK</button>
                    </div>
                </div>
            </div>
        </div><br/>
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-lg-5">
                        <div class="searchproduct">
                            <table class="table table-striped table-bordered" cellspacing="0">
                                <?php
                                if (!empty($this->arrStatistic)):
                                    foreach ($this->arrStatistic as $row):
                                        ?>
                                        <tr>
                                        <input type="hidden" value="<?php echo $row['slug'] ?>" id="<?php echo $row['slug'] ?>">
                                        <th style="text-align:left"><?php echo $row['name'] ?></th>
                                        <th style="text-align:center;">
                                            <?php
                                            echo $row['total']
                                            ?>
                                        </th>
                                        <th style="text-align:center">
                                            <a href="#<?php echo $row['slug'] ?>" class="btn btn-primary btn-xs <?php echo $row['slug'] ?>"><i class="icon-eye-open"></i> Xem</a>
                                        </th>
                                        </tr>
                                        <?php
                                    endforeach;
                                endif;
                                ?>
                            </table>
                        </div>
                    </div>
                    <div class="col-lg-7">
                        <div class="show-prod"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>

    function loadPage(page, action) {
        if (action == 'getproduct' || action == 'searchproduct')
            $('.' + action).load(baseurl + '/backend/tags/' + action + '/page/' + page, {tags_id: tags_id, search_name: search_product});
    }
    ;
    Statistic.index();
</script>