<section class="panel">
    <header class="panel-heading">Doanh số bán hàng của từng nhân viên</header>
    <div class="panel-body">
        <div class="row">
            <div class="form-group">
                <div class="col-md-offset-6 col-md-6">
                    <div class="col-sm-8">
                        <div class="input-group input-large" data-date-format="dd/mm/yyyy">
                            <input type="text" class="form-control dpd1" id="from" value="<?php echo $this->date['from'] ?>">
                            <span class="input-group-addon">To</span>
                            <input type="text" class="form-control dpd2" id="to" value="<?php echo $this->date['to'] ?>">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <button type="button" class="btn btn-white per-100 btn-daterandge" ><i class="icon-search"></i>OK</button>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-lg-12">
                <div class="searchproduct">
                    <table class="table table-striped table-bordered" cellspacing="0">
                        <thead>
                            <tr>
                                <th style="text-align:center;width:7%">ID User</th>
                                <th style="text-align:center;width:20%">Tên User</th>
                                <th style="text-align:center;width:20%" class="numeric">Tổng doanh thu</th>
                                <th style="text-align:center;width:20%">Đã thu</th>
                                <th style="text-align:center;width:20%">Chưa thu</th>
                                <th style="text-align:center;width:10%">Chức năng</th>
                            </tr>
                        </thead>
                        <tbody>

                            <?php
                            if ($this->arrReven) {
                                foreach ($this->arrReven as $reven) {
                                    ?>
                                    <tr>
                                        <td style="text-align: center"><?php echo $reven['user_updated']; ?></td>
                                        <td style="text-align: left">
                                            <?php
                                            $user_id = $reven['user_updated'];
                                            if (isset($this->arrUser[$user_id]['user_fullname'])) {
                                                echo $this->arrUser[$user_id]['user_fullname'];
                                            }
                                            ?> 
                                        </td>
                                        <td><?php echo number_format($reven['total']); ?></td>
                                        <td><?php echo number_format($reven['pay']); ?></td>
                                        <td><?php echo number_format($reven['notPay']); ?></td>
                                        <td class="numeric text-center visible-xs visible-sm visible-md visible-lg" width="200">
                                            <a href="<?php echo $this->serverUrl() . $this->Url('backend-order-search', array('controller' => 'order', 'action' => 'index', 'Sales' => $reven['user_updated'], 'date_from' => $this->date['from'], 'date_to' => $this->date['to'])) ?>" target="_bank"  class="btn btn-primary btn-xs"><i class="icon-eye-open"></i> Xem</a>
                                        </td>
                                    </tr>
                                    <?php
                                }
                                $total = 0;
                                $pay = 0;
                                $nopay = 0;
                                foreach ($this->arrReven as $reven) {
                                    $total += (int) $reven['total'];
                                    $pay += (int) $reven['pay'];
                                    $nopay += (int) $reven['notPay'];
                                }
                                ?>
                                <tr style="color: red; font-size: 18px; font-weight: 700">
                                    <td colspan="2" style="text-align: center">Tổng tiền:</td>
                                    <td style="text-align: left"><?php echo number_format($total) ?></td>
                                    <td style="text-align: left"><?php echo number_format($pay) ?></td>
                                    <td style="text-align: left"><?php echo number_format($nopay) ?></td>
                                    <td style="text-align: left"></td>
                                </tr>
                            <?php } else {
                                ?>
                                <tr class="none-product">
                                    <td colspan="6" style="text-align:center;">Chưa có đơn hàng trong ngày này.</td>
                                </tr>
                            <?php } ?>

                        </tbody>
                    </table>
                    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12" >
                        <?php //echo $this->paging;  ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    Statistic.index();
</script>