<?php
$arrDetailCategory = $this->arrDetailCategory;
?>
<div id="brcmb">
    <?php
    $tmpCount = 0;
    foreach ($this->arrGrade as $key => $value) :
        $tmpCount+=1;
        if ($tmpCount < count($this->arrGrade)):
            ?>
            <a href="<?php echo $this->serverUrl() . $this->Url('category', array('controller' => 'category', 'action' => 'index', 'categorySlug' => $value['cate_slug'], 'categoryID' => $value['cate_id'])) ?>">
                <span><?php echo $value['cate_name']; ?></span>
            </a> > 
            <?php
        endif;
    endforeach;
    ?>

</div>
<div id="cont">
    <div class="box">
        <div class="tt">
            <h1  class="tt"><?php echo $this->arrDetailCategory['cate_name']; ?></h1>
        </div>
        <?php if (!empty($this->arrCategoryChildrenList)):
            ?>
            <div class="ls-cat">     
                <div class="ls">
                    <ul>
                        <?php
                        foreach ($this->arrCategoryChildrenList as $key => $value):
                            if ($value['cate_id'] != $arrDetailCategory['cate_id']):
                                ?>
                                <li><a href="<?php echo $this->serverUrl() . $this->Url('category', array('controller' => 'category', 'action' => 'index', 'categorySlug' => $value['cate_slug'], 'categoryID' => $value['cate_id'])) ?>"><?php echo $value['cate_name']; ?></a></li>
                                <?php
                            endif;
                        endforeach;
                        ?>
                    </ul>
                </div>
            </div>
        <?php endif; ?>
        <?php if (!empty($this->arrTopview)): ?>
            <div class="sld">
                <div class="sw-cont">
                    <div class="swiper-wrapper">
                        <?php
                        foreach ($this->arrTopview as $key => $value):
                            ?>
                            <div class="swiper-slide"><a href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $value['prod_slug'], 'productId' => $value['prod_id'])) ?>"><img src="<?php echo json_decode($value['prod_image'], true)['thumbImage']['83x83'] ?>" title="<?php echo $value['prod_name']; ?>" style="width: 100%"/></a></div>
                        <?php endforeach; ?>
                    </div>
                    <div class="swiper-button-next"></div>
                    <div class="swiper-button-prev"></div>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <?php if (!empty($this->arrProductList)): ?>
        <div class="ls-pro full-title">               
            <div class="ls">
                <ul>
                    <?php foreach ($this->arrProductList as $key => $value): ?>
                        <li>
                            <div class="f-l img">
                                <a href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $value['prod_slug'], 'productId' => $value['prod_id'])) ?>" rel="nofollow"><img src="<?php echo json_decode($value['prod_image'], true)['thumbImage']['83x83']; ?>"/></a>
                            </div>
                            <?php if ($value['prod_call_price'] == 1): ?>
                                <div class="inf">
                                    <div  class="tt"><a href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $value['prod_slug'], 'productId' => $value['prod_id'])) ?>"><?php echo $value['prod_name']; ?></a></div>
                                    <div class="cr-price">Liên hệ để biết giá</div>
                                </div>
                            <?php else: ?>
                                <div class="inf">
                                    <div  class="tt"><a href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $value['prod_slug'], 'productId' => $value['prod_id'])) ?>"><?php echo $value['prod_name']; ?></a></div>
                                    <?php if ($value['prod_is_promotion'] == 1): ?><div class="op-price"><?php echo number_format($value['prod_price'], 0, ",", "."); ?> Vnđ</div><?php endif; ?>
                                    <div class="cr-price"><?php echo ($value['prod_is_promotion'] == 1) ? number_format($value['prod_promotion_price'], 0, ",", ".") : number_format($value['prod_price'], 0, ",", "."); ?> Vnđ</div>
                                    <?php if ($value['prod_is_promotion'] == 1): ?>
                                        <div class="percen">
                                            <?php
                                            $percent = 100 - ($value['prod_promotion_price'] * 100 / $value['prod_price']);
                                            echo $percent;
                                            ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                            <div class="clear"></div>
                        </li>  
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <?php
        if ($this->countPage > 1):
            if ($this->intPage < $this->countPage):
                ?>
                <div class="button"><a href="<?php echo $this->serverUrl() . $this->Url('category', array('controller' => 'category', 'action' => 'index', 'categorySlug' => $this->arrDetailCategory['cate_slug'], 'categoryID' => $this->arrDetailCategory['cate_id'], 'page' => ($this->intPage + 1))) ?>"><button class="readmore">Xem Thêm</button></a></div>
                <?php
            endif;
            if ($this->intPage > 1):
                ?>
                <div class="button"><a href="<?php echo $this->serverUrl() . $this->Url('category', array('controller' => 'category', 'action' => 'index', 'categorySlug' => $this->arrDetailCategory['cate_slug'], 'categoryID' => $this->arrDetailCategory['cate_id'], 'page' => ($this->intPage - 1))) ?>"><button class="back bt-default">Trở Về</button></a></div>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
    <div class="desc-cate">      
        <?php
        $description = $this->arrDetailCategory["cate_description"];
        if (!empty($params['brand'])) {
            $description = $linkCateBrand["link_description"];
        }
        if (empty($description)) {
            $description = '<strong>Megavita - Nơi mua sắm <strong>' . $this->arrDetailCategory['cate_name'] . '</strong> hàng đầu tại Việt Nam</strong><br/>
Việc mua hàng trực tuyến mang đến cho bạn sự tiện lợi cũng như là đa dạng hơn cùng với những ưu đãi hấp dẩn chi người tiêu dùng. Thế nhưng khá nhiều người tiêu dùng Việt Nam lại chưa tận hưởng được những tiện ích của việc mua hàng online.
<br/><br/>
Hiểu được nhu cầu của thị trường, Megavita.vn được thành lập để trở thành cầu nối giúp khách hàng dễ dàng tìm kiếm một nhà cung cấp đáng tin cậy với các loại mỹ phẩm, thực phẩm chức năng chính hãng, chất lượng bảo đảm. Tất cả sản phẩm <strong>' . $this->arrDetailCategory['cate_name'] . '</strong> của Megavita.vn đều được nhập khẩu chính hãng 100% từ thương hiệu danh tiếng <strong>' . $this->mainBrand['cate_name'] . '</strong>
<br/><br/>
Megavita.vn cam kết chỉ bán hàng <strong>' . $this->arrDetailCategory['cate_name'] . '</strong> chính hãng và chất lượng tốt từ thương hiệu <strong>' . $this->mainBrand['cate_name'] . '</strong> Tuyệt đối nói không với hàng giả, hàng chất lượng kém. Ngoài ra quý khách còn được miễn phí giao hàng tận nhà sản phẩm <strong>' . $this->arrDetailCategory['cate_name'] . '</strong> đến từ thương hiệu <strong>' . $this->mainBrand['cate_name'] . '</strong> trên mọi tỉnh thành khắp toàn quốc – đây là điều chỉ những nhà bán hàng biết nghĩ đến lợi ích của khách hàng mới có thể thực hiện được.';
        }

        echo (trim($description) != "") ? '<div class="cate-content">' . html_entity_decode($description) . ' </div>' : '';
        ?>
    </div>

    <div class="tags">
        <?php if (!empty($this->arrTags) || !empty($this->listKeyword)) { ?>
            <div class="tag-content">
                <div class="main">
                    <?php
                    if (!empty($this->arrTags)):
                        $i = 0;
                        foreach ($this->arrTags as $key => $value):
                            ?>
                            <a href="<?php echo $this->serverUrl() . $this->Url('tags', array('controller' => 'Tags', 'action' => 'index', 'tagsSlug' => $value["tags_slug"], 'tagsID' => $value["tags_id"])) ?>"><?php echo $value['tags_name']; ?></a>
                            <?php
                            $i++;
                            if (count($this->arrTags) != $i)
                                echo ',';
                            ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php if (!empty($this->listKeyword)): ?>
                        <?php
                        foreach ($this->listKeyword as $word) {
                            $url = $this->serverUrl() . $this->Url('frontend-search', array('controller' => 'search', 'action' => 'index', 'keySlug' => $word['word_slug']));
                            ?>
                            <a href="<?php echo $url ?>"> <?php echo $word['word_key']; ?> </a>
                            <?php
                            echo '&nbsp';
                        }
                        ?>
                    <?php endif ?>
                </div>
            </div>
            <?php if ((count($this->arrTags) + count($this->listKeyword)) >= 10): ?>
                <div class="open-tag"><a href="javascript:;">Xem nhiều hơn</a></div>
            <?php endif; ?>
        <?php } ?>
    </div>


    <div class="seo-data">
        <?php foreach ($this->arrAllBrandList as $value): ?>
            <a href="<?php echo $this->serverUrl() . $this->Url('category', array('categorySlug' => $this->arrDetailCategory['cate_slug'], 'categoryID' => $this->arrDetailCategory['cate_id'], 'brand' => $value["cate_slug"], 'action' => 'index')) ?>"><?php echo $this->arrDetailCategory['cate_name'] . ' ' . $value['cate_name']; ?></a>, 
        <?php endforeach; ?>
    </div>
</div>