
<?php ?>
<section class="wrapper site-min-height">
<?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-times-sign"></i> Lỗi!</h4>
    <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-edit-general')->getMessages(), $this->flashMessenger()->setNamespace('success-edit-general')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php
endif;
$param = $this->params;
?>

    <div class="row">
        <div class="col-lg-12">
            <section class="panel panel-primary">
                <div class="row">
                    <div class="col-lg-12">
                        <section class="panel panel-primary">
                            <header class="panel-heading">Sửa general</header>
                            <div class="panel-body">
                                <form method="POST" role="form" class="form-horizontal tasi-form" id="frm" novalidate="novalidate" enctype="multipart/form-data">
                                    <div class="col-lg-12">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label for="gene_title" class="col-lg-2 col-sm-2 control-label" value="">Nhập tiêu đề</label>
                                                <div class="col-lg-10">
                                                    <input type="text" value="<?php echo $this->generalDetail['gene_title'] ?>" placeholder="Nhập tiêu đề" class="form-control" name="gene_title" id="gene_title">
                                                    <input type="hidden" value="<?php echo $this->generalDetail['gene_type'] ?>" name="gene_type">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="gene_code" class="col-lg-2 col-sm-2 control-label" value="">Code</label>
                                                <div class="col-lg-10">
                                                    <input readonly type="text" value="<?php echo $this->generalDetail['gene_code'] ?>" placeholder="Nhập code" class="form-control" name="gene_code" id="cont_title">
                                                    <input type="hidden" name="user_id" value="<?php echo UID ?>">
                                                </div>
                                            </div>
<?php if ($this->generalDetail['gene_type'] == 1 || $this->generalDetail['gene_type'] == 2) { ?>                                                  
                                                <div class="form-group">
                                                    <label for="gene_content" class="col-lg-2 col-sm-2  control-label">Chi tiết nội dung</label>
                                                    <div class="col-sm-10">
                                                        <textarea rows="20" value="" name="gene_content" class="form-control editor">
    <?php echo $this->generalDetail['gene_content'] ?>
                                                        </textarea>
                                                    </div>
                                                </div>
<?php } else {
    ?>
                                                <div class="form-group">
                                                    <label for="gene_content" class="col-lg-2 col-sm-2 control-label" value="">Chi tiết nội dung</label>
                                                    <div class="col-lg-10">
                                                        <input type="text" value="<?php echo $this->generalDetail['gene_content'] ?>" placeholder="Nhập nội dung" class="form-control" name="gene_content" id="cont_title">

                                                    </div>
                                                </div>
<?php } ?>
                                            <div class="form-group">
                                                <label for="gene_status" class="col-lg-2 control-label">Trạng thái</label>
                                                <div class="col-lg-3">
                                                    <select class="form-control sumo-select-box" id="cont_status" name="gene_status">    
                                                        <option value="1" <?php echo ($this->generalDetail['gene_status'] == 1) ? 'selected' : ''; ?>>Hiện</option>
                                                        <option value="0" <?php echo ($this->generalDetail['gene_status'] == 0) ? 'selected' : ''; ?>>Ẩn</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="col-lg-offset-2 col-lg-10">
                                                    <button type="submit" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                                                    <button type="submit" id="done" class="btn btn-success bt-save" name="save_close"><i class="icon-save"></i> Lưu & Thoát</button> 
                                                    <input value="0" name="is_close" class="is_close" type="hidden" />                                        
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </section>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    General.index();
</script>
