<?php
$arrUserList = $this->arrUserList;
?>
<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-edit-general')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>
    <section class="panel">
        <header class="panel-heading">
            Danh sách general
        </header>
        <div class="panel-body">    
            <div class="adv-table editable-table ">  
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">                  

                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                        <form id="frm" class="form-horizontal" role="form" method="GET">
                            <div class="row">
                                <div class="col-lg-9 col-sm-9 col-md-9 col-xs-8">
                                    <div class="dataTables_filter no-padding per-100">
                                        <label><input  name="s"  value="<?php echo $this->params["s"]; ?>" type="text" aria-controls="editable-sample" class="per-100 input-seaching form-control medium"></label>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-4">
                                    <button type="submit" class="btn btn-white per-100" ><i class="icon-search"></i> Tìm kiếm</button>
                                </div>
                            </div>                            
                        </form>
                    </div>
                </div>
                <section id="unseen">
                    <table class="table table-bordered table-striped table-condensed cf">
                        <thead class="cf">
                            <tr>
                                <th class="text-center"><i class="icon-list"></i> ID</th>
                                <th class="visible-lg visible-sm visible-md visible-xs"><i class="icon-list-alt"></i> Tiêu đề</th>
                                <th class="text-center hidden-xs"><i class="icon-list-alt"></i> Code</th>
                                <th class="text-center visible-lg visible-sm visible-md visible-xs"><i class="icon-ok"></i> Loại</th>
                                <th class="text-center"><i class="icon-check"></i> Trạng thái </th>
                                <th class="text-center hidden-xs hidden-sm"><i class="icon-check"></i> Người cập nhật </th>
                                <th class="text-center visible-lg visible-sm visible-md visible-xs"><i class="icon-edit"></i> Chức năng</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if ($this->arrGeneralList):
                                foreach ($this->arrGeneralList as $arrGeneralList):
                                    ?>
                                    <tr>
                                        <td  class="text-center" width="80">
                                            <?php echo $arrGeneralList['gene_id']; ?>
                                        </td>
                                        <td class="visible-lg visible-sm visible-md visible-xs">
                                            <?php echo $arrGeneralList['gene_title']; ?>
                                        </td>
                                        <td class="hidden-xs" width="200">
                                            <?php echo $arrGeneralList['gene_code']; ?>
                                        </td>
                                        <td  class="text-center visible-lg visible-sm visible-md visible-xs" width="150">
                                            <?php
                                            switch ($arrGeneralList['gene_type']) {
                                                case 0: echo "text";
                                                    break;
                                                case 1: echo "văn bản";
                                                    break;
                                                case 2: echo "Keyword";
                                                    break;
                                                default: echo "không xác đinh";
                                            }
                                            ?>
                                        </td>
                                        <td  class="text-center"><?php if ($arrGeneralList['gene_status'] == 1): ?><a href="javascript:;" class="tooltips" data-placement="top" data-original-title="Đang hiện"><i class="icon-ok color-success"></a><?php endif;
                                    if ($arrGeneralList['gene_status'] == 0):
                                                ?><a href="javascript:;" class="tooltips" data-placement="top" data-original-title="Đang ẩn"><i class="icon-minus-sign color-danger"></i></a><?php endif; ?></td>
                                        <td class="hidden-xs hidden-sm numeric productCreated text-center">
                                            <?php
                                            $user_id = ($arrGeneralList['user_updated'] == NULL) ? 0 : $arrGeneralList['user_updated'];
                                            if (isset($arrUserList[$user_id]['user_fullname'])) {
                                                echo $arrUserList[$user_id]['user_fullname'];
                                            } else
                                                echo "Chưa có người cập nhật"
                                                ?> 
                                        </td>
                                        <td class="text-center visible-lg visible-sm visible-md visible-xs" width="200">
                                            <a  href="<?php echo $this->serverUrl() . $this->Url('general', array('controller' => 'general', 'action' => 'index', 'code' => $arrGeneralList['gene_code'], 'id' => $arrGeneralList['gene_id'])); ?>" target="_bank"  class="btn btn-primary btn-xs"><i class="icon-eye-open"></i> Xem</a>
                                            <a  href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'general', 'action' => 'edit', 'id' => $arrGeneralList['gene_id'])); ?>"  class="btn btn-primary btn-xs  edit" data-placement="top" data-original-title="Sửa danh mục"  rel="<?php echo $arrGeneralList['gene_id'] ?>"><i class="icon-pencil"></i> Sửa</a>
                                            <!--<a  class="btn btn-danger btn-xs remove tooltips" data-placement="top" data-original-title="Xóa general" rel="<?php echo $arrGeneralList['gene_id'] ?>"><i class="icon-trash "></i> Xóa</a>-->
                                        </td>
                                    </tr>

                                <?php endforeach; ?>
                            <?php else: ?>
                                <tr><td colspan="6" class="text-center">Hiện tại chưa có general nào.</td></tr>
<?php endif; ?>
                        </tbody>
                    </table>
                </section>
            </div>
            <div>
                <div class="row">
                    <div  class="col-lg-6 col-sm-12 col-md-12 col-xs-12">
                        <div class="form-group">
                            <div  class="col-sm-3 col-lg-3 col-md-3">
                                <select name="limit" class="form-control" onchange="window.location.href = this.value">
                                    <option value="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'general', 'action' => 'index', 'limit' => 15, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 15 ? "selected" : "" ?>>15</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'general', 'action' => 'index', 'limit' => 30, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 30 ? "selected" : "" ?>>30</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'general', 'action' => 'index', 'limit' => 100, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 100 ? "selected" : "" ?>>100</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'general', 'action' => 'index', 'limit' => 300, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 300 ? "selected" : "" ?>>300</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'general', 'action' => 'index', 'limit' => 500, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 500 ? "selected" : "" ?>>500</option>
                                    <option value ="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'general', 'action' => 'index', 'limit' => 1000, 's' => $this->params["s"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 1000 ? "selected" : "" ?>>1000</option>
                                </select>
                            </div>
                            <div class = "col-sm-3" style = "padding-top: 10px">Dòng</div>
                        </div>
                    </div>
                    <div class = "col-lg-6">
                        <?php echo $this->paging;
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
</section>
<script type="text/javascript">
    General.del();
</script>