<?php
$arrRole = $this->arrRole;
?>
<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-times-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-messenge')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>
    <section class="panel">
        <header class="panel-heading">Thêm phí vận chuyển mới</header>
        <div class="panel-body">

            <form id="frm" class="form-horizontal tasi-form" role="form" method="POST">
                <div class="form-group">
                    <label  class="col-lg-2 control-label">Tỉnh / Thành <span style="color:red">*</span></label>
                    <div class="col-lg-10">
                        <select name="city" id="city" class="selectbox selectpicker" data-live-search="true" title="Chọn một thành phố">
                            <?php foreach ($this->arrCityList as $arrCity): ?>
                                <option value="<?php echo $arrCity['city_id']; ?>" <?php echo $this->params['city'] == $arrCity['city_id'] ? "selected" : ''; ?>><?php echo $arrCity['city_name']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label  class="col-lg-2 control-label">Quận / Huyện <span style="color:red"></span></label>
                    <div class="col-lg-10">
                        <select name="district" id="district" class="form-control selectbox" data-live-search="true">
                            <option value="">=== Chọn quận huyện ===</option>
                            <?php
                            if (!empty($this->arrDistrictList)):
                                foreach ($this->arrDistrictList as $key => $arrDistrict) {
                                    ?>
                                    <option value="<?php echo $arrDistrict['dist_id']; ?>" <?php echo $this->params['district'] == $arrDistrict['dist_id'] ? "selected" : ''; ?>><?php echo $arrDistrict['dist_name']; ?></option>
                                    <?php
                                }
                            endif;
                            ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-2 col-sm-2 control-label" for="birthdate">Số tiền shipping</label>
                    <div class="col-lg-10">
                        <input id="birthdate" name="ship_fee" class="form-control" type="text" placeholder="Vui lòng số tiền shipping" value="<?php echo $this->params['ship_fee'] ? $this->params['ship_fee'] : ''; ?>">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                        <button type="submit" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                        <button type="submit" id="done" class="btn btn-success bt-save" name="save_close"><i class="icon-save"></i> Lưu & Thoát</button> 
                        <input value="0" name="is_close" class="is_close" type="hidden" />
                    </div>
                </div>

            </form>
        </div>

    </section>
</section>
<script type="text/javascript">
    Shipping.index();
</script>
