<div id="content">
    <div class="block-head">
        <?php echo $this->render('frontend/menu'); ?>

        <div class="breadcrumb">
            <div class="br-hidden">
                <div class="item item-end">
                    <div class="ar-right">
                        <div class="cont">
                            <a href="<?php echo $this->serverUrl() ?>">Trang chủ</a>
                        </div>
                    </div>
                </div>
                <div class="item  active">
                    <div class="ar-right">
                        <div class="cont">
                            Xác nhận Đổi mật khẩu 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div style="clear: both;"></div>
    </div>
    <div id="cont-resetpass">
        <?php if ($this->errors): ?>
            <div class="alert alert-block alert-danger fade in">
                <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
                <?php foreach ($this->errors as $error): ?>
                    <p> - <?php echo $error; ?></p>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
        <?php if ($this->success):
            ?>
            <div class="alert alert-success alert-block fade in">
                <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
                <p>- <?php echo $this->success; ?></p>
            </div>
        <?php endif; ?>
        <?php if (!$this->success): ?>
            <form method="POST">
                <table width="100%">
                    <tr>
                        <td class="text-right">Mật khẩu mới:</td>
                        <td>
                            <input type="password" name="strPassword"/>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-right">Nhắc lại mật khẩu</td>
                        <td>
                            <input type="password" name="strRePassword">
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" class="text-right">                           
                            <button class="btn-pre" type="submit">  ĐỒNG Ý  </button>
                        </td>
                    </tr>
                </table>
            </form>
        <?php endif; ?>
    </div>
    <div style="clear: both;"></div>
</div>