<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-brand')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>

    <div class="row" id="frmAddCity">
        <div class="col-lg-12">
            <section class="panel panel-primary">
                <header id="frmTitle" class="panel-heading">Thêm Thương hiệu</header>
                <div class="panel-body">
                    <form id="frm" role="form" class="form-horizontal tasi-form" method="POST">
                        <div class="form-group">
                            <label class="col-lg-2 control-label"> Tên Thương hiệu</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="brandName" placeholder="Nhập tên Thương hiệu" value="<?php echo $this->params['brandName'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="brandSlug" class="col-lg-2 control-label">URL</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="brandSlug" placeholder="Nhập URL" value="<?php echo $this->params['brandSlug'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="brandSort" class="col-lg-2 control-label">Độ ưu tiên</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="brandSort" placeholder="Nhập Độ ưu tiên" value="<?php echo $this->params['brandSort'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="brandStatus" class="col-lg-2 col-md-2 col-sm-2 col-sm-2 control-label" value="">Tình trạng</label>
                            <div class="col-lg-10 col-md-10 col-sm-10 tabselect" tabindex= "3">
                                <select name="brandStatus" class="multi-select form-control sumo-select-box">
                                    <option value="1">Hiển thị</option>
                                    <option value="0">Ẩn</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="brandDescription" class="col-lg-2 control-label">Mô tả ngắn về Thương hiệu</label>
                            <div class="col-lg-10 textedit" tabindex="4" >
                                <textarea rows="6" name="brandDescription" id="Sumary" class="form-control editor" style=""><?php echo $this->params['brandDescription']; ?></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for=brandMetaTitle" class="col-lg-2 control-label">SEO Meta Title</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="brandMetaTitle" placeholder="Nhập SEO Meta Title" value="<?php echo $this->params['brandMetaTitle'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="brandMetaKeyword" class="col-lg-2 control-label">SEO Meta Keyword</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="brandMetaKeyword" placeholder="Nhập SEO Meta Keyword" value="<?php echo $this->params['brandMetaKeyword'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="brandMetaDescription" class="col-lg-2 control-label">SEO Meta Description</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="brandMetaDescription" placeholder="Nhập SEO Meta Description" value="<?php echo $this->params['brandMetaDescription'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="brandMetaSocial" class="col-lg-2 control-label">SEO Meta Social</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="brandMetaSocial" placeholder="Nhập SEO Meta Social" value="<?php echo $this->params['brandMetaSocial'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-offset-3 col-lg-10">
                                <button type="button" onclick="document.getElementById('frm').submit();" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                                <button type="button" onclick="document.getElementById('frm').submit();" id="done" class="btn btn-success bt-save" name="save_close"><i class="icon-save"></i> Lưu & Thoát</button> 
                                <input value="0" name="is_close" class="is_close" type="hidden" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
</section>
<script>
    Brand.index();
</script>