<?php
$arrBrand = $this->arrBrand;
?>
<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-edit-brand')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>

    <div class="row" id="frmAddCity">
        <div class="col-lg-12">
            <section class="panel panel-primary">
                <header id="frmTitle" class="panel-heading">Chỉnh sửa Thương hiệu</header>
                <div class="panel-body">
                    <form id="frm" role="form" class="form-horizontal tasi-form" method="POST">
                        <div class="form-group">
                            <label class="col-lg-2 control-label"> Tên Thương hiệu</label>
                            <div class="col-lg-9">
                                <input class="form-control" type="text" name="brandName" value = "<?php echo $this->params['brandName'] ? $this->params['brandName'] : $arrBrand['bran_name']; ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="brandSlug" class="col-lg-2 control-label">URL</label>
                            <div class="col-lg-9">
                                <input class="form-control" type="text" name="brandSlug" placeholder="Nhập URL" value="<?php echo $this->params['brandSlug'] ? $this->params['brandSlug'] : $arrBrand['bran_slug']; ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="brandSort" class="col-lg-2 control-label">Độ ưu tiên</label>
                            <div class="col-lg-9">
                                <input class="form-control" type="text" name="brandSort" value="<?php echo $this->params['brandSort'] ? $this->params['brandSort'] : $arrBrand['bran_sort']; ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="brandStatus" class="col-lg-2 col-sm-2 control-label" value="">Trạng thái</label>
                            <div class="col-lg-10">
                                <select name="brandStatus" class="multi-select form-control sumo-select-box">
                                    <option value="1" <?php if ($arrBrand['bran_status'] == 1): ?>selected="selected"<?php endif; ?>>Hiển thị</option>
                                    <option value="0" <?php if ($arrBrand['bran_status'] == 0): ?>selected="selected"<?php endif; ?>>Ẩn</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="brandDescription" class="col-lg-2 control-label">Mô tả ngắn về Danh mục</label>
                            <div class="col-lg-10">
                                <textarea rows="6" name="brandDescription" id="Sumary" class="form-control editor" style=""><?php echo isset($this->params["brandDescription"]) ? $this->params["brandDescription"] : $arrBrand["bran_description"]; ?></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="brandMetaTitle" class="col-lg-2 control-label">SEO Meta Title</label>
                            <div class="col-lg-9">
                                <input class="form-control" type="text" name="brandMetaTitle" placeholder="Nhập SEO Meta Title" value ="<?php echo $arrBrand['bran_meta_title'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="brandMetaKeyword" class="col-lg-2 control-label">SEO Meta Keyword</label>
                            <div class="col-lg-9">
                                <input class="form-control" type="text" name="brandMetaKeyword" placeholder="Nhập SEO Meta Keyword" value ="<?php echo $arrBrand['bran_meta_keyword'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="brandMetaDescription" class="col-lg-2 control-label">SEO Meta Description</label>
                            <div class="col-lg-9">
                                <input class="form-control" type="text" name="brandMetaDescription" placeholder="Nhập SEO Meta Description" value ="<?php echo $arrBrand['bran_meta_description'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="bradMetaSocial" class="col-lg-2 control-label">SEO Meta Social</label>
                            <div class="col-lg-9">
                                <input class="form-control" type="text" name="bradMetaSocial" placeholder="Nhập SEO Meta Social" value ="<?php echo $arrBrand['bran_meta_social'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-offset-3 col-lg-10">
                                <button type="submit" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                                <button type="submit" id="done" class="btn btn-success bt-save" name="save_close"><i class="icon-save"></i> Lưu & Thoát</button> 
                                <input value="0" name="is_close" class="is_close" type="hidden" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <?php
            $successMessage = $this->flashMessenger()->setNamespace('success-delete-cate-prod')->getMessages();
            $errorMessage = $this->flashMessenger()->setNamespace('error-delete-cate-prod')->getMessages();
            if ($successMessage) {
                ?>
                <div class="alert alert-success alert-block fade in">
                    <button class="close close-sm" type="button" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>
                    <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
                    <p>- <?php echo current($successMessage); ?></p>
                </div>
            <?php } ?>
            <?php
            if ($errorMessage) {
                ?>
                <div class="alert alert-danger alert-block fade in">
                    <button class="close close-sm" type="button" data-dismiss="alert">
                        <i class="icon-remove"></i>
                    </button>
                    <h4><i class="icon-ok-sign"></i> Thất bại!</h4>
                    <p>- <?php echo current($errorMessage); ?></p>
                </div>
            <?php } ?>
            <section class="panel panel-primary">
                <header id="" class="panel-heading">Danh sách sản phẩm trong danh mục</header>
                <div class="panel-body">
                    <div class="row">
                        <form id="frm_addprod">
                            <div class="col-lg-10" id="result">
                                <input class="form-control" id="contentId" name="contentTag" type="text">
                            </div>
                            <div class="col-lg-2">
                                <a class="btn btn-primary" onclick="addProduct()"><i class="icon-plus-sign-alt"></i> Thêm</a>
                            </div>
                        </form>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <strong class="text-danger get-error"></strong>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <p>Vui lòng nhập ID Sản phẩm để thêm Sản phẩm vào Danh mục</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-3">
                            <a onclick="refresh()" class="btn btn-primary" data-placement="top" data-original-title="Cập nhật">
                                <i class="icon-refresh"></i> Làm mới
                            </a>
                            <a onclick="deleteProduct(<?php echo $this->params['id']; ?>, '', 1)" class="btn btn-danger remove tooltips" data-placement="top" data-original-title="Xóa sản phẩm">
                                <i class="icon-trash "></i> Xóa
                            </a>
                        </div>
                    </div>
                </div>
                <br>
                <div class="row listProducts">

                </div>
        </div>
</section>


</div>
</div>
</section>
<script>
    var id_cate = <?php echo $this->params['id']; ?>;
    $('.listProducts').load(baseurl + '/backend/category/product', {id_cate: id_cate});
    $('#contentId').tagsInput({
        autocomplete_url: baseurl + '/backend/category/select-product?id=' + id_cate,
        autocomplete: {selectFirst: true, width: '100px', autoFill: false}
    });
    Category.index();
</script>