<section class="wrapper site-min-height">
    <section class="panel">
        <header class="panel-heading">
            Danh sách tin nhắn
        </header><br>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-4">                  
                    <div id="editable-sample_length" class="dataTables_length no-padding">
                        <a class="btn btn-danger delete-all" href="javascript:;" ><i class="icon-trash "></i> Xóa</a>
                        <?php if (!empty($per["message"]["messall"]) || FULL_ACCESS == true): ?>
                        <a class="btn btn-primary" href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'message', 'action' => 'messall')); ?>" ><i class="icon-eye-open"></i> Xem tất cả</a>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4"> 
                </div>
                <form id="frm" class="form-horizontal" role="form" method="GET">
                    <div class="col-lg-4 col-md-4 col-sm-4">   
                        <div data-date-format="dd/mm/yyyy" data-date="" class="input-group input-large">
                            <input type="text" name="date_from" class="form-control dpd1" placeholder="Từ ngày" value="<?php echo empty($this->params['date_from']) ? date('d/m/Y', (time() - (60 * 60 * 24 * 30))) : $this->params['date_from']; ?>">
                            <span class="input-group-addon">Đến</span>
                            <input type="text" name="date_to" class="form-control dpd2" placeholder="Ðến ngày" value="<?php echo empty($this->params['date_to']) ? date('d/m/Y', time()) : $this->params['date_to']; ?>">
                        </div>
                    </div>
                    <div class="col-lg-2 col-sm-8 col-md-8 col-xs-12 floatRight">
                        <button type="submit" class="btn btn-white per-100"><i class="icon-search"></i> Tìm kiếm</button>
                    </div>
                </form>
            </div>
            <br>
                <section id="unseen">
                    <table class="table table-bordered table-striped table-condensed cf">
                        <thead class="cf">
                            <tr>
                                <th class="text-center"> #</th>
                                <th class="text-center"><i class="icon-ok"></i> Tiêu đề</th>
                                <th class="text-center visible-xs visible-md visible-sm visible-lg"><i class="icon-list-alt"></i> Nội dung</th>
                                <th class="text-center"><i class="icon-ok"></i> Ngày tạo</th>
                                <th class="text-center"><i class="icon-ok"></i> Trạng thái</th>
                                <th class="text-center visible-xs visible-md visible-sm visible-lg"><i class="icon-edit"></i> Chức năng</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php 
                            if($this->arrListMessage){
                                foreach($this->arrListMessage as $key=>$list){
                                    $key ++;
                            ?>
                                    <tr>
                                        <td class="text-center data-id"><input type="checkbox" name="data-id[]" clas value="<?php echo $list['mess_id'] ?>"/></td>
                                        <td class="text-center"><?php echo $list['mess_title'] ?></td>
                                        <td class="text-left"><?php echo $list['mess_content'] ?></td>
                                        <td class="text-center"><?php echo date('d/m/Y',$list['mess_created']) ?></td>
                                        <td class="text-center">
                                            <?php 
                                            if($list['mess_status'] == 0){
                                                echo '<strong><span class="label label-warning tooltips" data-placement="top" data-original-title="Chưa xem ">Chưa xem </span></strong>';
                                            }else{
                                                echo '<i class="icon-ok color-success"></i>';
                                            }
                                            ?>
                                        </td>
                                        <td class="text-center">
                                            <a rel="<?php echo $list['mess_id'] ?>" class="btn btn-primary btn-xs view-message" data-placement="top" data-original-title="Xem chi tiết"><i class="icon-eye-open"></i> Xem</a>
                                        </td>
                                    </tr>
                            <?php
                                }
                            }
                            ?>
                        </tbody>
                    </table>
                </section>
            </div>
            <div>
                <?php echo $this->paging; ?>
            </div>
        </div>
    </section>
</section>
<script type="text/javascript">
    Message.index();
</script>