<section class="wrapper site-min-height">
    <section class="panel">
        <header class="panel-heading">
            Danh sách tất cả tin nhắn
        </header>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-2 col-md-3 col-sm-4">                  
                    <div id="editable-sample_length" class="dataTables_length no-padding">
                        <a class="btn btn-danger delete-all" href="javascript:;" ><i class="icon-trash "></i> Xóa</a>
                    </div>
                </div>
            </div><br>
            <form id="frm" class="form-horizontal" role="form" method="GET">
                <div class="row">
                    <div class="col-lg-4 col-sm-8 col-md-8 col-xs-12">
                        <div class="col-lg-6 col-md-9 col-sm-9 col-xs-8 no-padding">
                        </div>
                        <div class="col-lg-6 col-md-9 col-sm-9 col-xs-8 no-padding">
                            <select name="type" class="selectbox selectpicker bs-select-hidden">
                                <option value="0" <?php if($this->params['type'] == 0): ?> selected <?php endif; ?>>Tất Cả</option>
                                <option value="1" <?php if($this->params['type'] == 1): ?> selected <?php endif; ?>>Ngày tạo</option>
                                <option value="2" <?php if($this->params['type'] == 2): ?> selected <?php endif; ?>>Ngày hẹn</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-8 col-md-8 col-xs-12">
                        <div data-date-format="dd/mm/yyyy" data-date="" class="input-group input-large">
                            <input type="text" name="date_from" class="form-control dpd1" placeholder="Từ ngày" value="<?php echo empty($this->params['date_from']) ? date('d/m/Y', (time() - (60 * 60 * 24 * 30))) : $this->params['date_from']; ?>">
                            <span class="input-group-addon">Đến</span>
                            <input type="text" name="date_to" class="form-control dpd2" placeholder="Ðến ngày" value="<?php echo empty($this->params['date_to']) ? date('d/m/Y', time()) : $this->params['date_to']; ?>">
                        </div>
                    </div>     
                    <div class="col-lg-4 col-sm-8 col-md-8 col-xs-12 floatRight">
                        <div class="col-lg-6 col-md-9 col-sm-9 col-xs-8 no-padding">
                            <div class="dataTables_filter no-padding per-100">
                                <select id="Sales_id" class="selectbox selectpicker"  multiple="multiple"  data-live-search="true" title="Sale xử lý">
                                    <?php
                                    if ($this->params['Sales']) {
                                        $SaleList = explode(',', $this->params['Sales']);
                                    }
                                    ?>
                                    <option value="0" <?php if (in_array(0, $SaleList)): ?> selected <?php endif; ?>>Chọn Tất cả</option>
                                    <?php foreach ($this->arrUserSaleList as $value): ?>
                                        <option value="<?php echo $value['user_id']; ?>" <?php if (in_array($value['user_id'], $SaleList)): ?> selected <?php endif; ?>><?php echo $value['user_fullname']; ?></option>
                                    <?php endforeach; ?>
                                </select>
                                <input type="hidden" name="Sales" id ="Sales" value="<?php echo $this->params['Sales'] ?>">
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-3 col-sm-3 col-xs-4 no-padding-right">
                            <button type="submit" class="btn btn-white per-100"><i class="icon-search"></i> Tìm kiếm</button>
                        </div>
                    </div>
                </div>
            </form><br>
                <section id="unseen">
                    <table class="table table-bordered table-striped table-condensed cf">
                        <thead class="cf">
                            <tr>
                                <th class="text-center"> #</th>
                                <th class="text-center visible-xs visible-md visible-sm visible-lg"><i class="icon-list-alt"></i> Nội dung</th>
                                <th class="text-center"><i class="icon-user"></i> Khách hàng</th>
                                <th class="text-center"><i class="icon-user"></i> User</th>
                                <th class="text-center"><i class="icon-list-alt"></i> Ngày tạo</th>
                                <th class="text-center"><i class="icon-ok"></i> Trạng thái</th>
                                <th class="text-center visible-xs visible-md visible-sm visible-lg"><i class="icon-edit"></i> Chức năng</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php 
                            if($this->arrListMessage){
                                foreach($this->arrListMessage as $key=>$list){
                                    $key ++;
                            ?>
                                    <tr>
                                        <td class="text-center data-id"><input type="checkbox" name="data-id[]" clas value="<?php echo $list['mess_id'] ?>"/></td>
                                        <td class="text-center"><?php echo $list['mess_title'] ?></td>
                                        <td class="text-left"><?php echo $list['mess_content'] ?></td>
                                        <td class="text-center"><?php echo $this->arrUserDetailList[$list['mess_user']]['user_fullname'] ?></td>
                                        <td class="text-center"><?php echo date('d/m/Y',$list['mess_created']) ?></td>
                                        <td class="text-center">
                                            <?php 
                                            if($list['mess_status'] == 0){
                                                echo '<strong><span class="label label-warning tooltips" data-placement="top" data-original-title="Chua xem ">Chua xem </span></strong>';
                                            }else{
                                                echo '<i class="icon-ok color-success"></i>';
                                            }
                                            ?>
                                        </td>
                                        <td class="text-center">
                                            <a href="<?php echo $list['mess_url'] ?>" rel="<?php echo $list['mess_id'] ?>" class="btn btn-primary btn-xs view-message" data-placement="top" data-original-title="Xem chi ti?t"><i class="icon-eye-open"></i> Xem</a>
                                        </td>
                                    </tr>
                            <?php
                                }
                            }
                            ?>
                        </tbody>
                    </table>
                </section>
            </div>
            <div>
                <?php echo $this->paging; ?>
            </div>
        </div>
    </section>
</section>
<script type="text/javascript">
    Message.index();
</script>