
<?php
$optionCategory = "";
foreach ($this->arrCategoryList as $cate) {
    if ($cate["cate_type"] == 0) {
        $optionMainCategory.= '<option ' . (($this->params["main_cate_id"] == $cate['cate_id']) ? "selected" : "") . ' value="' . $cate['cate_id'] . '" class="level-' . substr_count($cate['cate_grade'], ":") . '">' . $strSpace . $cate['cate_name'] . '</option>';
        $optionCategory.= '<option ' . ((in_array($cate['cate_id'], $this->params["cate_id"])) ? "selected" : "") . ' value="' . $cate['cate_id'] . '" class="level-' . substr_count($cate['cate_grade'], ":") . '">' . $strSpace . $cate['cate_name'] . '</option>';
    }
}
?>
<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-times-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = $this->flashMessenger()->setNamespace('success-add-content')->getMessages();
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
        <?php
    endif;
    $param = $this->params;
    ?>

    <div class="row">
        <div class="col-lg-12">
            <section class="panel panel-primary">
                <div class="row">
                    <div class="col-lg-12">
                        <section class="panel">
                            <header class="panel-heading">Thêm bài viết mới</header>
                            <div class="panel-body">
                                <form method="POST" role="form" class="form-horizontal tasi-form" id="frm" novalidate="novalidate" enctype="multipart/form-data">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="cont_title" class="col-lg-2 col-md-2 col-sm-2 control-label" value="">Tiêu đề bài viết</label>
                                            <div class="col-lg-10 col-md-10 col-sm-10">
                                                <input type="text" value="<?php echo $param['cont_title'] ?>" placeholder="Nhập tiêu đề bài viết" class="form-control" name="cont_title" id="cont_title">
                                                <input type="hidden" name="user_id" value="<?php echo UID ?>">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="cont_slug" class="col-lg-2 col-md-2 col-sm-2 control-label" value="">URL</label>
                                            <div class="col-lg-10 col-md-10 col-sm-10">
                                                <input type="text" value="<?php echo $param['cont_slug'] ?>" placeholder="Nhập URL" class="form-control" name="cont_slug" id="cont_slug">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="main_cate_id" class="col-lg-2 col-md-2 col-sm-2 control-label">Thuộc danh mục chính</label>
                                            <div class="col-lg-10 col-md-10 col-sm-10 width-fix">
                                                <select name="main_cate_id" class="selectbox selectpicker"  data-live-search="true" title="Chọn một danh mục chính">
                                                    <?php
                                                    $mainCate= $this->params['main_cate_id'];                                                  
                                                    foreach ($this->arrCategoryList as $category) {
                                                        $depth = substr_count($category['cate_grade'], ':') - 1;
                                                        $str = $depth > 0 ? str_repeat('&nbsp;&nbsp;&nbsp;', $depth - 1) . '&rdsh;&nbsp;' : '';
                                                        ?>
                                                        <option <?php echo ($category['cate_id'] ==  $mainCate) ? 'selected="selected"' : '' ?> value="<?php echo $category['cate_id'] ?>"><?php echo $str . $category['cate_name'] ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="cate_id" class="col-lg-2 col-md-2 col-sm-2 control-label">Thuộc danh mục phụ</label>
                                            <div class="col-lg-10 col-md-10 col-sm-10 width-fix">
                                                <select name="cate_id[]" multiple="multiple" class="selectbox selectpicker"  data-live-search="true" multiple="multiple" title="Chọn các danh mục phụ">
                                                    <?php
                                                    if(is_array($this->params['cate_id']))
                                                        $listCate = $this->params['cate_id'];
                                                    else
                                                        $listCate= explode(',' , $this->params['cate_id']);
                                                    foreach ($this->arrCategoryList as $category) {
                                                        $depth = substr_count($category['cate_grade'], ':') - 1;
                                                        $str = $depth > 0 ? str_repeat('&nbsp;&nbsp;&nbsp;', $depth - 1) . '&rdsh;&nbsp;' : '';
                                                        ?>
                                                        <option <?php echo in_array($category['cate_id'], $listCate) ? 'selected="selected"' : '' ?> value="<?php echo $category['cate_id'] ?>"><?php echo $str . $category['cate_name'] ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="cont_status" class="col-lg-2 col-sm-2 control-label" value="">Tình trạng</label>
                                            <div class="col-lg-10">
                                                <select name="cont_status" class="multi-select form-control sumo-select-box">
                                                    <option <?php echo ($this->params['cont_status'] == 1) ? 'selected' : ''; ?> value="1">Hiển thị</option>
                                                    <option <?php echo ($this->params['cont_status'] == 0) ? 'selected' : ''; ?> value="0">Ẩn</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="cont_summary" class="col-lg-2 col-sm-2 control-label"><b>Tóm tắt nội dung:</b></label>
                                            <div class="col-sm-10">
                                                <textarea placeholder="Nhập nội dung tóm tắt" rows="6" value="" name="cont_summary" class="form-control editor">
                                                    <?php echo $this->params['cont_summary'] ?>
                                                </textarea>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="cont_content" class="col-lg-2 col-sm-2 control-label"><b>Chi tiết nội dung</b></label>
                                            <div class="col-sm-10">
                                                <textarea rows="20" value="" name="cont_content" class="form-control editor">
                                                    <?php echo $this->params['cont_content'] ?>
                                                </textarea>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="tags_name" class="col-lg-2 col-sm-2 control-label">Chọn Tags: </label>
                                            <div class="col-lg-10 col-sm-10">
                                                <input type="text" value="<?php echo $this->params['tags_name']; ?>" placeholder="Nhập tags" class="form-control" name="tags_name" id="tags_name">

                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="cont_meta_title" class="col-lg-2 col-sm-2 control-label" value="">Meta title:</label>
                                            <div class="col-lg-10">
                                                <input type="text" value="<?php echo $this->params['cont_meta_title'] ?>" placeholder="Nhập tiêu đề bài viết" class="form-control" name="cont_meta_title" id="cont_meta_title">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="prod_meta_robot" class="col-lg-2 control-label">Meta Robot: </label>
                                            <div class="col-lg-10">
                                                <select class="form-control" id="cont_meta_robot" name="cont_meta_robot">    
                                                    <option value="index,follow" <?php echo isset($this->params['cont_meta_robot']) && $this->params['cont_meta_robot'] == 'index,follow' ? 'selected="selected"' : ''; ?>>Index,Follow</option>
                                                    <option value="noindex" <?php echo isset($this->params['cont_meta_robot']) && $this->params['cont_meta_robot'] == 'noindex' ? 'selected="selected"' : ''; ?>>Noindex</option>
                                                    <option value="index" <?php echo isset($this->params['cont_meta_robot']) && $this->params['cont_meta_robot'] == 'index' ? 'selected="selected"' : ''; ?>>Index</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="cont_meta_keyword" class="col-lg-2 col-sm-2 control-label">SEO Keywords : </label>
                                            <div class="col-sm-10">
                                                <input type="text" value="<?php echo $this->params['cont_meta_keyword'] ?>" placeholder="Nhập SEO Keywords " class="form-control" name="cont_meta_keyword" id="cont_meta_keyword">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="cont_meta_description" class="col-lg-2 col-sm-2 control-label">SEO Description : </label>
                                            <div class="col-sm-10">
                                                <textarea class="form-control" name="cont_meta_description" id="cont_meta_description" placeholder="Nhập SEO Description"><?php echo $this->params['cont_meta_description'] ?></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="cont_meta_description" class="col-lg-2 col-sm-2 control-label">#</label>
                                            <div class="col-sm-10">
                                                <div class="form-group">
                                                    <div class="col-sm-4">
                                                        <label for="cont_meta_description" class="col-lg-12 control-label">Lượt xem : </label>
                                                        <input type="text" value="<?php echo isset($param['cont_viewer']) ? $param['cont_viewer'] : 1 ?>" placeholder="Nhập mạc định số lượng view" class="form-control" name="cont_viewer" id="cont_viewer">

                                                    </div>
                                                    <div class="col-sm-4">
                                                        <label for="cont_meta_description" class="col-lg-12 control-label">Sắp xếp: </label>
                                                        <input type="text" value="<?php echo isset($param['cont_order']) ? $param['cont_order'] : 1 ?>" placeholder="Nhập sắp xếp" class="form-control" name="cont_order" id="cont_order">
                                                    </div>
                                                    <div class="col-sm-4">
                                                        <label for="cont_meta_description" class="col-lg-12 control-label">Đánh giá : </label>
                                                        <input type="text" value="<?php echo isset($param['cont_rate']) ? $param['cont_rate'] : 1 ?>" placeholder="Nhập rate" class="form-control" name="cont_rate" id="cont_rate">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="cont_meta_description" class="col-lg-2 col-sm-2 control-label">Hình ảnh đại diện</label>
                                            <div class="col-lg-10">
                                                <div>
                                                    <input type="file" name="cont_image" id="cont_image" class="ignore"/>
                                                </div>
                                                <div id="progress"></div>
                                                <ul class="newsImagesList">
                                                    <?php
                                                    $cont_image = json_decode($param['cont_image'], TRUE);
                                                    if ($cont_image):
                                                        ?>
                                                        <li class="newImage" style="background: none repeat scroll 0 0 #FFFFFF;border: 1px solid #DDDDDD;border-radius: 2px 2px 2px 2px;box-shadow: 1px 1px 2px #EEEEEE;float: left;margin: 0 5px 5px 0;padding: 5px;list-style:none outside none;margin-bottom:10px;display:inline;">
                                                            <img class="image" src="<?php echo $cont_image['thumbImage']['150x100'] ?>" alt="" style="display: block;margin-bottom: 10px;">
                                                            <span style="display: block;text-align: right;">
                                                                <a title="Xem" class="view" href="<?php echo $cont_image['sourceImage'] ?>" target="_blank" style="vertical-align: middle;cursor: pointer;display: inline-block;height: 16px;margin-left: 5px;opacity: 0.5;vertical-align: middle;width: 16px;background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAWJJREFUeNqk00soRFEcx/Ez4yIhWSClWNiR0mQjeawssJGVLJTMBnksJNnZeWTDRnntZGdhoWxsJERK2UgTK5mFYrzSXN9TPzVzulPkX5/unXPv/M45/3tvKBqNGpWHRkygFUW4xR5WcWUCKqxjDsZxiA684w55GMIpBhEKCrCD7ZjDK5ZQi0pUYwofWkVXUICdZRI+VnQe13UbOI9p/R5DuRuQiybEMGuCa03ba0OpG+Dp3C7zOUOAvfaY0uy0ANuwN60kx2SuYm3pxQ34xC4qMJzhzz1owQbu3QC7vGVkYwYjms2owb1YRBKbWoUxzn5ONLu9cQF9eECJHmmBVtqJayR+ArIikYhR+gWO1eV61Gl8y96n96IZ+ThSYFpHv3CAc5SpqU96I6uwDTvbKAp1THhOs5J6ieLO+I0auYMGDOhb6Q+b31dMIWcpT6bGM38ru51urGMflyHf981/6luAAQBAI081YdVfOQAAAABJRU5ErkJggg==);"></a>
                                                                <a title="Xóa" class="delete" style="vertical-align: middle;cursor: pointer;display: inline-block;height: 16px;margin-left: 5px;opacity: 0.5;vertical-align: middle;width: 16px;background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAK1JREFUeNpi/P//PwMySE9PPwmkzBgwwZqZM2eGogsyYVGITTMIhGATZMGhWA9o22UkV9kAqcPYFDKmpaU9AdLSDKSDrUBLfEBeeM1AAWCEBSLQmR+AFD8Q+wDxFphXgPgSlA0TfwS0WR5fIB6BMZDDAVmcUCyQBKhqACelBrANuBdgQAgpBcohiYsSMuARlL6HJPYQiX0bSn/EZUAukiG4wH0gLsOaEskFAAEGAE+1LkibLuYpAAAAAElFTkSuQmCC);"></a>
                                                                <div id="jsonData">
                                                                    <input name="cont_image" type="hidden" value="<?php echo $this->escapeHtml($param['cont_image']) ?>">
                                                                </div>
                                                            </span>
                                                        </li>
                                                    <?php endif; ?>

                                                </ul>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button type="submit" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                                                <button type="submit" id="done" class="btn btn-success bt-save" name="save_close"><i class="icon-save"></i> Lưu & Thoát</button> 
                                                <input value="0" name="is_close" class="is_close" type="hidden" />
                                            </div>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </section>
                    </div>

                </div>
        </div>

    </div>
</section>
<script type="text/javascript">
    Content.index();
    Content.upload();
</script>


