<?php
$optionBrand = "";
foreach ($this->arrBrand as $cate) {
    $optionBrand.= isset($this->params["brandId"]) ? '<option  ' . (($this->params["brandId"] == $cate['cate_id']) ? "selected" : "") . ' value="' . $cate['cate_id'] . '" class="level-' . substr_count($cate['cate_grade'], ":") . '">' . $strSpace . $cate['cate_name'] . '</option>' : '<option  ' . (($this->detailLinkCateBrand["link_cate_brand_brand"] == $cate['cate_id']) ? "selected" : "") . ' value="' . $cate['cate_id'] . '" class="level-' . substr_count($cate['cate_grade'], ":") . '">' . $strSpace . $cate['cate_name'] . '</option>';
}
?>
<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-edit-link-cate-brand')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>

    <div class="row" id="frmAddCity">
        <div class="col-lg-12">
            <section class="panel">
                <header id="frmTitle" class="panel-heading">Chỉnh sửa Meta theo danh mục và thương hiệu</header>
                <div class="panel-body">
                    <form id="frm" role="form" class="form-horizontal tasi-form" method="POST">
                        <div class="form-group">
                            <label class="col-lg-2 col-md-2 col-sm-2 control-label"> Tên Danh mục</label>
                            <div class="col-lg-10 col-md-10 col-sm-10 width-fix">
                                <select name="cateId" class="selectbox selectpicker main_cate_id" data-live-search="true" title="Chọn một danh mục">
                                    <?php
                                    $Cate = $this->detailLinkCateBrand['link_cate_brand_category'];
                                    foreach ($this->arrCategoryList as $category) {
                                        if ($category["cate_type"] == 0) {
                                            $depth = substr_count($category['cate_grade'], ':') - 1;
                                            $str = $depth > 0 ? str_repeat('&nbsp;&nbsp;&nbsp;', $depth - 1) . '&rdsh;&nbsp;' : '';
                                            ?>
                                            <option <?php echo ($category['cate_id'] == $Cate) ? 'selected="selected"' : '' ?> value="<?php echo $category['cate_id'] ?>"><?php echo $str . $category['cate_name'] ?></option>
                                        <?php }
                                    } ?>
                                </select> 
                                <img class="loading" style="width: 100px; margin-top: -3px;  position: fixed; z-index: 5; display: none; margin-left: 25%;" src="<?php echo STATIC_URL . '/b/images/ajax_loader_blue.gif' ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_slug" class="col-lg-2 col-md-2 col-sm-2 control-label"> Tên Thương hiệu</label>
                            <div class="col-lg-10 col-md-10 col-sm-10 width-fix">
                                <select name="brandId" class="selectbox selectpicker brand_id" data-live-search="true" title="Chọn một thương hiệu">
                                    <?php echo $optionBrand ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="cate_status" class="col-lg-2 col-md-2 col-sm-2 control-label">Trạng thái</label>
                            <div class="col-lg-10 col-md-10 col-sm-10">
                                <select class="form-control sumo-select-box" id="cont_status" name="link_status">    
                                    <option value="1" <?php echo ($this->detailLinkCateBrand['link_status'] == 1) ? 'selected' : ''; ?>>Hiện</option>
                                    <option value="0" <?php echo ($this->detailLinkCateBrand['link_status'] == 0) ? 'selected' : ''; ?>>Ẩn</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_detail" class="col-lg-2 col-md-2 col-sm-2 col-sm-2 control-label">Mô tả</label>
                            <div class="col-sm-10">
                                <textarea rows="6" value="" name="LinkDescription" class="form-control editor"><?php echo isset($this->params["LinkDescription"]) ? $this->params["LinkDescription"] : $this->detailLinkCateBrand['link_description']; ?></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_meta_title" class="col-lg-2 col-md-2 col-sm-2 control-label">SEO Title</label>
                            <div class="col-lg-6">
                                <input class="form-control" type="text" name="LinkMetaTitle" value ="<?php echo $this->detailLinkCateBrand['link_meta_title'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_meta_keyword" class="col-lg-2 col-md-2 col-sm-2 control-label">SEO Keyword</label>
                            <div class="col-lg-6">
                                <input class="form-control" type="text" name="LinkMetaKeyword" value ="<?php echo $this->detailLinkCateBrand['link_meta_keyword'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_meta_description" class="col-lg-2 col-md-2 col-sm-2 control-label">SEO Description</label>
                            <div class="col-lg-6">
                                <input class="form-control" type="text" name="LinkMetaDescription" value ="<?php echo $this->detailLinkCateBrand['link_meta_description'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_meta_social" class="col-lg-2 col-md-2 col-sm-2 control-label">SEO Social</label>
                            <div class="col-lg-6">
                                <input class="form-control" type="text" name="LinkMetaSocial" value ="<?php echo $this->detailLinkCateBrand['link_meta_social'] ?>">
                            </div>
                        </div>                      

                        <div class="form-group">
                            <div class="col-lg-offset-3 col-lg-10 col-md-10 col-sm-10">
                                <button type="submit" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                                <button type="submit" id="done" class="btn btn-success bt-save" name="save_close"><i class="icon-save"></i> Lưu & Thoát</button> 
                                <input value="0" name="is_close" class="is_close" type="hidden" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
</section>
<script>
    LinkCateBrand.index();
</script>

