<?php
$arrCategoryDetailList = $this->arrCategoryDetailList;
$arrBrandDetailList = $this->arrBrandDetailList;
$CateDetailList = $this->CateDetailList;
$param = $this->params;
?>
<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-link-cate-brand')->getMessages(), $this->flashMessenger()->setNamespace('success-edit-link-cate-brand')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>

    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">Danh sách Meta</header>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-2">                  
                            <div id="editable-sample_length" class="dataTables_length no-padding">
                                <a class="btn btn-primary" href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'LinkCategoryBrand', 'action' => 'add')); ?>" ><i class="icon-plus-sign-alt"></i> Thêm</a>
<!--                                <a class="btn btn-danger remove-all" href="javascript:;" ><i class="icon-trash "></i> Xóa</a>-->
                            </div>
                        </div>
                        <div class="col-lg-10">
                            <form id="frm" class="form-horizontal" role="form" method="GET">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="row sumo100">
                                            <div class="col-sm-6">
                                                <select  id="cate" class="selectbox selectpicker"  multiple="multiple"  data-live-search="true" title="Chọn danh mục">
                                                    <?php
                                                    if (is_array($param['cate_id'])) {
                                                        $listCate = $param['cate_id'];
                                                    } else {
                                                        $listCate = explode(',', $param['cate_id']);
                                                    }
                                                    foreach ($CateDetailList as $category) {
                                                        $depth = substr_count($category['cate_grade'], ':') - 1;
                                                        $str = $depth > 0 ? str_repeat('&nbsp;&nbsp;&nbsp;', $depth - 1) . '&rdsh;&nbsp;' : '';
                                                        ?>
                                                        <option <?php echo in_array($category['cate_id'], $listCate) ? 'selected="selected"' : '' ?> value="<?php echo $category['cate_id'] ?>"><?php echo $str . $category['cate_name'] ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                            <input type="hidden" name="cate_id" id ="cate_id" value="<?php echo $this->params['cate_id'] ?>">
                                            <div class="col-sm-6">
                                                <select width="100%" id="brand" class="selectbox selectpicker"  multiple="multiple"  data-live-search="true" title="Chọn thương hiệu">
                                                    <?php
                                                    if (is_array($param['brand_id'])) {
                                                        $listBrand = $param['brand_id'];
                                                    } else {
                                                        $listBrand = explode(',', $param['brand_id']);
                                                    }
                                                    foreach ($arrBrandDetailList as $brand) {
                                                        ?>
                                                        <option <?php echo in_array($brand['cate_id'], $listBrand) ? 'selected="selected"' : '' ?> value="<?php echo $brand['cate_id'] ?>"><?php echo $brand['cate_name'] ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                            <input type="hidden" name="brand_id" id ="brand_id" value="<?php echo $this->params['brand_id'] ?>">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="row">
                                            <div class="col-sm-8">
                                                <div class="dataTables_filter no-padding per-100">
                                                    <label><input  name="s"  value="<?php echo $this->params["s"]; ?>" type="text" aria-controls="editable-sample" class="per-100 input-seaching form-control medium"></label>
                                                </div>
                                            </div>
                                            <div class="col-sm-4">
                                                <button type="submit"  class="btn btn-white per-100" ><i class="icon-search"></i> Tìm kiếm</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <section id="unseen">
                        <table class="table table-bordered table-striped table-condensed cf">
                            <thead class="cf">
                                <tr>
                                    <th class="numeric text-center">#</th>
                                    <th class="numeric text-center visible-lg visible-xs visible-sm visible-md">Tên danh mục</th>
                                    <th class="numeric text-center">Tên nhãn hiệu</th>

                                    <th class="numeric text-center">Trạng thái</th>
                                    <th class="numeric text-center">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if ($this->arrLinkCateBrandList):
                                    foreach ($this->arrLinkCateBrandList as $arrLinkCateBrandList):
                                        ?>
                                        <tr>
                                            <td class="text-center" width="50"><?php echo $arrLinkCateBrandList['link_cate_brand_id'] ?></td>
                                            <td class="visible-lg visible-xs visible-sm visible-md" width="150">
                                                <?php
                                                $value = $arrLinkCateBrandList['link_cate_brand_category'];
                                                $temp = substr_count($arrCategoryDetailList[$value]['cate_grade'], ':');
                                                echo str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;', $temp);
                                                if ($temp > 0) {
                                                    echo '&#x21b3;&nbsp;&nbsp;';
                                                }
                                                if (isset($arrCategoryDetailList[$value]['cate_name'])) {
                                                    echo $arrCategoryDetailList[$value]['cate_name'];
                                                }
                                                ?>
                                            </td>
                                            <td width="100">
                                                <?php
                                                $value = $arrLinkCateBrandList['link_cate_brand_brand'];
                                                if (isset($arrCategoryDetailList[$value]['cate_name'])) {
                                                    echo $arrCategoryDetailList[$value]['cate_name'];
                                                }
                                                ?>
                                            </td>

                                            <td  class="numeric text-center" width="50"><?php if ($arrLinkCateBrandList['link_status'] == 1): ?><a href="javascript:;" class="tooltips" data-placement="top" data-original-title="Đang hiện"><i class="icon-ok color-success"></a><?php
                                                endif;
                                                if ($arrLinkCateBrandList['link_status'] == 0):
                                                    ?><a href="javascript:;" class="tooltips" data-placement="top" data-original-title="Đang ẩn"><i class="icon-minus-sign color-danger"></i></a><?php endif; ?></td>
                                            <td class="numeric text-center" width="100">
                                                <a  href="<?php echo $this->serverUrl() . $this->Url('category', array('controller' => 'category', 'action' => 'index', 'categorySlug' => $arrCategoryDetailList[$arrLinkCateBrandList['link_cate_brand_category']]['cate_slug'], 'categoryID' => $arrCategoryDetailList[$arrLinkCateBrandList['link_cate_brand_category']]['cate_id'], 'brand' => $arrCategoryDetailList[$value]['cate_slug'])); ?>" target="_bank"  class="btn btn-primary btn-xs"><i class="icon-eye-open"></i> Xem</a>
                                                <a href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'LinkCategoryBrand', 'action' => 'edit', 'id' => $arrLinkCateBrandList['link_cate_brand_id'])); ?>" class="btn btn-primary btn-xs edit"><i class="icon-pencil"></i> Sửa</a>
                                                <a  class="btn btn-danger btn-xs remove tooltips" data-placement="top" data-original-title="Xóa meta" rel="<?php echo $arrLinkCateBrandList['link_cate_brand_id'] ?>"><i class="icon-trash "></i> Xóa</a>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr><td colspan="8" class="text-center">Hiện tại chưa có dữ liệu.</td></tr>
                                <?php endif ?>
                            </tbody>
                        </table>
                    </section>
                    <div>
                        <div class="row">
                            <div  class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <div  class="col-lg-3 col-sm-3 col-md-3 col-xs-3">
                                        <select name="limit" class="form-control" onchange="window.location.href = this.value">
                                            <option value="<?php echo $this->serverUrl() . $this->Url('backend-meta-search', array('controller' => 'LinkCategoryBrand', 'action' => 'index', 'limit' => 15, 's' => $this->params["s"], 'cate_id' => $this->params["cate_id"], 'brand_id' => $this->params["brand_id"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 15 ? "selected" : "" ?>>15</option>
                                            <option value ="<?php echo $this->serverUrl() . $this->Url('backend-meta-search', array('controller' => 'LinkCategoryBrand', 'action' => 'index', 'limit' => 30, 's' => $this->params["s"], 'cate_id' => $this->params["cate_id"], 'brand_id' => $this->params["brand_id"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 30 ? "selected" : "" ?>>30</option>
                                            <option value ="<?php echo $this->serverUrl() . $this->Url('backend-meta-search', array('controller' => 'LinkCategoryBrand', 'action' => 'index', 'limit' => 100, 's' => $this->params["s"], 'cate_id' => $this->params["cate_id"], 'brand_id' => $this->params["brand_id"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 100 ? "selected" : "" ?>>100</option>
                                            <option value ="<?php echo $this->serverUrl() . $this->Url('backend-meta-search', array('controller' => 'LinkCategoryBrand', 'action' => 'index', 'limit' => 300, 's' => $this->params["s"], 'cate_id' => $this->params["cate_id"], 'brand_id' => $this->params["brand_id"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 300 ? "selected" : "" ?>>300</option>
                                            <option value ="<?php echo $this->serverUrl() . $this->Url('backend-meta-search', array('controller' => 'LinkCategoryBrand', 'action' => 'index', 'limit' => 500, 's' => $this->params["s"], 'cate_id' => $this->params["cate_id"], 'brand_id' => $this->params["brand_id"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 500 ? "selected" : "" ?>>500</option>
                                            <option value ="<?php echo $this->serverUrl() . $this->Url('backend-meta-search', array('controller' => 'LinkCategoryBrand', 'action' => 'index', 'limit' => 1000, 's' => $this->params["s"], 'cate_id' => $this->params["cate_id"], 'brand_id' => $this->params["brand_id"])); ?>" <?php echo!empty($this->params["limit"]) && $this->params["limit"] == 1000 ? "selected" : "" ?>>1000</option>
                                        </select>
                                    </div>
                                    <div class = "col-sm-3" style = "padding-top: 10px">Dòng</div>
                                </div>
                            </div>
                            <div class = "col-lg-6">
                                <?php echo $this->paging;
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    $('.sumo-multiple-select-box').SumoSelect();
    LinkCateBrand.index();
</script>
