<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-remove-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-category')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="icon-remove"></i>
            </button>
            <h4><i class="icon-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>

    <div class="row" id="frmAddCity">
        <div class="col-lg-12">
            <section class="panel panel-primary">
                <header id="frmTitle" class="panel-heading">Thêm Danh mục bài viết</header>
                <div class="panel-body">
                    <form id="frm" role="form" class="form-horizontal tasi-form" method="POST">
                        <div class="form-group">
                            <label class="col-lg-2 control-label"> Tên Danh mục</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="CategoryName" placeholder="Nhập Tên danh mục " value="<?php echo $this->params['CategoryName'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_slug" class="col-lg-2 control-label"> Tên không dấu</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="CateSlug" placeholder="Nhập Tên không dấu" value="<?php echo $this->params['CateSlug'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"> Thuộc Nhóm :</label>
                            <div class="col-lg-10">
                                <select name="parentID" class="form-control">
                                    <option value="0">Chọn Nhóm</option>
                                    <?php foreach ($this->arrCategoryList as $arrCategoryList) { ?>
                                        <option value="<?php echo $arrCategoryList['cate_id'] ?>" <?php if ($arrCategoryList['cate_id'] == $this->params['parentID']) { ?> selected <?php } ?>>
                                            <?php
                                            $temp = substr_count($arrCategoryList['cate_grade'], ':');
                                            if ($temp > 0) {
                                                if ($arrCategoryList['cate_parent'] != 0) {
                                                    echo str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;', $temp);
                                                    echo '&#x21b3;&nbsp;&nbsp;';
                                                }
                                            }
                                            echo $arrCategoryList['cate_name'];
                                            ?>
                                        </option>
<?php } ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_order" class="col-lg-2 control-label">Độ ưu tiên</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="CateOrder" placeholder="Nhập độ ưu tiên" value="<?php echo $this->params['CateOrder'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_description" class="col-lg-2 control-label">Mô tả ngắn về Danh mục</label>
                            <div class="col-lg-10">
                                <textarea placeholder="Nhập mô tả" rows="6" name="cate_description" id="Sumary" class="form-control editor" style="">
                                   
                                </textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_meta_title" class="col-lg-2 control-label">SEO Meta Title</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="CateMetaTitle" placeholder="Nhập SEO Meta Title" value="<?php echo $this->params['CateMetaTitle'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_meta_keyword" class="col-lg-2 control-label">SEO Meta Keyword</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="CateMetaKeyword" placeholder="Nhập SEO Meta Keyword" value="<?php echo $this->params['CateMetaKeyword'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_meta_description" class="col-lg-2 control-label">SEO Meta Description</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="CateMetaDescription" placeholder="Nhập SEO Meta Description" value="<?php echo $this->params['CateMetaDescription'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="cate_meta_social" class="col-lg-2 control-label">SEO Meta Social</label>
                            <div class="col-lg-10">
                                <input class="form-control" type="text" name="CateMetaSocial" placeholder="Nhập SEO Meta Social" value="<?php echo $this->params['CateMetaSocial'] ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-lg-offset-3 col-lg-10">
                                <button type="submit" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                                <button type="submit" id="done" class="btn btn-success bt-save" name="save_close"><i class="icon-save"></i> Lưu & Thoát</button> 
                                <input value="0" name="is_close" class="is_close" type="hidden" />
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
</section>
<script type="text/javascript">
    Categorynews.index();
</script>