<?php

use My\General;
?>
<div id="content">
    <div class="block-head">
        <div class="menu">
            <div class="m-level">
                <div class="title">
                    <span class="icon i-list"></span> <div class="text">TẤT CẢ DANH MỤC</div>
                </div>
                <div class="list">
                </div>
            </div>
        </div>
        <div class="breadcrumb" itemscope itemtype="http://data-vocabulary.org/Breadcrumb">            
            <div class="br-hidden">
                <div class="item item-end">
                    <div class="ar-right">
                        <div class="cont">
                            <a style="text-decoration: none" itemprop="url"><span itemprop="title">Gian hàng</span></a>
                        </div>
                    </div>
                </div>
            </div
        </div>
        <div style="clear: both;"></div>
    </div>
    <div class="block-content">
        <div class="left">
            <?php
            if ($this->arrCategoryParentList) {
                ?>
                <div class="box">
                    <div class="head box-head">
                        DANH MỤC SẢN PHẢM
                    </div>
                    <div class="cont">
                        <ul class="menu ">
                            <?php
                            $arrCate = array();
                            foreach ($this->arrCategoryParentList as $key => $value) {
                                $arrCate[$key] = $value;
                                $arrParams = array('controller' => 'category', 'action' => 'index', 'categorySlug' => $value["cate_slug"], 'categoryID' => $value["cate_id"], 'brand' => $brand);
                                $this->params['price'] ? $arrParams['price'] = $this->params['price'] : '';
                                $this->params['s'] ? $arrParams['s'] = str_replace(' ', '+', $this->params['s']) : '';
                                $this->params['sort'] ? $arrParams['sort'] = str_replace(' ', '+', $this->params['sort']) : '';
                                $cateLink = $this->serverUrl() . $this->Url('category', $arrParams);
                                $arrCate[$key]["cate_link"] = $cateLink;
                            }
                            $arrInput = My\General::arrCateInput($arrCate, $arrCate[0]['cate_id']);
                            echo My\General::arrCateOutput($arrInput, 1, $this->params['categoryID'])["result"];
                            ?>

                        </ul>
                    </div>
                </div>
                <?php
            }
            ?>
        </div>

        <div class="main">
            <div class="list-prod">
                <div class="title" style="    height: 50px;    font-size: 13px;">
                    <h1>

                        <?php
                        echo $arrStand["stan_name"];
                        ?>
                    </h1><br/>
                    <div class="info">
                        <div><strong>Thông tin gian hàng</strong></div>
                        Email: <a href="#" style="    color: #4681C3;"><?php echo $arrStand["stan_email"] ?></a> | Phone: <a style="    color: #EC5657;" href="#"><?php echo $arrStand["stan_phone"] ?></a>
                    </div>
                </div>
                <?php if ($this->arrProductList) { ?>
                    <div class="bar">
                        <div class="tabs">
                            <div class="item active" data-view="grid">
                                <div class="icon grid">

                                </div>
                            </div>
                            <div class="item" data-view="list">
                                <div class="icon list">

                                </div>
                            </div>
                        </div>

                        <div class="chonse">
                            <div class="sort">
                                <?php
                                $arrParams = array('controller' => 'category', 'action' => 'index', 'brand' => $this->params['brand'], 'categoryID' => $this->params['categoryID'], 'categorySlug' => $this->params['categorySlug'], 'price' => $this->params['price']);
                                ?>
                                Sắp xếp
                                <select name="sort" id="sort">
                                    <?php
                                    $arrParams['sort'] = 'id_desc';
                                    $linkSort = $this->serverUrl() . $this->Url('category', $arrParams);
                                    ?>
                                    <option value="<?php echo $linkSort; ?>" <?php echo $this->params['sort'] == 'id_desc' ? 'selected' : null ?>>Sản phẩm mới</option>
                                    <?php
                                    $arrParams['sort'] = 'id_asc';
                                    $linkSort = $this->serverUrl() . $this->Url('category', $arrParams);
                                    ?>
                                    <option value="<?php echo $linkSort; ?>" <?php echo $this->params['sort'] == 'id_asc' ? 'selected' : null ?>>Sản phẩm cũ</option>
                                    <?php
                                    $arrParams['sort'] = 'price_desc';
                                    $linkSort = $this->serverUrl() . $this->Url('category', $arrParams);
                                    ?>
                                    <option value="<?php echo $linkSort; ?>" <?php echo $this->params['sort'] == 'price_desc' ? 'selected' : null ?>>Giá giảm dần</option>
                                    <?php
                                    $arrParams['sort'] = 'price_asc';
                                    $linkSort = $this->serverUrl() . $this->Url('category', $arrParams);
                                    ?>
                                    <option value="<?php echo $linkSort; ?>" <?php echo $this->params['sort'] == 'price_asc' ? 'selected' : null ?>>Giá tăng dần</option>
                                </select>
                            </div>
                            <?php
                            if ($this->countPage) {
                                $arrParams = array('controller' => 'category', 'action' => 'index', 'brand' => $this->params['brand'], 'categoryID' => $this->params['categoryID'], 'categorySlug' => $this->params['categorySlug'], 'price' => $this->params['price']);
                                $this->params['s'] ? $arrParams['s'] = str_replace(' ', '+', $this->params['s']) : '';
                                $this->params['sort'] ? $arrParams['sort'] = str_replace(' ', '+', $this->params['sort']) : '';
                                ?>
                                <div class="pagging">
                                    Xem
                                    <select name="page" class="view-page">
                                        <?php
                                        for ($i = 1; $i <= $this->countPage; $i++) {
                                            $arrParams['page'] = $i;
                                            $linkPage = $this->serverUrl() . $this->Url('category', $arrParams);
                                            ?>
                                            <option value="<?php echo $linkPage; ?>" <?php echo $i == $this->params['page'] ? 'selected' : null ?>><?php echo $i; ?></option>
                                        <?php } ?>
                                    </select> /  Trang
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                <?php } ?>
            </div>
            <div class="view-list grid">
                <?php
                if ($this->arrProductList) :
                    foreach ($this->arrProductList as $arrProductList) :
                        $prodLink = $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $arrProductList["prod_slug"], 'productId' => $arrProductList['prod_id']));
                        ?>
                        <div class="item">
                            <div class="img">
                                <a href="<?php echo $prodLink ?>" rel="nofollow" title="<?php echo $arrProductList['prod_name']; ?>" ><img class="lazy" data-original="<?php echo json_decode($arrProductList['prod_image'], TRUE)['thumbImage']['224x224']; ?>" /></a>
                            </div>
                            <?php
                            if ($arrProductList['prod_call_price'] != 1):
                                if ($arrProductList['prod_is_promotion'] == 1):
                                    $percent = 100 - ($arrProductList['prod_promotion_price'] * 100 / $arrProductList['prod_price']);
                                    ?>
                                    <div class="icon">
                                        <!--<div class="gift"></div>-->
                                        <div class="discount">
                                            <?php
                                            echo number_format($percent, 0, ",", ".") . '%';
                                            ?>
                                        </div>
                                    </div>
                                    <?php
                                endif;
                            endif;
                            ?>
                            <div class="info">
                                <div class="title">
                                    <a href="<?php echo $prodLink ?>" title="<?php echo $arrProductList['prod_name']; ?>" ><?php echo $arrProductList['prod_name']; ?></a>
                                </div>
                                <div class="rate">
                                    <?php
                                    $rate = round($arrProductList['prod_rate'] / $arrProductList['prod_count_rate'], 0);
                                    $rate = (round(($rate / 2), 0) * 2);
//                                    $rate = $rate >= 5 ? $rate : 5;
                                    ?>
                                    <div class="star star-<?php echo $rate > 20 ? 20 : $rate; ?>"> <?php echo $rate ? '( ' . $arrProductList['prod_count_rate'] . ' đánh giá )' : '( ' . $arrProductList['prod_count_rate'] . ' đánh giá )'; ?></div> <!-- 5,10,15,20,25,30,35,40,45,50 -->
                                </div>
                                <div class="price">
                                    <div class="current">
                                        <?php
                                        if ($arrProductList['prod_call_price'])
                                            echo 'Liên hệ để biết giá';
                                        else if ($arrProductList['prod_is_promotion'] && !$arrProductList['prod_call_price'])
                                            echo number_format($arrProductList['prod_promotion_price'], 0, '', '.') . ' VNĐ';
                                        else if (!$arrProductList['prod_is_promotion'] && !$arrProductList['prod_call_price'])
                                            echo number_format($arrProductList['prod_price'], 0, '', '.') . ' VNĐ';
                                        ?>
                                    </div>
                                    <div class="promot">
                                        <?php
                                        if ($arrProductList['prod_call_price'])
                                            echo '';
                                        else if ($arrProductList['prod_is_promotion'] && !$arrProductList['prod_call_price'])
                                            echo number_format($arrProductList['prod_price'], 0, '', '.') . ' VNĐ';
                                        ?>
                                    </div>
                                </div>
                                <div class="desc">
                                    <?php echo html_entity_decode($arrProductList['prod_description']); ?>
                                </div>
                                <div class="read-more"><a href="<?php echo $prodLink ?>">Xem chi tiết</a></div>
                            </div>
                        </div>
                        <?php
                    endforeach;
                else:
                    ?>
                    <p>Không tìm thấy sản phẩm ... </p>
                <?php endif; ?>
                <div style="clear: both"></div>
            </div>        
            <div class="paging">
                <?php echo $this->paging; ?>
            </div>
        </div>
    </div>
    <div style="clear: both;"></div>
</div>
